// packages/svelte/examples/popover/scroll-area.svelte
<script lang="ts">
import { Button, Popover } from "@pisagor/svelte";

const items = Array.from({ length: 12 }, (_, i) => ({
  id: i + 1,
  label: `Item ${i + 1}`,
}));
</script>

<Popover>
  <Popover.Trigger>
    <Button variant="outline"> Open </Button>
  </Popover.Trigger>
  <Popover.Content class="h-80 w-72">
    <Popover.Header title="Scrollable content" />
    <Popover.Body>
      <ul class="flex flex-col gap-1">
        {#each items as item}
          <li class="rounded-md px-2 py-1.5 text-sm hover:bg-muted">
            {item.label}
          </li>
        {/each}
      </ul>
    </Popover.Body>
    <Popover.Footer>
      <Popover.CloseTrigger>
        {#snippet asChild(
  props,
)}
          <Button {...props()}>Close</Button>
        {/snippet}
      </Popover.CloseTrigger>
    </Popover.Footer>
  </Popover.Content>
</Popover>

// packages/react/examples/popover/scroll-area.tsx
import { Button, Popover } from "@pisagor/react";
export function ScrollArea() {
  const items = Array.from({ length: 12 }, (_, i) => ({
    id: i + 1,
    label: `Item ${i + 1}`,
  }));
  return (
    <Popover>
      <Popover.Trigger asChild>
        <Button variant="outline">Open</Button>
      </Popover.Trigger>
      <Popover.Content className="h-80 w-72">
        <Popover.Header title="Scrollable content" />
        <Popover.Body>
          <ul className="flex flex-col gap-1">
            {items.map((item) => (
              <li
                className="rounded-md px-2 py-1.5 text-sm hover:bg-muted"
                key={item.id}
              >
                {item.label}
              </li>
            ))}
          </ul>
        </Popover.Body>
        <Popover.Footer>
          <Popover.CloseTrigger asChild>
            <Button>Close</Button>
          </Popover.CloseTrigger>
        </Popover.Footer>
      </Popover.Content>
    </Popover>
  );
}
