// packages/svelte/examples/qr-code/sizes.svelte
<script lang="ts">
import { QrCode } from "@pisagor/svelte";
</script>

<div class="flex flex-wrap items-end justify-center gap-2">
  <QrCode class="[--qr-code-size:6rem]">
    <QrCode.Frame class="rounded-md border" />
  </QrCode>
  <QrCode class="[--qr-code-size:8rem]">
    <QrCode.Frame class="rounded-md border" />
  </QrCode>
</div>

// packages/react/src/components/qr-code/examples/sizes.tsx
import { QrCode } from "..";

export function Sizes() {
  return (
    <div className="flex flex-wrap items-end justify-center gap-2">
      <QrCode className="[--qr-code-size:6rem]">
        <QrCode.Frame className="rounded-md border" />
      </QrCode>
      <QrCode className="[--qr-code-size:8rem]">
        <QrCode.Frame className="rounded-md border" />
      </QrCode>
    </div>
  );
}
