// packages/solid/src/components/accordion/accordion.tsx
import {
  type AccordionItemContentProps,
  type AccordionItemTriggerProps,
  Accordion as AccordionPrimitive,
  type AccordionItemProps as AccordionPrimitiveItemProps,
  type AccordionRootProps,
} from "@ark-ui/solid/accordion";
import type { AccordionItemProps as BaseAccordionItemProps } from "@pisagor/props";
import { accordionItemRecipe } from "@pisagor/recipes";
import type { JSX } from "solid-js";
import { For, splitProps } from "solid-js";
import { CaretDownIcon } from "../../internal/icons";
import { AccordionItemContext, useAccordionItem } from "./accordion.context";

export interface AccordionItemProps
  extends AccordionPrimitiveItemProps,
    BaseAccordionItemProps {}

interface AccordionPresetItem {
  value: string;
  title: JSX.Element;
  content: JSX.Element;
  disabled?: boolean;
}

export interface AccordionProps extends Omit<AccordionRootProps, "children"> {
  items?: AccordionPresetItem[];
}

export function AccordionRoot(props: AccordionRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["collapsible", "children"]);
  return (
    <AccordionPrimitive.Root {...rest} collapsible={local.collapsible ?? true}>
      {local.children}
    </AccordionPrimitive.Root>
  );
}

export function AccordionItem(props: AccordionItemProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? accordionItemRecipe)();

  return (
    <AccordionItemContext value={{ slots: slots() }}>
      <AccordionPrimitive.Item
        {...rest}
        class={slots().base({ class: local.class })}
      >
        {local.children}
      </AccordionPrimitive.Item>
    </AccordionItemContext>
  );
}

export function AccordionItemTrigger(
  props: AccordionItemTriggerProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useAccordionItem();

  return (
    <AccordionPrimitive.ItemTrigger
      {...rest}
      class={slots.trigger({ class: local.class })}
    >
      {local.children}
      <AccordionPrimitive.ItemIndicator>
        <CaretDownIcon class={slots.indicator()} />
      </AccordionPrimitive.ItemIndicator>
    </AccordionPrimitive.ItemTrigger>
  );
}

export function AccordionItemContent(
  props: AccordionItemContentProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useAccordionItem();

  return (
    <AccordionPrimitive.ItemContent
      {...rest}
      class={slots.content({ class: local.class })}
    >
      <div class={slots.body()}>{local.children}</div>
    </AccordionPrimitive.ItemContent>
  );
}

export function AccordionShorthand(props: AccordionProps): JSX.Element {
  const [local, rest] = splitProps(props, ["items"]);

  return (
    <AccordionRoot {...rest}>
      <For each={local.items}>
        {(item) => (
          <AccordionItem disabled={item.disabled} value={item.value}>
            <AccordionItemTrigger>{item.title}</AccordionItemTrigger>
            <AccordionItemContent>{item.content}</AccordionItemContent>
          </AccordionItem>
        )}
      </For>
    </AccordionRoot>
  );
}

// packages/react/src/components/accordion/accordion.tsx
import type {
  AccordionItemContentProps,
  AccordionItemTriggerProps,
  AccordionItemProps as AccordionPrimitiveItemProps,
  AccordionRootProps,
} from "@ark-ui/react/accordion";
import { Accordion as AccordionPrimitive } from "@ark-ui/react/accordion";
import { CaretDownIcon } from "@phosphor-icons/react";
import type { AccordionItemProps as BaseAccordionItemProps } from "@pisagor/props";
import { accordionItemRecipe } from "@pisagor/recipes";
import type { ReactNode } from "react";
import { AccordionItemContext, useAccordionItem } from "./accordion.context";

// #region Types
export interface AccordionItemProps
  extends AccordionPrimitiveItemProps,
    BaseAccordionItemProps {}

interface AccordionPresetItem {
  value: string;
  title: ReactNode;
  content: ReactNode;
  disabled?: boolean;
}

export interface AccordionProps extends Omit<AccordionRootProps, "children"> {
  items?: AccordionPresetItem[];
}
// #endregion

// #region Parts
export function AccordionRoot({
  collapsible = true,
  children,
  ...rest
}: AccordionRootProps) {
  return (
    <AccordionPrimitive.Root {...rest} collapsible={collapsible}>
      {children}
    </AccordionPrimitive.Root>
  );
}

export function AccordionItem({
  children,
  recipe = accordionItemRecipe,
  className,
  ...rest
}: AccordionItemProps) {
  const slots = recipe();

  return (
    <AccordionItemContext value={{ slots }}>
      <AccordionPrimitive.Item {...rest} className={slots.base({ className })}>
        {children}
      </AccordionPrimitive.Item>
    </AccordionItemContext>
  );
}

export function AccordionItemTrigger({
  children,
  className,
  ...rest
}: AccordionItemTriggerProps) {
  const { slots } = useAccordionItem();

  return (
    <AccordionPrimitive.ItemTrigger
      {...rest}
      className={slots.trigger({ className })}
    >
      {children}

      <AccordionPrimitive.ItemIndicator>
        <CaretDownIcon className={slots.indicator()} />
      </AccordionPrimitive.ItemIndicator>
    </AccordionPrimitive.ItemTrigger>
  );
}

export function AccordionItemContent({
  children,
  className,
  ...rest
}: AccordionItemContentProps) {
  const { slots } = useAccordionItem();

  return (
    <AccordionPrimitive.ItemContent
      {...rest}
      className={slots.content({ className })}
    >
      <div className={slots.body()}>{children}</div>
    </AccordionPrimitive.ItemContent>
  );
}
// #endregion

// #region Shorthand
export function AccordionShorthand({ items, ...rest }: AccordionProps) {
  return (
    <AccordionRoot {...rest}>
      {items?.map((item) => (
        <AccordionItem
          disabled={item.disabled}
          key={item.value}
          value={item.value}
        >
          <AccordionItemTrigger>{item.title}</AccordionItemTrigger>
          <AccordionItemContent>{item.content}</AccordionItemContent>
        </AccordionItem>
      ))}
    </AccordionRoot>
  );
}
// #endregion

// #region Display Names
AccordionRoot.displayName = "Accordion.Root";
AccordionItem.displayName = "Accordion.Item";
AccordionItemTrigger.displayName = "Accordion.ItemTrigger";
AccordionItemContent.displayName = "Accordion.ItemContent";
AccordionShorthand.displayName = "Accordion";
// #endregion
