// packages/react-ui/src/components/tree-view/tree-view.tsx
import { ark } from "@ark-ui/react/factory";
import {
  createTreeCollection as arkCreateTreeCollection,
  type TreeCollection as arkTreeCollection,
  TreeView as TreeViewPrimitive,
} from "@ark-ui/react/tree-view";
import {
  CaretRightIcon,
  CheckIcon,
  FileIcon,
  FolderIcon,
  FolderOpenIcon,
  MinusIcon,
} from "@phosphor-icons/react";
import {
  treeViewBranchVariants,
  treeViewItemVariants,
  treeViewVariants,
} from "@pisagor/recipes/tree-view";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "react";
import { formControlToggleVariants } from "../../internal/form-control/form-control-variants";
import {
  TreeViewBranchContext,
  TreeViewContext,
  type TreeViewContextProps,
  TreeViewItemContext,
  useTreeView,
  useTreeViewBranch,
  useTreeViewItem,
} from "./tree-view.context";

// #region Types
export interface TreeNodeType<T = unknown> {
  children?: TreeNodeType<T>[] | undefined;
  expandedIcon?: JSX.ElementType | null;
  icon?: JSX.ElementType | null;
  id: string;
  name: string;
}

export type TreeCollection = arkTreeCollection;

export type TreeViewProps = TreeViewPrimitive.RootComponentProps & TreeViewContextProps;

export type NodeProviderProps<T extends TreeNodeType = TreeNodeType> =
  TreeViewPrimitive.NodeProviderProps<T>;

export type TreeViewBranchControlProps = ComponentProps<typeof TreeViewPrimitive.BranchControl> &
  Pick<TreeViewBranchTitleProps, "icon" | "expandedIcon">;

export interface TreeViewBranchTitleProps
  extends ComponentProps<typeof TreeViewPrimitive.BranchText> {
  /**
   * Custom expanded icon
   *
   * @defaultValue <FolderOpenIcon />
   */
  expandedIcon?: JSX.ElementType | null;
  /**
   * Custom icon
   *
   * @defaultValue <FolderIcon />
   */
  icon?: JSX.ElementType | null;
}

export type TreeViewItemTitleProps = ComponentProps<typeof TreeViewPrimitive.ItemText>;

export interface TreeViewItemTextProps extends TreeViewItemTitleProps {
  /**
   * Custom file icon
   *
   * @defaultValue <FileIcon />
   */
  icon?: JSX.ElementType;
}

export type TreeViewLabelProps = ComponentProps<typeof TreeViewPrimitive.Label>;

export type TreeViewTreeProps = ComponentProps<typeof TreeViewPrimitive.Tree>;

export type TreeViewBranchProps = ComponentProps<typeof TreeViewPrimitive.Branch>;

export type TreeViewBranchIndicatorProps = ComponentProps<typeof TreeViewPrimitive.BranchIndicator>;

export type TreeViewBranchContentProps = ComponentProps<typeof TreeViewPrimitive.BranchContent>;

export type TreeViewBranchIndentGuideProps = ComponentProps<
  typeof TreeViewPrimitive.BranchIndentGuide
>;

export type TreeViewItemProps = ComponentProps<typeof TreeViewPrimitive.Item>;

export type TreeViewNodeCheckboxProps = ComponentProps<typeof TreeViewPrimitive.NodeCheckbox>;

export type TreeViewNodeInputProps = ComponentProps<typeof TreeViewPrimitive.NodeRenameInput>;

interface TreeViewItemIconProps extends ComponentProps<typeof ark.span> {}
// #endregion

// #region Parts
export const createTreeCollection = <T extends TreeNodeType>(
  options: Parameters<typeof arkCreateTreeCollection<T>>[0],
) =>
  arkCreateTreeCollection<T>({
    nodeToString: (node) => node.name,
    nodeToValue: (node) => node.id,
    ...options,
  });

export function TreeViewRoot({ children, fileIcons, className, ...rest }: TreeViewProps) {
  const slots = treeViewVariants();

  return (
    <TreeViewContext value={{ fileIcons, slots }}>
      <TreeViewPrimitive.Root {...rest} className={slots.base({ className })}>
        {children}
      </TreeViewPrimitive.Root>
    </TreeViewContext>
  );
}

export function TreeViewLabel({ className, ...rest }: TreeViewLabelProps) {
  const { slots } = useTreeView();

  return <TreeViewPrimitive.Label {...rest} className={slots.label({ className })} />;
}

export function TreeViewTree({ className, ...rest }: TreeViewTreeProps) {
  const { slots } = useTreeView();

  return <TreeViewPrimitive.Tree {...rest} className={slots.tree({ className })} />;
}

export const TreeViewNodeProvider = <T extends TreeNodeType>(props: NodeProviderProps<T>) => (
  <TreeViewPrimitive.NodeProvider {...props} />
);

export function TreeViewBranch({ children, className, ...rest }: TreeViewBranchProps) {
  const slots = treeViewBranchVariants();

  return (
    <TreeViewBranchContext value={{ slots }}>
      <TreeViewPrimitive.Branch {...rest} className={slots.base({ className })}>
        {children}
      </TreeViewPrimitive.Branch>
    </TreeViewBranchContext>
  );
}

export function TreeViewBranchControl({
  children,
  expandedIcon,
  icon,
  className,
  ...rest
}: TreeViewBranchControlProps) {
  const { slots } = useTreeView();

  return (
    <TreeViewPrimitive.BranchControl {...rest} className={slots.control({ className })}>
      <TreeViewBranchIndicator />
      <TreeViewBranchTitle expandedIcon={expandedIcon} icon={icon}>
        {children}
      </TreeViewBranchTitle>
    </TreeViewPrimitive.BranchControl>
  );
}

function TreeViewBranchTitle({
  children,
  expandedIcon: ExpandedIcon,
  icon: Icon,
  className,
  ...rest
}: TreeViewBranchTitleProps) {
  const { slots } = useTreeViewBranch();

  return (
    <TreeViewPrimitive.NodeContext>
      {(nodeState) => (
        <>
          {nodeState.renaming ? (
            <TreeViewNodeInput />
          ) : (
            <TreeViewPrimitive.BranchText {...rest} className={slots.title({ className })}>
              {Icon !== null && !nodeState.expanded && (
                <TreeViewItemIcon>{Icon ? <Icon /> : <FolderIcon />}</TreeViewItemIcon>
              )}
              {ExpandedIcon !== null && nodeState.expanded && (
                <TreeViewItemIcon>
                  {ExpandedIcon ? <ExpandedIcon /> : <FolderOpenIcon />}
                </TreeViewItemIcon>
              )}
              {children}
            </TreeViewPrimitive.BranchText>
          )}
        </>
      )}
    </TreeViewPrimitive.NodeContext>
  );
}

export function TreeViewBranchIndicator({ className, ...rest }: TreeViewBranchIndicatorProps) {
  const { slots } = useTreeViewBranch();

  return (
    <TreeViewPrimitive.BranchIndicator {...rest} className={slots.indicator({ className })}>
      <CaretRightIcon />
    </TreeViewPrimitive.BranchIndicator>
  );
}

export function TreeViewBranchContent({
  children,
  className,
  ...rest
}: TreeViewBranchContentProps) {
  const { slots } = useTreeViewBranch();

  return (
    <TreeViewPrimitive.BranchContent {...rest} className={slots.content({ className })}>
      <TreeViewBranchIndentGuide />

      {children}
    </TreeViewPrimitive.BranchContent>
  );
}

function TreeViewBranchIndentGuide({ className, ...rest }: TreeViewBranchIndentGuideProps) {
  const { slots } = useTreeViewBranch();

  return (
    <TreeViewPrimitive.BranchIndentGuide {...rest} className={slots.indentGuide({ className })} />
  );
}

export function TreeViewItem({ children, className, ...rest }: TreeViewItemProps) {
  const { slots } = useTreeView();
  const itemSlots = treeViewItemVariants();

  return (
    <TreeViewItemContext value={{ slots: itemSlots }}>
      <TreeViewPrimitive.Item {...rest} className={slots.control({ className })}>
        {children}
      </TreeViewPrimitive.Item>
    </TreeViewItemContext>
  );
}

export function TreeViewItemText({
  children,
  icon: Icon = FileIcon,
  className,
  ...rest
}: TreeViewItemTextProps) {
  const { fileIcons } = useTreeView();

  const getFileIcon = (value: string): JSX.ElementType => {
    const extension = getFileExtension(value);
    const resolved = extension ? fileIcons?.[extension] : undefined;
    return resolved ?? Icon;
  };

  return (
    <TreeViewPrimitive.NodeContext>
      {(nodeState) => {
        const ResolvedIcon = getFileIcon(nodeState.value);

        return (
          <>
            <TreeViewItemIcon>
              <ResolvedIcon />
            </TreeViewItemIcon>

            {nodeState.renaming ? (
              <TreeViewNodeInput />
            ) : (
              <TreeViewItemTitle {...rest} className={className}>
                {children}
              </TreeViewItemTitle>
            )}
          </>
        );
      }}
    </TreeViewPrimitive.NodeContext>
  );
}

function TreeViewItemIcon({ className, ...rest }: TreeViewItemIconProps) {
  const item = useTreeViewItem();
  const slots = item?.slots ?? treeViewItemVariants();

  return (
    <ark.span
      {...rest}
      className={slots.icon({ className })}
      data-part="item-icon"
      data-scope="tree-view"
    />
  );
}

function TreeViewItemTitle({ className, ...rest }: TreeViewItemTitleProps) {
  const item = useTreeViewItem();
  const slots = item?.slots ?? treeViewItemVariants();

  return <TreeViewPrimitive.ItemText {...rest} className={slots.title({ className })} />;
}

export function TreeViewNodeCheckbox({ className, ...rest }: TreeViewNodeCheckboxProps) {
  const item = useTreeViewItem();
  const slots = item?.slots ?? treeViewItemVariants();

  return (
    <TreeViewPrimitive.NodeCheckbox
      {...rest}
      className={cn(formControlToggleVariants(), slots.checkbox(), className)}
    >
      <TreeViewPrimitive.NodeCheckboxIndicator indeterminate={<MinusIcon />}>
        <CheckIcon />
      </TreeViewPrimitive.NodeCheckboxIndicator>
    </TreeViewPrimitive.NodeCheckbox>
  );
}

function TreeViewNodeInput({ className, ...rest }: TreeViewNodeInputProps) {
  const item = useTreeViewItem();
  const slots = item?.slots ?? treeViewItemVariants();

  return (
    <TreeViewPrimitive.NodeRenameInput {...rest} className={slots.renameInput({ className })} />
  );
}

type CreateFileIconsArgs = Record<`.${string}`, JSX.ElementType | null>;

export const createFileIcons = (args: CreateFileIconsArgs) => ({ ...args });

const getFileExtension = (file: string) => {
  const name = file.includes(".") ? file.split(".").at(-1)?.toLowerCase() : null;

  return name ? `.${name}` : null;
};
// #endregion

// #region Display Names
TreeViewRoot.displayName = "TreeView";
TreeViewLabel.displayName = "TreeView.Label";
TreeViewTree.displayName = "TreeView.Tree";
TreeViewNodeProvider.displayName = "TreeView.NodeProvider";
TreeViewBranch.displayName = "TreeView.Branch";
TreeViewBranchControl.displayName = "TreeView.BranchControl";
TreeViewBranchIndicator.displayName = "TreeView.BranchIndicator";
TreeViewBranchContent.displayName = "TreeView.BranchContent";
TreeViewItem.displayName = "TreeView.Item";
TreeViewItemText.displayName = "TreeView.ItemText";
TreeViewNodeCheckbox.displayName = "TreeView.NodeCheckbox";
// #endregion

// packages/solid/src/components/tree-view/tree-view.tsx
import { ark } from "@ark-ui/solid/factory";
import type {
  TreeCollection as arkTreeCollection,
  TreeViewBranchContentProps,
  TreeViewBranchIndentGuideProps,
  TreeViewBranchIndicatorProps,
  TreeViewBranchTextProps,
  TreeViewLabelProps,
  TreeViewNodeCheckboxProps,
  TreeViewNodeProviderProps,
  TreeViewNodeRenameInputProps,
  TreeViewBranchControlProps as TreeViewPrimitiveBranchControlProps,
  TreeViewBranchProps as TreeViewPrimitiveBranchProps,
  TreeViewItemProps as TreeViewPrimitiveItemProps,
  TreeViewItemTextProps as TreeViewPrimitiveItemTextProps,
  TreeViewRootComponentProps,
  TreeViewTreeProps,
} from "@ark-ui/solid/tree-view";
import {
  createTreeCollection as arkCreateTreeCollection,
  TreeView as TreeViewPrimitive,
} from "@ark-ui/solid/tree-view";
import { formControlToggleRecipe } from "@pisagor/recipes/form-control";
import {
  treeViewBranchRecipe,
  treeViewItemRecipe,
  treeViewRecipe,
} from "@pisagor/recipes/tree-view";
import { cn } from "@pisagor/utils";
import type { Component, ComponentProps, JSX } from "solid-js";
import { Show, splitProps } from "solid-js";
import {
  CaretRightIcon,
  CheckIcon,
  FileIcon,
  FolderIcon,
  FolderOpenIcon,
  MinusIcon,
} from "../../internal/icons";
import { useFormControlSurface } from "../surface/use-form-control-surface";
import {
  TreeViewBranchContext,
  TreeViewContext,
  type TreeViewContextProps,
  TreeViewItemContext,
  useTreeView,
  useTreeViewBranch,
  useTreeViewItem,
} from "./tree-view.context";

export interface TreeNodeType<T = unknown> {
  children?: TreeNodeType<T>[] | undefined;
  expandedIcon?: Component | null;
  icon?: Component | null;
  id: string;
  name: string;
}

export type TreeCollection = arkTreeCollection;

export interface TreeViewProps extends TreeViewRootComponentProps, TreeViewContextProps {
  recipe?: typeof treeViewRecipe;
}

export interface TreeViewBranchProps extends TreeViewPrimitiveBranchProps {
  branchRecipe?: typeof treeViewBranchRecipe;
}

export interface TreeViewItemProps extends TreeViewPrimitiveItemProps {
  itemRecipe?: typeof treeViewItemRecipe;
}

export type NodeProviderProps<T extends TreeNodeType = TreeNodeType> = TreeViewNodeProviderProps<T>;

export type TreeViewBranchControlProps = TreeViewPrimitiveBranchControlProps &
  Pick<TreeViewBranchTitleProps, "icon" | "expandedIcon">;

export interface TreeViewBranchTitleProps extends TreeViewBranchTextProps {
  expandedIcon?: Component | null;
  icon?: Component | null;
}

export type TreeViewItemTitleProps = TreeViewPrimitiveItemTextProps;

export interface TreeViewItemTextProps extends TreeViewItemTitleProps {
  icon?: Component;
}

export type TreeViewNodeInputProps = TreeViewNodeRenameInputProps;

type TreeViewItemIconProps = ComponentProps<typeof ark.span>;

export const createTreeCollection = <T extends TreeNodeType>(
  options: Parameters<typeof arkCreateTreeCollection<T>>[0],
) =>
  arkCreateTreeCollection<T>({
    nodeToString: (node) => node.name,
    nodeToValue: (node) => node.id,
    ...options,
  });

export function TreeViewRoot(props: TreeViewProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "fileIcons", "recipe", "class"]);
  const slots = () => (local.recipe ?? treeViewRecipe)();

  return (
    <TreeViewContext value={{ fileIcons: local.fileIcons, slots: slots() }}>
      <TreeViewPrimitive.Root {...rest} class={slots().base({ class: cn(local.class) })}>
        {local.children}
      </TreeViewPrimitive.Root>
    </TreeViewContext>
  );
}

export function TreeViewLabel(props: TreeViewLabelProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useTreeView();
  return <TreeViewPrimitive.Label {...rest} class={slots.label({ class: cn(local.class) })} />;
}

export function TreeViewTree(props: TreeViewTreeProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useTreeView();
  return <TreeViewPrimitive.Tree {...rest} class={slots.tree({ class: cn(local.class) })} />;
}

export function TreeViewNodeProvider<T extends TreeNodeType>(
  props: NodeProviderProps<T>,
): JSX.Element {
  return <TreeViewPrimitive.NodeProvider {...props} />;
}

export function TreeViewBranch(props: TreeViewBranchProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "branchRecipe", "class"]);
  const slots = () => (local.branchRecipe ?? treeViewBranchRecipe)();

  return (
    <TreeViewBranchContext value={{ slots: slots() }}>
      <TreeViewPrimitive.Branch {...rest} class={slots().base({ class: cn(local.class) })}>
        {local.children}
      </TreeViewPrimitive.Branch>
    </TreeViewBranchContext>
  );
}

export function TreeViewBranchControl(props: TreeViewBranchControlProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "expandedIcon", "icon", "class"]);
  const { slots } = useTreeView();

  return (
    <TreeViewPrimitive.BranchControl {...rest} class={slots.control({ class: cn(local.class) })}>
      <TreeViewBranchIndicator />
      <TreeViewBranchTitle expandedIcon={local.expandedIcon} icon={local.icon}>
        {local.children}
      </TreeViewBranchTitle>
    </TreeViewPrimitive.BranchControl>
  );
}

function TreeViewBranchTitle(props: TreeViewBranchTitleProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "expandedIcon", "icon", "class"]);
  const { slots } = useTreeViewBranch();
  const Icon = () => local.icon;
  const ExpandedIcon = () => local.expandedIcon;

  return (
    <TreeViewPrimitive.NodeContext>
      {(nodeState) => (
        <Show
          fallback={
            <TreeViewPrimitive.BranchText {...rest} class={slots.title({ class: cn(local.class) })}>
              <Show when={Icon() !== null && !nodeState().expanded}>
                <TreeViewItemIcon>
                  <Show fallback={<FolderIcon />} when={Icon()}>
                    {(Comp) => {
                      const C = Comp();
                      return C ? <C /> : null;
                    }}
                  </Show>
                </TreeViewItemIcon>
              </Show>
              <Show when={ExpandedIcon() !== null && nodeState().expanded}>
                <TreeViewItemIcon>
                  <Show fallback={<FolderOpenIcon />} when={ExpandedIcon()}>
                    {(Comp) => {
                      const C = Comp();
                      return C ? <C /> : null;
                    }}
                  </Show>
                </TreeViewItemIcon>
              </Show>
              {local.children}
            </TreeViewPrimitive.BranchText>
          }
          when={nodeState().renaming}
        >
          <TreeViewNodeInput />
        </Show>
      )}
    </TreeViewPrimitive.NodeContext>
  );
}

export function TreeViewBranchIndicator(props: TreeViewBranchIndicatorProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useTreeViewBranch();

  return (
    <TreeViewPrimitive.BranchIndicator
      {...rest}
      class={slots.indicator({ class: cn(local.class) })}
    >
      <CaretRightIcon />
    </TreeViewPrimitive.BranchIndicator>
  );
}

export function TreeViewBranchContent(props: TreeViewBranchContentProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useTreeViewBranch();

  return (
    <TreeViewPrimitive.BranchContent {...rest} class={slots.content({ class: cn(local.class) })}>
      <TreeViewBranchIndentGuide />
      {local.children}
    </TreeViewPrimitive.BranchContent>
  );
}

function TreeViewBranchIndentGuide(props: TreeViewBranchIndentGuideProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useTreeViewBranch();
  return (
    <TreeViewPrimitive.BranchIndentGuide
      {...rest}
      class={slots.indentGuide({ class: cn(local.class) })}
    />
  );
}

export function TreeViewItem(props: TreeViewItemProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "itemRecipe", "class"]);
  const { slots } = useTreeView();
  const itemSlots = () => (local.itemRecipe ?? treeViewItemRecipe)();

  return (
    <TreeViewItemContext value={{ slots: itemSlots() }}>
      <TreeViewPrimitive.Item {...rest} class={slots.control({ class: cn(local.class) })}>
        {local.children}
      </TreeViewPrimitive.Item>
    </TreeViewItemContext>
  );
}

export function TreeViewItemText(props: TreeViewItemTextProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "icon", "class"]);
  const { fileIcons } = useTreeView();
  const Icon = () => local.icon ?? FileIcon;

  const getFileIcon = (value: string): Component => {
    const extension = getFileExtension(value);
    const resolved = extension ? fileIcons?.[extension] : undefined;
    return resolved ?? Icon();
  };

  return (
    <TreeViewPrimitive.NodeContext>
      {(nodeState) => {
        const ResolvedIcon = getFileIcon(nodeState().value);
        return (
          <>
            <TreeViewItemIcon>
              <ResolvedIcon />
            </TreeViewItemIcon>
            <Show
              fallback={
                <TreeViewItemTitle {...rest} class={local.class}>
                  {local.children}
                </TreeViewItemTitle>
              }
              when={nodeState().renaming}
            >
              <TreeViewNodeInput />
            </Show>
          </>
        );
      }}
    </TreeViewPrimitive.NodeContext>
  );
}

function TreeViewItemIcon(props: TreeViewItemIconProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const item = useTreeViewItem();
  const slots = item?.slots ?? treeViewItemRecipe();

  return (
    <ark.span
      {...rest}
      class={slots.icon({ class: cn(local.class) })}
      data-part="item-icon"
      data-scope="tree-view"
    />
  );
}

function TreeViewItemTitle(props: TreeViewItemTitleProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const item = useTreeViewItem();
  const slots = item?.slots ?? treeViewItemRecipe();
  return <TreeViewPrimitive.ItemText {...rest} class={slots.title({ class: cn(local.class) })} />;
}

export function TreeViewNodeCheckbox(props: TreeViewNodeCheckboxProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const item = useTreeViewItem();
  const slots = item?.slots ?? treeViewItemRecipe();
  const surfaceVariant = useFormControlSurface();

  return (
    <TreeViewPrimitive.NodeCheckbox
      {...rest}
      class={cn(formControlToggleRecipe({ surfaceVariant }), slots.checkbox(), local.class)}
    >
      <TreeViewPrimitive.NodeCheckboxIndicator indeterminate={<MinusIcon />}>
        <CheckIcon />
      </TreeViewPrimitive.NodeCheckboxIndicator>
    </TreeViewPrimitive.NodeCheckbox>
  );
}

function TreeViewNodeInput(props: TreeViewNodeInputProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const item = useTreeViewItem();
  const slots = item?.slots ?? treeViewItemRecipe();
  return (
    <TreeViewPrimitive.NodeRenameInput
      {...rest}
      class={slots.renameInput({ class: cn(local.class) })}
    />
  );
}

type CreateFileIconsArgs = Record<`.${string}`, Component | null>;

export const createFileIcons = (args: CreateFileIconsArgs) => ({ ...args });

const getFileExtension = (file: string) => {
  const name = file.includes(".") ? file.split(".").at(-1)?.toLowerCase() : null;
  return name ? `.${name}` : null;
};
