// packages/solid/src/components/file-input/file-input.tsx
import { ark } from "@ark-ui/solid/factory";
import type { FileInputProps as BaseFileInputProps } from "@pisagor/props";
import {
  type FormControlGroupShellVariantProps,
  fileInputRecipe,
  formControlGroupShellRecipe,
} from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { createSignal, splitProps } from "solid-js";
import {
  InputGroupAddon,
  InputGroupButton,
  InputGroupText,
  type InputGroupTextProps,
} from "../input-group/input-group-core";
import { useFormControlSurface } from "../surface/use-form-control-surface";
import { FileInputContext, useFileInput } from "./file-input.context";

type FormControlVariant = "primary" | "secondary";
type FileInputVariantProps = FormControlGroupShellVariantProps;

type NativeFileInputProps = Omit<
  ComponentProps<"input">,
  "defaultValue" | "onChange" | "size" | "type" | "value"
>;

type FileInputRootProps = ComponentProps<typeof ark.div> &
  FileInputVariantProps &
  BaseFileInputProps & {
    disabled?: boolean;
  };

export interface FileInputProps
  extends NativeFileInputProps,
    FileInputVariantProps,
    BaseFileInputProps {
  invalid?: boolean;
  browseLabel?: string;
  placeholder?: string;
  onChange?: (
    event: Event & {
      currentTarget: HTMLInputElement;
      target: HTMLInputElement;
    },
  ) => void;
  onFilesChange?: (files: globalThis.File[]) => void;
  onValueChange?: (files: globalThis.File[]) => void;
}

interface FileInputControlProps extends ComponentProps<"input"> {}
interface FileInputLabelProps extends InputGroupTextProps {}

function getSelectedFiles(input: HTMLInputElement): globalThis.File[] {
  return input.files ? Array.from(input.files) : [];
}

function formatFileLabel(files: globalThis.File[]): string | undefined {
  if (files.length === 0) return undefined;
  if (files.length === 1) return files[0]?.name;
  return `${files.length} files selected`;
}

function FileInputRoot(props: FileInputRootProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "variant",
    "disabled",
    "children",
    "recipe",
    "class",
  ]);
  const surfaceVariant = useFormControlSurface();
  const size = () => local.size ?? "md";
  const variant = () => local.variant ?? ("primary" as FormControlVariant);
  const slots = () => (local.recipe ?? fileInputRecipe)();

  return (
    <FileInputContext value={{ slots: slots() }}>
      <ark.div
        {...rest}
        class={formControlGroupShellRecipe({
          class: cn(slots().root(), local.class),
          size: size(),
          surfaceVariant,
          variant: variant(),
        })}
        data-disabled={local.disabled ? true : undefined}
        data-part="root"
        data-scope="file-input"
        data-size={size()}
        data-variant={variant()}
        role="group"
      >
        {local.children}
      </ark.div>
    </FileInputContext>
  );
}

function FileInputControl(props: FileInputControlProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileInput();
  return (
    <input
      {...rest}
      class={slots.control({ class: local.class })}
      data-part="control"
      data-scope="file-input"
      type="file"
    />
  );
}

function FileInputLabel(props: FileInputLabelProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useFileInput();
  return (
    <InputGroupText {...rest} class={slots.label({ class: local.class })}>
      {local.children}
    </InputGroupText>
  );
}

export function FileInput(props: FileInputProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "variant",
    "accept",
    "disabled",
    "invalid",
    "multiple",
    "name",
    "required",
    "browseLabel",
    "capture",
    "id",
    "placeholder",
    "ref",
    "onChange",
    "onFilesChange",
    "onValueChange",
    "recipe",
    "class",
  ]);

  let inputEl: HTMLInputElement | undefined;
  const [fileLabel, setFileLabel] = createSignal<string>();

  const openPicker = () => inputEl?.click();

  const changeHandler = (
    event: Event & {
      currentTarget: HTMLInputElement;
      target: HTMLInputElement;
    },
  ) => {
    local.onChange?.(event);
    const files = getSelectedFiles(event.currentTarget);
    local.onFilesChange?.(files);
    local.onValueChange?.(files);
    setFileLabel(formatFileLabel(files));
  };

  return (
    <FileInputRoot
      class={local.class}
      disabled={local.disabled}
      recipe={local.recipe}
      size={local.size}
      variant={local.variant}
    >
      <FileInputControl
        {...rest}
        accept={local.accept}
        aria-invalid={local.invalid || undefined}
        capture={local.capture}
        data-invalid={local.invalid || undefined}
        disabled={local.disabled}
        id={local.id}
        multiple={local.multiple}
        name={local.name}
        onChange={changeHandler}
        ref={(el) => {
          inputEl = el;
          if (typeof local.ref === "function") local.ref(el);
        }}
        required={local.required}
      />
      <InputGroupAddon align="inline-start">
        <InputGroupButton
          disabled={local.disabled}
          onClick={openPicker}
          type="button"
        >
          {local.browseLabel ?? "Choose file"}
        </InputGroupButton>
      </InputGroupAddon>
      <FileInputLabel onClick={local.disabled ? undefined : openPicker}>
        {fileLabel() ?? local.placeholder ?? "No file chosen"}
      </FileInputLabel>
    </FileInputRoot>
  );
}

// packages/react/src/components/file-input/file-input.tsx
import { ark } from "@ark-ui/react/factory";
import type { FileInputProps as BaseFileInputProps } from "@pisagor/props";
import {
  type FormControlGroupShellVariantProps,
  fileInputRecipe,
  formControlGroupShellRecipe,
} from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import {
  type ChangeEventHandler,
  type ComponentProps,
  useRef,
  useState,
} from "react";
import {
  InputGroupAddon,
  InputGroupButton,
  InputGroupText,
  type InputGroupTextProps,
} from "../input-group/input-group-core";
import { useFormControlSurface } from "../surface/use-form-control-surface";
import { FileInputContext, useFileInput } from "./file-input.context";

// #region Types
type FormControlVariant = "primary" | "secondary";

type FileInputVariantProps = FormControlGroupShellVariantProps;

type NativeFileInputProps = Omit<
  ComponentProps<"input">,
  "defaultValue" | "onChange" | "size" | "type" | "value"
>;

type FileInputRootProps = ComponentProps<typeof ark.div> &
  FileInputVariantProps &
  BaseFileInputProps & {
    /** Disables the control and sets `data-disabled` on the root. */
    disabled?: boolean;
  };

export interface FileInputProps
  extends NativeFileInputProps,
    FileInputVariantProps,
    BaseFileInputProps {
  /** Marks the control invalid for styling and assistive tech. */
  invalid?: boolean;
  /** Label for the browse button. */
  browseLabel?: string;
  /** Text shown when no file is selected. */
  placeholder?: string;
  onChange?: ChangeEventHandler<HTMLInputElement>;
  /** Called with accepted files when the selection changes. */
  onFilesChange?: (files: File[]) => void;
  /** Alias for `onFilesChange`; matches `FileUpload` callback naming. */
  onValueChange?: (files: File[]) => void;
}

interface FileInputControlProps extends ComponentProps<"input"> {}

interface FileInputLabelProps extends InputGroupTextProps {}
// #endregion

// #region Helpers
function getSelectedFiles(input: HTMLInputElement): File[] {
  return input.files ? Array.from(input.files) : [];
}

function formatFileLabel(files: File[]): string | undefined {
  if (files.length === 0) {
    return undefined;
  }

  if (files.length === 1) {
    return files[0]?.name;
  }

  return `${files.length} files selected`;
}
// #endregion

// #region Parts
function FileInputRoot({
  size = "md",
  variant: variantProp,
  disabled,
  children,
  recipe = fileInputRecipe,
  className,
  ...rest
}: FileInputRootProps) {
  const resolved = {
    surfaceVariant: useFormControlSurface(),
    variant: variantProp ?? ("primary" as FormControlVariant),
  };
  const shellArgs = {
    surfaceVariant: resolved.surfaceVariant,
    variant: resolved.variant,
  };
  const controlProps = { "data-variant": resolved.variant };
  const slots = recipe();

  return (
    <FileInputContext value={{ slots }}>
      <ark.div
        {...rest}
        {...controlProps}
        className={formControlGroupShellRecipe({
          className: cn(slots.root(), className),
          size,
          ...shellArgs,
        })}
        data-disabled={disabled ? true : undefined}
        data-part="root"
        data-scope="file-input"
        data-size={size}
        role="group"
      >
        {children}
      </ark.div>
    </FileInputContext>
  );
}

function FileInputControl({ className, ...rest }: FileInputControlProps) {
  const { slots } = useFileInput();

  return (
    <input
      {...rest}
      className={slots.control({ className })}
      data-part="control"
      data-scope="file-input"
      type="file"
    />
  );
}

function FileInputLabel({ children, className, ...rest }: FileInputLabelProps) {
  const { slots } = useFileInput();

  return (
    <InputGroupText {...rest} className={slots.label({ className })}>
      {children}
    </InputGroupText>
  );
}
// #endregion

// #region Closed
export function FileInput({
  size = "md",
  variant,
  accept,
  disabled,
  invalid,
  multiple,
  name,
  required,
  browseLabel = "Choose file",
  capture,
  id,
  placeholder = "No file chosen",
  ref,
  onChange,
  onFilesChange,
  onValueChange,
  recipe,
  className,
  ...rest
}: FileInputProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [fileLabel, setFileLabel] = useState<string>();

  const setRefs = (node: HTMLInputElement | null) => {
    inputRef.current = node;

    if (typeof ref === "function") {
      ref(node);
      return;
    }

    if (ref) {
      ref.current = node;
    }
  };

  const openPicker = () => {
    inputRef.current?.click();
  };

  const changeHandler: ChangeEventHandler<HTMLInputElement> = (event) => {
    onChange?.(event);
    const files = getSelectedFiles(event.currentTarget);
    onFilesChange?.(files);
    onValueChange?.(files);
    setFileLabel(formatFileLabel(files));
  };

  return (
    <FileInputRoot
      className={className}
      disabled={disabled}
      recipe={recipe}
      size={size}
      variant={variant}
    >
      <FileInputControl
        {...rest}
        accept={accept}
        aria-invalid={invalid || undefined}
        capture={capture}
        data-invalid={invalid || undefined}
        disabled={disabled}
        id={id}
        multiple={multiple}
        name={name}
        onChange={changeHandler}
        ref={setRefs}
        required={required}
      />

      <InputGroupAddon align="inline-start">
        <InputGroupButton
          disabled={disabled}
          onClick={openPicker}
          type="button"
        >
          {browseLabel}
        </InputGroupButton>
      </InputGroupAddon>

      <FileInputLabel onClick={disabled ? undefined : openPicker}>
        {fileLabel ?? placeholder}
      </FileInputLabel>
    </FileInputRoot>
  );
}
// #endregion

// #region Display Names
FileInputRoot.displayName = "FileInput.Root";
FileInputControl.displayName = "FileInput.Control";
FileInputLabel.displayName = "FileInput.Label";
FileInput.displayName = "FileInput";
// #endregion
