// packages/solid/src/components/prose/prose.tsx
import { ark } from "@ark-ui/solid/factory";
import type { ProseProps as ProseSharedProps } from "@pisagor/props";
import { proseRecipe } from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { Show, splitProps } from "solid-js";

export interface ProseProps
  extends Omit<ComponentProps<typeof ark.div>, "innerHTML">,
    ProseSharedProps {
  html?: string;
}

export function Prose(props: ProseProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "class",
    "recipe",
    "html",
    "children",
  ]);
  const recipe = () => local.recipe ?? proseRecipe;

  return (
    <Show
      fallback={
        <ark.div
          {...rest}
          class={recipe()({ class: cn(local.class) })}
          data-part="root"
          data-scope="prose"
        >
          {local.children}
        </ark.div>
      }
      when={local.html}
    >
      {(html) => (
        <ark.div
          {...rest}
          class={recipe()({ class: cn(local.class) })}
          data-part="root"
          data-scope="prose"
          innerHTML={html()}
        />
      )}
    </Show>
  );
}

// packages/react/src/components/prose/prose.tsx
import { ark } from "@ark-ui/react/factory";
import type { ProseProps as ProseSharedProps } from "@pisagor/props";
import { proseRecipe } from "@pisagor/recipes";
import type { ComponentProps } from "react";

// #region Types
export interface ProseProps
  extends Omit<ComponentProps<typeof ark.div>, "dangerouslySetInnerHTML">,
    ProseSharedProps {
  /**
   * Trusted HTML content rendered via `dangerouslySetInnerHTML`.
   *
   * @remarks
   * When set, `children` is ignored. Only pass sanitized / trusted markup
   * (for example CMS content from your own database).
   */
  html?: string;
}
// #endregion

// #region Component
export function Prose({
  children,
  html,
  recipe = proseRecipe,
  className,
  ...rest
}: ProseProps) {
  return (
    <ark.div
      {...rest}
      {...(html ? { dangerouslySetInnerHTML: { __html: html } } : { children })}
      className={recipe({ className })}
      data-part="root"
      data-scope="prose"
    />
  );
}
// #endregion
