// packages/solid/src/components/navbar/navbar.tsx
import { ark } from "@ark-ui/solid/factory";
import type { NavbarProps as BaseNavbarRootProps } from "@pisagor/props";
import { navbarRecipe } from "@pisagor/recipes";
import type { ComponentProps, JSX } from "solid-js";
import { splitProps } from "solid-js";
import { NavbarContext, useNavbar } from "./navbar.context";

export interface NavbarRootProps
  extends ComponentProps<typeof ark.header>,
    BaseNavbarRootProps {}

export type NavbarPartProps = ComponentProps<typeof ark.div>;
export type NavbarNavProps = ComponentProps<typeof ark.nav>;

export function NavbarRoot(props: NavbarRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? navbarRecipe)();

  return (
    <NavbarContext value={{ slots: slots() }}>
      <ark.header
        {...rest}
        class={slots().base({ class: local.class })}
        data-part="root"
        data-scope="navbar"
      >
        {local.children}
      </ark.header>
    </NavbarContext>
  );
}

export function NavbarBrand(props: NavbarPartProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useNavbar();
  return (
    <ark.div
      {...rest}
      class={slots.brand({ class: local.class })}
      data-part="brand"
      data-scope="navbar"
    />
  );
}

export function NavbarContent(props: NavbarPartProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useNavbar();
  return (
    <ark.div
      {...rest}
      class={slots.content({ class: local.class })}
      data-part="content"
      data-scope="navbar"
    />
  );
}

export function NavbarNav(props: NavbarNavProps): JSX.Element {
  const [local, rest] = splitProps(props, ["aria-label", "class"]);
  const { slots } = useNavbar();
  return (
    <ark.nav
      {...rest}
      aria-label={local["aria-label"] ?? "Main"}
      class={slots.nav({ class: local.class })}
      data-part="nav"
      data-scope="navbar"
    />
  );
}

export function NavbarActions(props: NavbarPartProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useNavbar();
  return (
    <ark.div
      {...rest}
      class={slots.actions({ class: local.class })}
      data-part="actions"
      data-scope="navbar"
    />
  );
}

// packages/react/src/components/navbar/navbar.tsx
import { ark } from "@ark-ui/react/factory";
import type { NavbarProps as BaseNavbarRootProps } from "@pisagor/props";
import { navbarRecipe } from "@pisagor/recipes";
import type { ComponentProps } from "react";
import { NavbarContext, useNavbar } from "./navbar.context";

// #region Types
export interface NavbarRootProps
  extends ComponentProps<typeof ark.header>,
    BaseNavbarRootProps {}

export type NavbarPartProps = ComponentProps<typeof ark.div>;

export type NavbarNavProps = ComponentProps<typeof ark.nav>;
// #endregion

// #region Parts
export function NavbarRoot({
  children,
  recipe = navbarRecipe,
  className,
  ...rest
}: NavbarRootProps) {
  const slots = recipe();

  return (
    <NavbarContext value={{ slots }}>
      <ark.header
        {...rest}
        className={slots.base({ className })}
        data-part="root"
        data-scope="navbar"
      >
        {children}
      </ark.header>
    </NavbarContext>
  );
}

export function NavbarBrand({ className, ...rest }: NavbarPartProps) {
  const { slots } = useNavbar();

  return (
    <ark.div
      {...rest}
      className={slots.brand({ className })}
      data-part="brand"
      data-scope="navbar"
    />
  );
}

export function NavbarContent({ className, ...rest }: NavbarPartProps) {
  const { slots } = useNavbar();

  return (
    <ark.div
      {...rest}
      className={slots.content({ className })}
      data-part="content"
      data-scope="navbar"
    />
  );
}

export function NavbarNav({
  "aria-label": ariaLabel = "Main",
  className,
  ...rest
}: NavbarNavProps) {
  const { slots } = useNavbar();

  return (
    <ark.nav
      {...rest}
      aria-label={ariaLabel}
      className={slots.nav({ className })}
      data-part="nav"
      data-scope="navbar"
    />
  );
}

export function NavbarActions({ className, ...rest }: NavbarPartProps) {
  const { slots } = useNavbar();

  return (
    <ark.div
      {...rest}
      className={slots.actions({ className })}
      data-part="actions"
      data-scope="navbar"
    />
  );
}
// #endregion

// #region Display Names
NavbarRoot.displayName = "Navbar";
NavbarBrand.displayName = "Navbar.Brand";
NavbarContent.displayName = "Navbar.Content";
NavbarNav.displayName = "Navbar.Nav";
NavbarActions.displayName = "Navbar.Actions";
// #endregion
