// packages/solid/src/components/qr-code/qr-code.tsx
import type {
  QrCodeDownloadTriggerProps,
  QrCodeFrameProps,
  QrCodeOverlayProps,
  QrCodeRootProps as QrCodePrimitiveRootProps,
} from "@ark-ui/solid/qr-code";
import { QrCode as QrCodePrimitive } from "@ark-ui/solid/qr-code";
import type { QrCodeProps as QrCodeRootSharedProps } from "@pisagor/props";
import { qrCodeRecipe } from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { JSX } from "solid-js";
import { splitProps } from "solid-js";
import { QrCodeContext, useQrCode } from "./qr-code.context";

export interface QrCodeRootProps
  extends QrCodePrimitiveRootProps,
    QrCodeRootSharedProps {}

export type QrCodeDownloadProps = QrCodeDownloadTriggerProps;

export function QrCodeRoot(props: QrCodeRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? qrCodeRecipe)();

  return (
    <QrCodeContext value={{ slots: slots() }}>
      <QrCodePrimitive.Root
        {...rest}
        class={slots().base({ class: cn(local.class) })}
      >
        {local.children ?? <QrCodeFrame />}
      </QrCodePrimitive.Root>
    </QrCodeContext>
  );
}

export function QrCodeFrame(props: QrCodeFrameProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useQrCode();
  return (
    <QrCodePrimitive.Frame
      {...rest}
      class={slots.frame({ class: local.class })}
    >
      <QrCodePrimitive.Pattern class={slots.pattern()} />
    </QrCodePrimitive.Frame>
  );
}

export function QrCodeOverlay(props: QrCodeOverlayProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useQrCode();
  return (
    <QrCodePrimitive.Overlay
      {...rest}
      class={slots.overlay({ class: local.class })}
    />
  );
}

export function QrCodeDownload(props: QrCodeDownloadProps): JSX.Element {
  return <QrCodePrimitive.DownloadTrigger {...props} />;
}

// packages/react/src/components/qr-code/qr-code.tsx
import type {
  QrCodeDownloadTriggerProps,
  QrCodeFrameProps,
  QrCodeOverlayProps,
  QrCodeRootProps as QrCodePrimitiveRootProps,
} from "@ark-ui/react/qr-code";
import { QrCode as QrCodePrimitive } from "@ark-ui/react/qr-code";
import type { QrCodeProps as QrCodeRootSharedProps } from "@pisagor/props";
import { qrCodeRecipe } from "@pisagor/recipes";

import { QrCodeContext, useQrCode } from "./qr-code.context";

// #region Types
export interface QrCodeRootProps
  extends QrCodePrimitiveRootProps,
    QrCodeRootSharedProps {}

export type QrCodeDownloadProps = QrCodeDownloadTriggerProps;
// #endregion

// #region Parts
export function QrCodeRoot({
  children,
  recipe = qrCodeRecipe,
  className,
  ...rest
}: QrCodeRootProps) {
  const slots = recipe();

  return (
    <QrCodeContext value={{ slots }}>
      <QrCodePrimitive.Root {...rest} className={slots.base({ className })}>
        {children ?? <QrCodeFrame />}
      </QrCodePrimitive.Root>
    </QrCodeContext>
  );
}

export function QrCodeFrame({ className, ...rest }: QrCodeFrameProps) {
  const { slots } = useQrCode();

  return (
    <QrCodePrimitive.Frame {...rest} className={slots.frame({ className })}>
      <QrCodePrimitive.Pattern className={slots.pattern()} />
    </QrCodePrimitive.Frame>
  );
}

export function QrCodeOverlay({ className, ...rest }: QrCodeOverlayProps) {
  const { slots } = useQrCode();

  return (
    <QrCodePrimitive.Overlay
      {...rest}
      className={slots.overlay({ className })}
    />
  );
}

export function QrCodeDownload(props: QrCodeDownloadProps) {
  return <QrCodePrimitive.DownloadTrigger {...props} />;
}
// #endregion

// #region Display Names
QrCodeRoot.displayName = "QrCode";
QrCodeFrame.displayName = "QrCode.Frame";
QrCodeOverlay.displayName = "QrCode.Overlay";
QrCodeDownload.displayName = "QrCode.Download";
// #endregion
