// packages/react/src/components/listbox/listbox.tsx
import {
  type CollectionItem,
  createListCollection,
} from "@ark-ui/react/collection";
import type {
  ListboxContentProps,
  ListboxEmptyProps,
  ListboxItemGroupLabelProps,
  ListboxItemIndicatorProps,
  ListboxItemTextProps,
  ListboxItemGroupProps as ListboxPrimitiveItemGroupProps,
  ListboxItemProps as ListboxPrimitiveItemProps,
  ListboxRootProps as ListboxPrimitiveRootProps,
  ListboxValueTextProps,
} from "@ark-ui/react/listbox";
import { Listbox as ListboxPrimitive } from "@ark-ui/react/listbox";
import { CheckIcon } from "@phosphor-icons/react";
import type {
  ListboxItemProps as ListboxItemSharedProps,
  ListboxProps as ListboxRootSharedProps,
} from "@pisagor/props";
import { listboxItemRecipe, listboxRecipe } from "@pisagor/recipes";

import { useMemo } from "react";
import { DropdownMenu, type DropdownMenuShortcutProps } from "../dropdown-menu";
import {
  ListboxContext,
  ListboxItemContext,
  useListbox,
  useListboxItem,
} from "./listbox.context";

// #region Types
interface ListboxPresetItem extends CollectionItem {
  label: string;
  value: string;
  disabled?: boolean;
}

export type ListboxRootProps<T extends CollectionItem = CollectionItem> = Omit<
  ListboxPrimitiveRootProps<T>,
  "onValueChange"
> & {
  onValueChange?: (value: string | string[]) => void;
} & ListboxRootSharedProps;

export interface ListboxProps
  extends Omit<ListboxRootProps, "children" | "collection"> {
  collection?: ListboxRootProps["collection"];
  items?: ListboxPresetItem[];
}

export interface ListboxItemProps
  extends ListboxPrimitiveItemProps,
    ListboxItemSharedProps {}

export interface ListboxItemGroupProps extends ListboxPrimitiveItemGroupProps {
  /** The heading of the listbox item group. */
  heading?: string;
}

// #endregion

// #region Parts
export function ListboxRoot<T extends CollectionItem = CollectionItem>({
  recipe = listboxRecipe,
  className,
  children,
  onValueChange,
  ...rest
}: ListboxRootProps<T>) {
  const slots = recipe();

  return (
    <ListboxContext value={{ slots }}>
      <ListboxPrimitive.Root
        {...rest}
        className={slots.base({ className })}
        onValueChange={
          onValueChange ? (details) => onValueChange(details.value) : undefined
        }
      >
        {children}
      </ListboxPrimitive.Root>
    </ListboxContext>
  );
}

export function ListboxContent({ className, ...rest }: ListboxContentProps) {
  const { slots } = useListbox();

  return (
    <ListboxPrimitive.Content
      {...rest}
      className={slots.content({ className })}
    />
  );
}

export function ListboxItem({
  variant = "default",
  children,
  recipe = listboxItemRecipe,
  className,
  ...rest
}: ListboxItemProps) {
  const slots = useMemo(() => recipe({ variant }), [variant, recipe]);

  return (
    <ListboxItemContext value={{ slots }}>
      <ListboxPrimitive.Item
        {...rest}
        className={slots.base({ className })}
        data-variant={variant}
      >
        {children}
      </ListboxPrimitive.Item>
    </ListboxItemContext>
  );
}

export function ListboxItemText({ className, ...rest }: ListboxItemTextProps) {
  const { slots } = useListboxItem();

  return (
    <ListboxPrimitive.ItemText
      {...rest}
      className={slots.text({ className })}
    />
  );
}

export function ListboxItemGroup({
  children,
  heading,
  className,
  ...rest
}: ListboxItemGroupProps) {
  const { slots } = useListbox();

  return (
    <ListboxPrimitive.ItemGroup
      {...rest}
      className={slots.itemGroup({ className })}
    >
      {!!heading && <ListboxItemGroupLabel>{heading}</ListboxItemGroupLabel>}
      {children}
    </ListboxPrimitive.ItemGroup>
  );
}

export function ListboxItemGroupLabel({
  className,
  ...rest
}: ListboxItemGroupLabelProps) {
  const { slots } = useListbox();

  return (
    <ListboxPrimitive.ItemGroupLabel
      {...rest}
      className={slots.itemGroupLabel({ className })}
    />
  );
}

export function ListboxValueText({
  className,
  ...rest
}: ListboxValueTextProps) {
  const { slots } = useListbox();

  return (
    <ListboxPrimitive.ValueText
      {...rest}
      className={slots.valueText({ className })}
    />
  );
}

export function ListboxItemIndicator({
  children,
  className,
  ...rest
}: ListboxItemIndicatorProps) {
  const { slots } = useListboxItem();

  return (
    <ListboxPrimitive.ItemIndicator
      {...rest}
      className={slots.indicator({ className })}
    >
      {children ?? <CheckIcon />}
    </ListboxPrimitive.ItemIndicator>
  );
}

export function ListboxEmpty({ className, ...rest }: ListboxEmptyProps) {
  const { slots } = useListbox();

  return (
    <ListboxPrimitive.Empty {...rest} className={slots.empty({ className })} />
  );
}

export function ListboxShortcut(props: DropdownMenuShortcutProps) {
  return (
    <DropdownMenu.Shortcut
      {...props}
      data-part="shortcut"
      data-scope="listbox"
    />
  );
}
// #endregion

// #region Shorthand
export function ListboxShorthand({
  collection: collectionProp,
  items = [],
  ...rest
}: ListboxProps) {
  const collection =
    collectionProp ??
    createListCollection({
      items,
      itemToString: (item) => item.value,
      itemToValue: (item) => item.value,
    });

  return (
    <ListboxRoot {...rest} collection={collection}>
      {items.length > 0 && (
        <ListboxContent>
          {items.map((item) => (
            <ListboxItem item={item} key={item.value}>
              <ListboxItemText>{item.label}</ListboxItemText>
            </ListboxItem>
          ))}
        </ListboxContent>
      )}
    </ListboxRoot>
  );
}
// #endregion

// #region Display Names
ListboxRoot.displayName = "Listbox.Root";
ListboxContent.displayName = "Listbox.Content";
ListboxItem.displayName = "Listbox.Item";
ListboxItemText.displayName = "Listbox.ItemText";
ListboxItemGroup.displayName = "Listbox.ItemGroup";
ListboxItemGroupLabel.displayName = "Listbox.ItemGroupLabel";
ListboxValueText.displayName = "Listbox.ValueText";
ListboxItemIndicator.displayName = "Listbox.ItemIndicator";
ListboxEmpty.displayName = "Listbox.Empty";
ListboxShortcut.displayName = "Listbox.Shortcut";
ListboxShorthand.displayName = "Listbox";
// #endregion

// packages/solid/src/components/listbox/listbox.tsx
import {
  type CollectionItem,
  createListCollection,
} from "@ark-ui/solid/collection";
import type {
  ListboxContentProps,
  ListboxEmptyProps,
  ListboxItemGroupLabelProps,
  ListboxItemIndicatorProps,
  ListboxItemTextProps,
  ListboxItemGroupProps as ListboxPrimitiveItemGroupProps,
  ListboxItemProps as ListboxPrimitiveItemProps,
  ListboxRootProps as ListboxPrimitiveRootProps,
  ListboxValueTextProps,
} from "@ark-ui/solid/listbox";
import { Listbox as ListboxPrimitive } from "@ark-ui/solid/listbox";
import type {
  ListboxItemProps as ListboxItemSharedProps,
  ListboxProps as ListboxRootSharedProps,
} from "@pisagor/props";
import { listboxItemRecipe, listboxRecipe } from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { JSX } from "solid-js";
import { createMemo, For, Show, splitProps } from "solid-js";
import { CheckIcon } from "../../internal/icons";
import { DropdownMenu, type DropdownMenuShortcutProps } from "../dropdown-menu";
import {
  ListboxContext,
  ListboxItemContext,
  useListbox,
  useListboxItem,
} from "./listbox.context";

interface ListboxPresetItem extends CollectionItem {
  label: string;
  value: string;
  disabled?: boolean;
}

export type ListboxRootProps<T extends CollectionItem = CollectionItem> = Omit<
  ListboxPrimitiveRootProps<T>,
  "onValueChange"
> & {
  onValueChange?: (value: string | string[]) => void;
} & ListboxRootSharedProps;

export interface ListboxProps
  extends Omit<ListboxRootProps, "children" | "collection"> {
  collection?: ListboxRootProps["collection"];
  items?: ListboxPresetItem[];
}

export interface ListboxItemProps
  extends ListboxPrimitiveItemProps,
    ListboxItemSharedProps {}

export interface ListboxItemGroupProps extends ListboxPrimitiveItemGroupProps {
  heading?: string;
}

export function ListboxRoot<T extends CollectionItem = CollectionItem>(
  props: ListboxRootProps<T>,
): JSX.Element {
  const [local, rest] = splitProps(props as ListboxRootProps, [
    "recipe",
    "class",
    "children",
    "onValueChange",
  ]);
  const slots = () => (local.recipe ?? listboxRecipe)();

  return (
    <ListboxContext value={{ slots: slots() }}>
      <ListboxPrimitive.Root
        {...rest}
        class={slots().base({ class: cn(local.class) })}
        onValueChange={
          local.onValueChange
            ? (details) => local.onValueChange?.(details.value)
            : undefined
        }
      >
        {local.children}
      </ListboxPrimitive.Root>
    </ListboxContext>
  );
}

export function ListboxContent(props: ListboxContentProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useListbox();
  return (
    <ListboxPrimitive.Content
      {...rest}
      class={slots.content({ class: local.class })}
    />
  );
}

export function ListboxItem(props: ListboxItemProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "variant",
    "children",
    "recipe",
    "class",
  ]);
  const variant = () => local.variant ?? "default";
  const slots = createMemo(() =>
    (local.recipe ?? listboxItemRecipe)({ variant: variant() }),
  );

  return (
    <ListboxItemContext value={{ slots: slots() }}>
      <ListboxPrimitive.Item
        {...rest}
        class={slots().base({ class: local.class })}
        data-variant={variant()}
      >
        {local.children}
      </ListboxPrimitive.Item>
    </ListboxItemContext>
  );
}

export function ListboxItemText(props: ListboxItemTextProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useListboxItem();
  return (
    <ListboxPrimitive.ItemText
      {...rest}
      class={slots.text({ class: local.class })}
    />
  );
}

export function ListboxItemGroup(props: ListboxItemGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "heading", "class"]);
  const { slots } = useListbox();

  return (
    <ListboxPrimitive.ItemGroup
      {...rest}
      class={slots.itemGroup({ class: local.class })}
    >
      <Show when={!!local.heading}>
        <ListboxItemGroupLabel>{local.heading}</ListboxItemGroupLabel>
      </Show>
      {local.children}
    </ListboxPrimitive.ItemGroup>
  );
}

export function ListboxItemGroupLabel(
  props: ListboxItemGroupLabelProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useListbox();
  return (
    <ListboxPrimitive.ItemGroupLabel
      {...rest}
      class={slots.itemGroupLabel({ class: local.class })}
    />
  );
}

export function ListboxValueText(props: ListboxValueTextProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useListbox();
  return (
    <ListboxPrimitive.ValueText
      {...rest}
      class={slots.valueText({ class: local.class })}
    />
  );
}

export function ListboxItemIndicator(
  props: ListboxItemIndicatorProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useListboxItem();
  return (
    <ListboxPrimitive.ItemIndicator
      {...rest}
      class={slots.indicator({ class: local.class })}
    >
      {local.children ?? <CheckIcon />}
    </ListboxPrimitive.ItemIndicator>
  );
}

export function ListboxEmpty(props: ListboxEmptyProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useListbox();
  return (
    <ListboxPrimitive.Empty
      {...rest}
      class={slots.empty({ class: local.class })}
    />
  );
}

export function ListboxShortcut(props: DropdownMenuShortcutProps): JSX.Element {
  return (
    <DropdownMenu.Shortcut
      {...props}
      data-part="shortcut"
      data-scope="listbox"
    />
  );
}

export function ListboxShorthand(props: ListboxProps): JSX.Element {
  const [local, rest] = splitProps(props, ["collection", "items"]);
  const items = createMemo(() => local.items ?? []);
  const collection = createMemo(
    () =>
      local.collection ??
      createListCollection({
        items: items(),
        itemToString: (item) => item.value,
        itemToValue: (item) => item.value,
      }),
  );

  return (
    <ListboxRoot {...rest} collection={collection()}>
      <Show when={items().length > 0}>
        <ListboxContent>
          <For each={items()}>
            {(item) => (
              <ListboxItem item={item}>
                <ListboxItemText>{item.label}</ListboxItemText>
              </ListboxItem>
            )}
          </For>
        </ListboxContent>
      </Show>
    </ListboxRoot>
  );
}
