// packages/solid/examples/radio-group/compound.tsx
import { RadioGroup } from "@pisagor/solid";

export function Compound() {
  return (
    <RadioGroup.Root defaultValue="1">
      <RadioGroup.Item value="1">Default</RadioGroup.Item>
      <RadioGroup.Item value="2">Comfortable</RadioGroup.Item>
      <RadioGroup.Item value="3">Compact</RadioGroup.Item>
    </RadioGroup.Root>
  );
}

// packages/svelte/examples/radio-group/compound.svelte
<script lang="ts">
import { RadioGroup } from "@pisagor/svelte";
</script>

<RadioGroup.Root defaultValue="1">
      <RadioGroup.Item value="1">Default</RadioGroup.Item>
      <RadioGroup.Item value="2">Comfortable</RadioGroup.Item>
      <RadioGroup.Item value="3">Compact</RadioGroup.Item>
    </RadioGroup.Root>
