// packages/solid/src/components/radio-group/radio-group.tsx
import {
  type RadioGroupItemTextProps,
  type RadioGroupLabelProps,
  RadioGroup as RadioGroupPrimitive,
  type RadioGroupItemProps as RadioGroupPrimitiveItemProps,
  type RadioGroupRootProps as RadioGroupPrimitiveRootProps,
} from "@ark-ui/solid/radio-group";
import { formControlRadioToggleRecipe } from "@pisagor/recipes/form-control";
import {
  radioGroupItemRecipe,
  radioGroupRecipe,
} from "@pisagor/recipes/radio-group";
import { cn } from "@pisagor/utils";
import type { JSX } from "solid-js";
import { For, splitProps } from "solid-js";
import { Field } from "../field";
import { useFormControlSurface } from "../surface/use-form-control-surface";

type FormControlVariant = "primary" | "secondary";

interface RadioGroupPresetItem {
  disabled?: boolean;
  label: JSX.Element;
  value: string;
}

export interface RadioGroupRootProps
  extends Omit<RadioGroupPrimitiveRootProps, "onValueChange"> {
  onValueChange?: (value: string | null) => void;
  recipe?: typeof radioGroupRecipe;
}

export interface RadioGroupProps extends Omit<RadioGroupRootProps, "children"> {
  items?: RadioGroupPresetItem[];
}

export interface RadioGroupItemProps extends RadioGroupPrimitiveItemProps {
  variant?: FormControlVariant;
  recipe?: typeof radioGroupItemRecipe;
}

export function RadioGroupRoot(props: RadioGroupRootProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "children",
    "onValueChange",
    "recipe",
    "class",
  ]);

  return (
    <RadioGroupPrimitive.Root
      {...rest}
      class={(local.recipe ?? radioGroupRecipe)({ class: cn(local.class) })}
      onValueChange={
        local.onValueChange
          ? (details) => local.onValueChange?.(details.value)
          : undefined
      }
    >
      {local.children}
    </RadioGroupPrimitive.Root>
  );
}

export function RadioGroupItem(props: RadioGroupItemProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "variant",
    "tabIndex",
    "children",
    "recipe",
    "class",
  ]);
  const surfaceVariant = useFormControlSurface();
  const variant = () => local.variant ?? ("primary" as FormControlVariant);
  const slots = () => (local.recipe ?? radioGroupItemRecipe)();

  return (
    <RadioGroupPrimitive.Item
      {...rest}
      class={slots().base({ class: cn(local.class) })}
    >
      <RadioGroupPrimitive.ItemControl
        class={cn(
          formControlRadioToggleRecipe({
            surfaceVariant,
            variant: variant(),
          }),
          slots().control(),
        )}
        data-variant={variant()}
      />
      <RadioGroupItemText>{local.children}</RadioGroupItemText>
      <RadioGroupPrimitive.ItemHiddenInput tabIndex={local.tabIndex} />
    </RadioGroupPrimitive.Item>
  );
}

export function RadioGroupItemText(
  props: RadioGroupItemTextProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  return (
    <Field.Label
      asChild={(labelProps) => (
        <RadioGroupPrimitive.ItemText
          {...labelProps()}
          {...rest}
          class={cn(local.class)}
        >
          {local.children}
        </RadioGroupPrimitive.ItemText>
      )}
    />
  );
}

export function RadioGroupLabel(props: RadioGroupLabelProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <Field.Label
      asChild={(labelProps) => (
        <RadioGroupPrimitive.Label {...labelProps()} {...rest}>
          {local.children}
        </RadioGroupPrimitive.Label>
      )}
    />
  );
}

export function RadioGroupShorthand(props: RadioGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, ["items"]);

  return (
    <RadioGroupRoot {...rest}>
      <For each={local.items ?? []}>
        {(item) => (
          <RadioGroupItem disabled={item.disabled} value={item.value}>
            {item.label}
          </RadioGroupItem>
        )}
      </For>
    </RadioGroupRoot>
  );
}

// packages/react-ui/src/components/radio-group/radio-group.tsx
import { RadioGroup as RadioGroupPrimitive } from "@ark-ui/react/radio-group";
import { radioGroupItemVariants, radioGroupVariants } from "@pisagor/recipes/radio-group";
import { cn } from "@pisagor/utils";
import type { ComponentProps, ReactNode } from "react";
import type { FormControlVariant } from "../../internal/form-control/form-control-variants";
import {
  formControlRadioToggleVariants,
  formControlShellProps,
  shellVariantArgs,
} from "../../internal/form-control/form-control-variants";
import { useFormControlVariant } from "../../internal/form-control/use-form-control-variant";
import { Field } from "../field";

// #region Types
interface RadioGroupPresetItem {
  disabled?: boolean;
  label: ReactNode;
  value: string;
}

export interface RadioGroupRootProps
  extends Omit<ComponentProps<typeof RadioGroupPrimitive.Root>, "onValueChange"> {
  onValueChange?: (value: string | null) => void;
}

export interface RadioGroupProps extends Omit<RadioGroupRootProps, "children"> {
  items?: RadioGroupPresetItem[];
}

export interface RadioGroupItemProps extends ComponentProps<typeof RadioGroupPrimitive.Item> {
  /** Visual shell variant. When omitted, resolves from the nearest `Surface` context. */
  variant?: FormControlVariant;
}

export type RadioGroupItemTextProps = ComponentProps<typeof RadioGroupPrimitive.ItemText>;

export type RadioGroupLabelProps = ComponentProps<typeof RadioGroupPrimitive.Label>;
// #endregion

// #region Parts
export function RadioGroupRoot({
  className,
  children,
  onValueChange,
  ...rest
}: RadioGroupRootProps) {
  return (
    <RadioGroupPrimitive.Root
      {...rest}
      className={radioGroupVariants({ className })}
      onValueChange={onValueChange ? (details) => onValueChange(details.value) : undefined}
    >
      {children}
    </RadioGroupPrimitive.Root>
  );
}

export function RadioGroupItem({
  variant: variantProp,
  tabIndex,
  children,
  className,
  ...rest
}: RadioGroupItemProps) {
  const resolved = useFormControlVariant(variantProp);
  const shellArgs = shellVariantArgs(resolved);
  const controlProps = formControlShellProps(resolved);
  const slots = radioGroupItemVariants();

  return (
    <RadioGroupPrimitive.Item {...rest} className={slots.base({ className })}>
      <RadioGroupPrimitive.ItemControl
        {...controlProps}
        className={cn(formControlRadioToggleVariants({ ...shellArgs }), slots.control())}
      />

      <RadioGroupItemText>{children}</RadioGroupItemText>

      <RadioGroupPrimitive.ItemHiddenInput tabIndex={tabIndex} />
    </RadioGroupPrimitive.Item>
  );
}

export function RadioGroupItemText({ className, children, ...rest }: RadioGroupItemTextProps) {
  return (
    <Field.Label asChild>
      <RadioGroupPrimitive.ItemText {...rest} className={className}>
        {children}
      </RadioGroupPrimitive.ItemText>
    </Field.Label>
  );
}

export function RadioGroupLabel({ children, ...rest }: RadioGroupLabelProps) {
  return (
    <Field.Label asChild>
      <RadioGroupPrimitive.Label {...rest}>{children}</RadioGroupPrimitive.Label>
    </Field.Label>
  );
}
// #endregion

// #region Shorthand
export function RadioGroupShorthand({ items = [], ...rest }: RadioGroupProps) {
  return (
    <RadioGroupRoot {...rest}>
      {items.map((item) => (
        <RadioGroupItem disabled={item.disabled} key={item.value} value={item.value}>
          {item.label}
        </RadioGroupItem>
      ))}
    </RadioGroupRoot>
  );
}
// #endregion

// #region Display Names
RadioGroupRoot.displayName = "RadioGroup.Root";
RadioGroupItem.displayName = "RadioGroup.Item";
RadioGroupItemText.displayName = "RadioGroup.ItemText";
RadioGroupLabel.displayName = "RadioGroup.Label";
RadioGroupShorthand.displayName = "RadioGroup";
// #endregion
