// packages/solid/src/components/avatar/avatar-group.tsx
import { ark } from "@ark-ui/solid/factory";
import type { AvatarGroupProps as BaseAvatarGroupRootProps } from "@pisagor/props";
import { avatarGroupRecipe } from "@pisagor/recipes";
import type { ComponentProps, JSX } from "solid-js";
import { For, Show, splitProps } from "solid-js";
import { Avatar } from "./avatar";
import { AvatarGroupContext, useAvatarGroup } from "./avatar-group.context";

export interface AvatarGroupRootProps
  extends ComponentProps<typeof ark.div>,
    BaseAvatarGroupRootProps {}

export interface AvatarGroupProps
  extends Omit<AvatarGroupRootProps, "children"> {
  max?: number;
  users: Array<{ src?: string; fallback?: string; name?: string }>;
}

export type AvatarGroupCountProps = ComponentProps<typeof ark.div>;

export function AvatarGroupRoot(props: AvatarGroupRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? avatarGroupRecipe)();

  return (
    <AvatarGroupContext value={{ slots: slots() }}>
      <ark.div
        {...rest}
        class={slots().base({ class: local.class })}
        data-part="group"
        data-scope="avatar"
      >
        {local.children}
      </ark.div>
    </AvatarGroupContext>
  );
}

export function AvatarGroupCount(props: AvatarGroupCountProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useAvatarGroup();
  return (
    <ark.div
      {...rest}
      class={slots.count({ class: local.class })}
      data-part="group-count"
      data-scope="avatar"
    />
  );
}

export function AvatarGroupShorthand(props: AvatarGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, ["max", "users"]);
  const visibleUsers = () =>
    local.max !== undefined ? local.users.slice(0, local.max) : local.users;
  const remainingCount = () =>
    local.max !== undefined && local.users.length > local.max
      ? local.users.length - local.max
      : 0;

  return (
    <AvatarGroupRoot {...rest}>
      <For each={visibleUsers()}>
        {(user) => (
          <Avatar
            alt={user.name ?? ""}
            fallback={user.fallback}
            src={user.src}
          />
        )}
      </For>
      <Show when={remainingCount() > 0}>
        <AvatarGroupCount>+{remainingCount()}</AvatarGroupCount>
      </Show>
    </AvatarGroupRoot>
  );
}

// packages/react-ui/src/components/avatar/avatar-group.tsx
import { ark } from "@ark-ui/react/factory";
import { avatarGroupVariants } from "@pisagor/recipes/avatar";
import type { ComponentProps } from "react";
import { Avatar } from "./avatar";
import { AvatarGroupContext, useAvatarGroup } from "./avatar-group.context";

// #region Types
export type AvatarGroupRootProps = ComponentProps<typeof ark.div>;

export interface AvatarGroupProps extends Omit<AvatarGroupRootProps, "children"> {
  /** Maximum number of avatars to show; excess shown as "+N". */
  max?: number;
  /** User list rendered as avatars. */
  users: Array<{ src?: string; fallback?: string; name?: string }>;
}

export type AvatarGroupCountProps = ComponentProps<typeof ark.div>;
// #endregion

// #region Parts
export function AvatarGroupRoot({ children, className, ...rest }: AvatarGroupRootProps) {
  const slots = avatarGroupVariants();

  return (
    <AvatarGroupContext value={{ slots }}>
      <ark.div
        {...rest}
        className={slots.base({ className })}
        data-part="group"
        data-scope="avatar"
      >
        {children}
      </ark.div>
    </AvatarGroupContext>
  );
}

export function AvatarGroupCount({ className, ...rest }: AvatarGroupCountProps) {
  const { slots } = useAvatarGroup();

  return (
    <ark.div
      {...rest}
      className={slots.count({ className })}
      data-part="group-count"
      data-scope="avatar"
    />
  );
}
// #endregion

// #region Shorthand
export function AvatarGroupShorthand({ max, users, ...rest }: AvatarGroupProps) {
  const visibleUsers = max !== undefined ? users.slice(0, max) : users;
  const remainingCount = max !== undefined && users.length > max ? users.length - max : 0;

  return (
    <AvatarGroupRoot {...rest}>
      {visibleUsers.map((user) => (
        <Avatar
          alt={user.name ?? ""}
          fallback={user.fallback}
          key={user.src ?? user.fallback ?? user.name}
          src={user.src}
        />
      ))}
      {remainingCount > 0 ? <AvatarGroupCount>+{remainingCount}</AvatarGroupCount> : null}
    </AvatarGroupRoot>
  );
}
// #endregion

// #region Display Names
AvatarGroupRoot.displayName = "AvatarGroup.Root";
AvatarGroupCount.displayName = "AvatarGroup.Count";
AvatarGroupShorthand.displayName = "AvatarGroup";
// #endregion
