// packages/solid/src/components/circular-progress/circular-progress.tsx
import { ark } from "@ark-ui/solid/factory";
import {
  Progress as ProgressPrimitive,
  type ProgressRootProps,
  type ProgressValueTextProps,
  useProgressContext,
} from "@ark-ui/solid/progress";
import {
  type CircularProgressRecipeSlot,
  circularProgressRecipe,
} from "@pisagor/recipes/circular-progress";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { Show, splitProps } from "solid-js";
import type { VariantClassNames } from "../../internal/types";
import {
  CircularProgressSlotsContext,
  useCircularProgressSlots,
} from "./circular-progress.context";

type CircularProgressTrackProps = ComponentProps<typeof ark.svg>;
type CircularProgressValueProps = ProgressValueTextProps;
type CircularProgressClassNames = VariantClassNames<CircularProgressRecipeSlot>;

type CircularProgressRootProps = ProgressRootProps & {
  recipe?: typeof circularProgressRecipe;
};

export interface CircularProgressProps
  extends Omit<CircularProgressRootProps, "children"> {
  size?: number;
  thickness?: number;
  indeterminate?: boolean;
  isValueVisible?: boolean;
  children?: JSX.Element;
  classNames?: CircularProgressClassNames;
  trackProps?: Omit<
    CircularProgressTrackProps,
    "class" | "height" | "viewBox" | "width"
  >;
  valueProps?: Omit<CircularProgressValueProps, "children" | "class">;
}

interface CircularProgressTrackPartProps {
  size?: number;
  thickness?: number;
  class?: string;
  rangeClassName?: string;
  trackProps?: Omit<
    CircularProgressTrackProps,
    "class" | "height" | "viewBox" | "width"
  >;
}

function CircularProgressRoot(props: CircularProgressRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? circularProgressRecipe)();

  return (
    <CircularProgressSlotsContext value={{ slots: slots() }}>
      <ProgressPrimitive.Root
        {...rest}
        class={slots().base({ class: cn(local.class) })}
      >
        {local.children}
      </ProgressPrimitive.Root>
    </CircularProgressSlotsContext>
  );
}

function CircularProgressValueWrapper(props: {
  class?: string;
  children?: JSX.Element;
}): JSX.Element {
  const { slots } = useCircularProgressSlots();
  return (
    <span class={slots.valueWrapper({ class: cn(props.class) })}>
      {props.children}
    </span>
  );
}

function CircularProgressValue(props: CircularProgressValueProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useCircularProgressSlots();
  return (
    <ProgressPrimitive.ValueText
      {...rest}
      class={slots.value({ class: cn(local.class) })}
    />
  );
}

function CircularProgressTrack(
  props: CircularProgressTrackPartProps,
): JSX.Element {
  const { slots } = useCircularProgressSlots();
  const progress = useProgressContext();
  const size = () => props.size ?? 32;
  const thickness = () => props.thickness ?? 4;
  const radius = () => size() / 2 - thickness() / 2;
  const circumference = () => 2 * Math.PI * radius();
  const api = () => progress();
  const range = () => Math.max(api().max - api().min, 1);
  const normalizedValue = () => {
    const value = api().value;
    return value == null
      ? api().min
      : Math.min(Math.max(value, api().min), api().max);
  };
  const percent = () => (normalizedValue() - api().min) / range();
  const dashOffset = () => circumference() * (1 - percent());

  return (
    <ark.svg
      {...props.trackProps}
      aria-hidden="true"
      class={slots.track({ class: cn(props.class) })}
      data-part="circle"
      data-scope="circular-progress"
      height={size()}
      viewBox={`0 0 ${size()} ${size()}`}
      width={size()}
    >
      <circle
        cx={size() / 2}
        cy={size() / 2}
        data-part="track-bg"
        data-scope="circular-progress"
        r={radius()}
        stroke-width={thickness()}
      />
      <circle
        class={slots.range({ class: cn(props.rangeClassName) })}
        cx={size() / 2}
        cy={size() / 2}
        data-part="range"
        data-scope="circular-progress"
        r={radius()}
        stroke-dasharray={String(circumference())}
        stroke-dashoffset={String(
          api().value == null ? circumference() * 0.7 : dashOffset(),
        )}
        stroke-linecap="round"
        stroke-width={thickness()}
      />
    </ark.svg>
  );
}

export function CircularProgress(props: CircularProgressProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "indeterminate",
    "isValueVisible",
    "value",
    "children",
    "thickness",
    "trackProps",
    "valueProps",
    "class",
    "classNames",
  ]);

  return (
    <CircularProgressRoot
      {...rest}
      class={local.class}
      value={local.indeterminate ? null : local.value}
    >
      <Show when={local.isValueVisible}>
        <CircularProgressValueWrapper class={local.classNames?.valueWrapper}>
          <CircularProgressValue
            {...local.valueProps}
            class={local.classNames?.value}
          />
        </CircularProgressValueWrapper>
      </Show>
      {local.children}
      <CircularProgressTrack
        class={local.classNames?.track}
        rangeClassName={local.classNames?.range}
        size={local.size ?? 32}
        thickness={local.thickness ?? 4}
        trackProps={local.trackProps}
      />
    </CircularProgressRoot>
  );
}

// packages/react/src/components/circular-progress/circular-progress.tsx
import { ark } from "@ark-ui/react/factory";
import {
  Progress as ProgressPrimitive,
  type ProgressRootProps,
  type ProgressValueTextProps,
  useProgressContext,
} from "@ark-ui/react/progress";
import type { CircularProgressProps as CircularProgressRootSharedProps } from "@pisagor/props";
import {
  type CircularProgressRecipeSlot,
  circularProgressRecipe,
} from "@pisagor/recipes";
import type { ComponentProps, ReactNode } from "react";
import type { VariantClassNames } from "../../internal/types";
import {
  CircularProgressSlotsContext,
  useCircularProgressSlots,
} from "./circular-progress.context";

// #region Types
type CircularProgressTrackProps = ComponentProps<typeof ark.svg>;

type CircularProgressValueProps = ProgressValueTextProps;

type CircularProgressClassNames = VariantClassNames<CircularProgressRecipeSlot>;

type CircularProgressRootProps = ProgressRootProps &
  CircularProgressRootSharedProps;

export interface CircularProgressProps
  extends Omit<CircularProgressRootProps, "children"> {
  /**
   * Visual size preset for the progress circle.
   *
   * @defaultValue 32
   */
  size?: number;
  /**
   * Stroke thickness in pixels.
   *
   * @defaultValue 4
   */
  thickness?: number;
  /**
   * Whether to show indeterminate progress.
   *
   * @defaultValue false
   */
  indeterminate?: boolean;
  /** When true, renders the numeric value text centered inside the circle. */
  isValueVisible?: boolean;
  children?: ReactNode;
  /** Slot class names */
  classNames?: CircularProgressClassNames;
  /** Extra props forwarded to the circular progress track element */
  trackProps?: Omit<
    CircularProgressTrackProps,
    "className" | "height" | "viewBox" | "width"
  >;
  /** Extra props forwarded to the circular progress value element */
  valueProps?: Omit<CircularProgressValueProps, "children" | "className">;
}

interface CircularProgressTrackPartProps {
  size?: number;
  thickness?: number;
  className?: string;
  rangeClassName?: string;
  trackProps?: Omit<
    CircularProgressTrackProps,
    "className" | "height" | "viewBox" | "width"
  >;
}
// #endregion

// #region Parts
function CircularProgressRoot({
  children,
  recipe = circularProgressRecipe,
  className,
  ...rest
}: CircularProgressRootProps) {
  const slots = recipe();

  return (
    <CircularProgressSlotsContext value={{ slots }}>
      <ProgressPrimitive.Root {...rest} className={slots.base({ className })}>
        {children}
      </ProgressPrimitive.Root>
    </CircularProgressSlotsContext>
  );
}

function CircularProgressValueWrapper({
  children,
  className,
}: {
  className?: string;
  children?: ReactNode;
}) {
  const { slots } = useCircularProgressSlots();

  return <span className={slots.valueWrapper({ className })}>{children}</span>;
}

function CircularProgressValue({
  className,
  ...rest
}: CircularProgressValueProps) {
  const { slots } = useCircularProgressSlots();

  return (
    <ProgressPrimitive.ValueText
      {...rest}
      className={slots.value({ className })}
    />
  );
}

function CircularProgressTrack({
  size = 32,
  rangeClassName,
  thickness = 4,
  trackProps,
  className,
}: CircularProgressTrackPartProps) {
  const { slots } = useCircularProgressSlots();
  const { max, min, value } = useProgressContext();

  const radius = size / 2 - thickness / 2;
  const circumference = 2 * Math.PI * radius;
  const range = Math.max(max - min, 1);
  const normalizedValue =
    value == null ? min : Math.min(Math.max(value, min), max);
  const percent = (normalizedValue - min) / range;
  const dashOffset = circumference * (1 - percent);

  return (
    <ark.svg
      {...trackProps}
      aria-hidden="true"
      className={slots.track({ className })}
      data-part="circle"
      data-scope="circular-progress"
      height={size}
      viewBox={`0 0 ${size} ${size}`}
      width={size}
    >
      <circle
        cx={size / 2}
        cy={size / 2}
        data-part="track-bg"
        data-scope="circular-progress"
        r={radius}
        strokeWidth={thickness}
      />
      <circle
        className={slots.range({ className: rangeClassName })}
        cx={size / 2}
        cy={size / 2}
        data-part="range"
        data-scope="circular-progress"
        r={radius}
        strokeDasharray={circumference}
        strokeDashoffset={value == null ? circumference * 0.7 : dashOffset}
        strokeLinecap="round"
        strokeWidth={thickness}
      />
    </ark.svg>
  );
}
// #endregion

// #region Closed
export function CircularProgress({
  size = 32,
  indeterminate = false,
  isValueVisible,
  value,
  children,
  thickness = 4,
  trackProps,
  valueProps,
  className,
  classNames,
  ...rest
}: CircularProgressProps) {
  return (
    <CircularProgressRoot
      {...rest}
      className={className}
      value={indeterminate ? null : value}
    >
      {isValueVisible && (
        <CircularProgressValueWrapper className={classNames?.valueWrapper}>
          <CircularProgressValue
            {...valueProps}
            className={classNames?.value}
          />
        </CircularProgressValueWrapper>
      )}

      {children}

      <CircularProgressTrack
        className={classNames?.track}
        rangeClassName={classNames?.range}
        size={size}
        thickness={thickness}
        trackProps={trackProps}
      />
    </CircularProgressRoot>
  );
}
// #endregion

// #region Display Names
CircularProgressRoot.displayName = "CircularProgress.Root";
CircularProgressValueWrapper.displayName = "CircularProgress.ValueWrapper";
CircularProgressValue.displayName = "CircularProgress.Value";
CircularProgressTrack.displayName = "CircularProgress.Track";
CircularProgress.displayName = "CircularProgress";
// #endregion
