// packages/vue/src/components/field/examples/orientation-vertical.vue
<script lang="ts" setup>
import { Input } from "@pisagor/vue";
import { Field } from "..";
</script>

<template>
  <Field orientation="vertical">
    <Field.Label>Name</Field.Label>
    <Input placeholder="Enter your name" type="text" />
    <Field.Description
      >Stacks label, control, and description vertically.</Field.Description
    >
  </Field>
</template>

// packages/svelte/examples/field/orientation-vertical.svelte
<script lang="ts">
import { Field, Input } from "@pisagor/svelte";
</script>

<Field orientation="vertical">
      <Field.Label>Name</Field.Label>
      <Input placeholder="Enter your name" type="text" />
      <Field.Description>
        Stacks label, control, and description vertically.
      </Field.Description>
    </Field>
