// packages/react/examples/item/with-media.tsx
import { CaretRightIcon, SealCheckIcon } from "@phosphor-icons/react";
import { Item } from "@pisagor/react";

export function WithMedia() {
  return (
    <Item variant="outline">
      <Item.Media>
        <SealCheckIcon className="size-5" />
      </Item.Media>
      <Item.Content>
        <Item.Title>Your profile has been verified.</Item.Title>
      </Item.Content>
      <Item.Actions>
        <CaretRightIcon className="size-4" />
      </Item.Actions>
    </Item>
  );
}

// packages/svelte/examples/item/with-media.svelte
<script lang="ts">
import { Item } from "@pisagor/svelte/item";
import CaretRightIcon from "phosphor-svelte/lib/CaretRightIcon";
import SealCheckIcon from "phosphor-svelte/lib/SealCheckIcon";
</script>

<Item variant="outline">
      <Item.Media>
        <SealCheckIcon class="size-5" />
      </Item.Media>
      <Item.Content>
        <Item.Title>Your profile has been verified.</Item.Title>
      </Item.Content>
      <Item.Actions>
        <CaretRightIcon class="size-4" />
      </Item.Actions>
    </Item>
