// packages/react-ui/src/components/aspect-ratio/aspect-ratio.tsx
import { ark } from "@ark-ui/react/factory";
import { aspectRatioVariants } from "@pisagor/recipes/aspect-ratio";
import type { ComponentProps } from "react";

// #region Types
type AspectRatioRootProps = ComponentProps<typeof ark.div>;

export interface AspectRatioProps extends AspectRatioRootProps {}
// #endregion

// #region Part
export function AspectRatio({ className, ...rest }: AspectRatioProps) {
  return (
    <ark.div
      {...rest}
      className={aspectRatioVariants({ className })}
      data-part="root"
      data-scope="aspect-ratio"
    />
  );
}
// #endregion

// packages/solid/src/components/aspect-ratio/aspect-ratio.tsx
import { ark } from "@ark-ui/solid/factory";
import { aspectRatioRecipe } from "@pisagor/recipes/aspect-ratio";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { splitProps } from "solid-js";

export interface AspectRatioProps extends ComponentProps<typeof ark.div> {
  recipe?: typeof aspectRatioRecipe;
}

export function AspectRatio(props: AspectRatioProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class", "recipe"]);
  const recipeFn = () => local.recipe ?? aspectRatioRecipe;

  return (
    <ark.div
      {...rest}
      class={recipeFn()({ class: cn(local.class) })}
      data-part="root"
      data-scope="aspect-ratio"
    />
  );
}
