// packages/react/src/components/steps/examples/loading.tsx
import { CircleNotchIcon } from "@phosphor-icons/react";
import { Steps } from "..";

export function Loading() {
  const items = [
    { id: "step-1", loading: true },
    { id: "step-2", loading: false },
    { id: "step-3", loading: false },
  ];
  return (
    <Steps count={items.length}>
      <Steps.List>
        {items.map((item, index) => (
          <Steps.Item index={index} key={item.id}>
            <Steps.Trigger disabled>
              <Steps.Indicator>
                {item.loading ? (
                  <CircleNotchIcon className="animate-spin" />
                ) : (
                  index + 1
                )}
              </Steps.Indicator>
            </Steps.Trigger>
            <Steps.Separator />
          </Steps.Item>
        ))}
      </Steps.List>
    </Steps>
  );
}

// packages/vue/src/components/steps/examples/loading.vue
<script setup lang="ts">
import { PhCircleNotch } from "@phosphor-icons/vue";
import { Steps } from "..";

const items = [
  { id: "step-1", loading: true },
  { id: "step-2", loading: false },
  { id: "step-3", loading: false },
];
</script>

<template>
        <Steps :count="items.length">
          <Steps.List>
            <Steps.Item v-for="(item, index) in items" :key="item.id" :index="index">
              <Steps.Trigger disabled>
                <Steps.Indicator>
                  <PhCircleNotch v-if="item.loading" class="animate-spin" />
                  <template v-else>{{ index + 1 }}</template>
                </Steps.Indicator>
              </Steps.Trigger>
              <Steps.Separator />
            </Steps.Item>
          </Steps.List>
        </Steps>
  
</template>
