// packages/solid/examples/download-trigger/with-promise.tsx
import { Button, DownloadTrigger } from "@pisagor/solid";
import { DownloadIcon } from "@pisagor/solid/icons";

export function WithPromise() {
  return (
    <DownloadTrigger
      asChild={(props) => (
        <Button {...props()} size="lg" variant="outline">
          <DownloadIcon />
          Download
        </Button>
      )}
      data={() =>
        new Promise<Blob>((resolve) => {
          setTimeout(() => {
            resolve(
              new Blob(['{"message": "Loaded asynchronously"}'], {
                type: "application/json",
              }),
            );
          }, 500);
        })
      }
      fileName="data.json"
      mimeType="application/json"
    />
  );
}

// packages/svelte/examples/download-trigger/with-promise.svelte
<script lang="ts">
import { Button, DownloadTrigger } from "@pisagor/svelte";
import DownloadIcon from "phosphor-svelte/lib/DownloadIcon";

const data = () =>
  new Promise<Blob>((resolve) => {
    setTimeout(() => {
      resolve(
        new Blob(['{"message": "Loaded asynchronously"}'], {
          type: "application/json",
        }),
      );
    }, 500);
  });
</script>

<DownloadTrigger {data} fileName="data.json" mimeType="application/json">
  {#snippet asChild(
    props,
  )}
    <Button {...props()} size="lg" variant="outline">
      <DownloadIcon />
      Download
    </Button>
  {/snippet}
</DownloadTrigger>
