// packages/react/examples/download-trigger/with-promise.tsx
import { DownloadIcon } from "@phosphor-icons/react";
import { Button } from "@pisagor/react";
import { DownloadTrigger } from "@pisagor/react/download-trigger";
export function WithPromise() {
  return (
    <DownloadTrigger
      asChild
      data={() =>
        new Promise<Blob>((resolve) => {
          setTimeout(() => {
            resolve(
              new Blob(['{"message": "Loaded asynchronously"}'], {
                type: "application/json",
              }),
            );
          }, 500);
        })
      }
      fileName="data.json"
      mimeType="application/json"
    >
      {
        <Button size="lg" variant="outline">
          <DownloadIcon />
          Download
        </Button>
      }
    </DownloadTrigger>
  );
}

// packages/svelte/examples/download-trigger/with-promise.svelte
<script lang="ts">
import { Button } from "@pisagor/svelte";
import { DownloadTrigger } from "@pisagor/svelte/download-trigger";
import DownloadIcon from "phosphor-svelte/lib/DownloadIcon";

const data = () =>
  new Promise<Blob>((resolve) => {
    setTimeout(() => {
      resolve(
        new Blob(['{"message": "Loaded asynchronously"}'], {
          type: "application/json",
        }),
      );
    }, 500);
  });
</script>

<DownloadTrigger {data} fileName="data.json" mimeType="application/json">
  {#snippet asChild(props)}
    <Button {...props()} size="lg" variant="outline">
      <DownloadIcon />
      Download
    </Button>
  {/snippet}
</DownloadTrigger>
