// packages/svelte/examples/frame/separated-panels.svelte
<script lang="ts">
import { Frame } from "@pisagor/svelte";
</script>

<Frame>
      <Frame.Header>
        <Frame.Title>Section header</Frame.Title>
        <Frame.Description>
          Brief description about the section
        </Frame.Description>
      </Frame.Header>
      <Frame.Panel>
        <h2 class="font-semibold text-sm">Separated panel</h2>
        <p class="text-muted-foreground text-sm">Section description</p>
      </Frame.Panel>
      <Frame.Panel>
        <h2 class="font-semibold text-sm">Separated panel</h2>
        <p class="text-muted-foreground text-sm">Section description</p>
      </Frame.Panel>
    </Frame>

// packages/react/examples/frame/separated-panels.tsx
import { Frame } from "@pisagor/react";

export function SeparatedPanels() {
  return (
    <Frame>
      <Frame.Header>
        <Frame.Title>Section header</Frame.Title>
        <Frame.Description>
          Brief description about the section
        </Frame.Description>
      </Frame.Header>
      <Frame.Panel>
        <h2 className="font-semibold text-sm">Separated panel</h2>
        <p className="text-muted-foreground text-sm">Section description</p>
      </Frame.Panel>
      <Frame.Panel>
        <h2 className="font-semibold text-sm">Separated panel</h2>
        <p className="text-muted-foreground text-sm">Section description</p>
      </Frame.Panel>
    </Frame>
  );
}
