// packages/solid/examples/popover/modal.tsx
import { Button, Popover } from "@pisagor/solid";
export function Modal() {
  return (
    <Popover modal>
      <Popover.Trigger
        asChild={(props) => (
          <Button {...props()} variant="outline">
            Open
          </Button>
        )}
      />
      <Popover.Content>
        <Popover.Header
          description="You're all caught up. Check back later for new notifications."
          title="Notifications"
        />
      </Popover.Content>
    </Popover>
  );
}

// packages/svelte/examples/popover/modal.svelte
<script lang="ts">
import { Button, Popover } from "@pisagor/svelte";
</script>

<Popover modal>
  <Popover.Trigger>
    <Button variant="outline"> Open </Button>
  </Popover.Trigger>
  <Popover.Content>
    <Popover.Header
      description="You're all caught up. Check back later for new notifications."
      title="Notifications"
    />
  </Popover.Content>
</Popover>
