// packages/react/src/components/dropdown-menu/examples/with-scroll.tsx
import { Button } from "@pisagor/react";
import { DropdownMenu } from "..";
export function WithScroll() {
  const items = Array.from({ length: 15 }, (_, i) => `Item ${i + 1}`);
  return (
    <DropdownMenu>
      <DropdownMenu.Trigger asChild>
        <Button variant="outline">Open</Button>
      </DropdownMenu.Trigger>
      <DropdownMenu.Content className="max-h-60 min-w-40">
        {items.map((label, index) => (
          <DropdownMenu.Item key={label} value={`item-${index + 1}`}>
            {label}
          </DropdownMenu.Item>
        ))}
      </DropdownMenu.Content>
    </DropdownMenu>
  );
}

// packages/vue/examples/dropdown-menu/with-scroll.vue
<script lang="ts" setup>
import { Button, DropdownMenu } from "@pisagor/vue";

const items = Array.from({ length: 15 }, (_, i) => `Item ${i + 1}`);
</script>

<template>
  <DropdownMenu>
    <DropdownMenu.Trigger as-child>
      <Button variant="outline">Open</Button>
    </DropdownMenu.Trigger>
    <DropdownMenu.Content class="max-h-60 min-w-40">
      <DropdownMenu.Item
        v-for="(label, index) in items"
        :key="label"
        :value="`item-${index + 1}`"
      >
        {{ label }}
      </DropdownMenu.Item>
    </DropdownMenu.Content>
  </DropdownMenu>
</template>
