// packages/svelte/skills/svelte/assets/examples/data-list/orientation-vertical.svelte
<script lang="ts">
import { DataList } from "@pisagor/svelte/data-list";
</script>

<DataList.Root orientation="vertical">
      <DataList.Item value="Jane">First name</DataList.Item>
      <DataList.Item value="Doe">Last name</DataList.Item>
      <DataList.Item value="jane.doe@example.com">Email</DataList.Item>
    </DataList.Root>

// packages/react/examples/data-list/orientation-vertical.tsx
import { DataList } from "@pisagor/react/data-list";

export function OrientationVertical() {
  return (
    <DataList.Root orientation="vertical">
      <DataList.Item value="Jane">First name</DataList.Item>
      <DataList.Item value="Doe">Last name</DataList.Item>
      <DataList.Item value="jane.doe@example.com">Email</DataList.Item>
    </DataList.Root>
  );
}
