// packages/vue/examples/frame/separated-panels.vue
<script lang="ts" setup>
import { Frame } from "@pisagor/vue";
</script>

<template>
  <Frame>
    <Frame.Header>
      <Frame.Title>Section header</Frame.Title>
      <Frame.Description>Brief description about the section</Frame.Description>
    </Frame.Header>
    <Frame.Panel>
      <h2 class="font-semibold text-sm">Separated panel</h2>
      <p class="text-muted-foreground text-sm">Section description</p>
    </Frame.Panel>
    <Frame.Panel>
      <h2 class="font-semibold text-sm">Separated panel</h2>
      <p class="text-muted-foreground text-sm">Section description</p>
    </Frame.Panel>
  </Frame>
</template>

// packages/svelte/examples/frame/separated-panels.svelte
<script lang="ts">
import { Frame } from "@pisagor/svelte";
</script>

<Frame>
      <Frame.Header>
        <Frame.Title>Section header</Frame.Title>
        <Frame.Description>
          Brief description about the section
        </Frame.Description>
      </Frame.Header>
      <Frame.Panel>
        <h2 class="font-semibold text-sm">Separated panel</h2>
        <p class="text-muted-foreground text-sm">Section description</p>
      </Frame.Panel>
      <Frame.Panel>
        <h2 class="font-semibold text-sm">Separated panel</h2>
        <p class="text-muted-foreground text-sm">Section description</p>
      </Frame.Panel>
    </Frame>
