// packages/solid/src/components/app-shell/region.ts
import type { AppShellRecipe } from "@pisagor/recipes/app-shell";
import { createEffect, createMemo, createSignal, onCleanup } from "solid-js";
import type {
  AppShellFixedStackVar,
  AppShellPlacement,
  AppShellRailState,
  AppShellRegionPosition,
  AppShellRegionVar,
  AppShellResizableProps,
  AppShellSideState,
  MutableRef,
} from "./app-shell.context";
import { useAppShell, useSideState } from "./app-shell.context";

export function useRegionWidth(name: AppShellRegionVar, width: () => string) {
  const { setRegionVar } = useAppShell();

  createEffect(() => {
    const value = width();
    setRegionVar(name, value);
    onCleanup(() => setRegionVar(name, "0px"));
  });
}

export function regionVarFor(
  placement: AppShellPlacement,
  region: "inspector" | "panel" | "rail",
) {
  return `--app-shell-${placement}-${region}-width` as AppShellRegionVar;
}

export function gridAreaFor(
  placement: AppShellPlacement,
  region: "inspector" | "panel" | "rail",
) {
  return `${placement}-${region}` as const;
}

export function mergeResizableProps(
  defaults: Required<
    Pick<AppShellResizableProps, "enabled" | "handlePosition">
  >,
  override?: AppShellResizableProps,
): Required<Pick<AppShellResizableProps, "enabled" | "handlePosition">> {
  return {
    enabled: override?.enabled ?? defaults.enabled,
    handlePosition: override?.handlePosition ?? defaults.handlePosition,
  };
}

export function useShellRegionResizeCallbacks(regionVar: AppShellRegionVar) {
  const { setRegionResizing, setRegionVar } = useAppShell();

  return {
    onResizeChange: (nextWidth: number) => {
      setRegionVar(regionVar, `${nextWidth}px`);
    },
    onResizeEnd: () => setRegionResizing(false),
    onResizeStart: () => setRegionResizing(true),
  };
}

export function regionPositionClasses(
  slots: AppShellRecipe,
  position: AppShellRegionPosition = "fixed",
  orientation: "column" | "row" = "column",
  rowLayer?: "banner" | "header" | "navigation",
  columnLayer?: "inspector",
) {
  if (position === "relative") {
    return orientation === "column"
      ? slots.regionRelativeColumn()
      : slots.regionRelativeRow();
  }

  if (orientation === "column") {
    if (columnLayer === "inspector") {
      return slots.regionStickyInspector();
    }
    return slots.regionStickyColumn();
  }

  if (rowLayer === "banner") {
    return slots.regionStickyBanner();
  }

  if (rowLayer === "navigation") {
    return slots.regionStickyNavigation();
  }

  return slots.regionStickyHeader();
}

export function useSyncFixedRegionHeight(
  getEl: () => HTMLElement | undefined | null,
  position: () => AppShellRegionPosition,
  cssVar: AppShellFixedStackVar,
) {
  const { setFixedStackVar } = useAppShell();

  createEffect(() => {
    const element = getEl();
    const pos = position();

    if (pos !== "fixed" || !element) {
      setFixedStackVar(cssVar, "0px");
      return;
    }

    const syncHeight = () => {
      setFixedStackVar(cssVar, `${element.offsetHeight}px`);
    };

    syncHeight();
    const observer = new ResizeObserver(syncHeight);
    observer.observe(element);

    onCleanup(() => {
      observer.disconnect();
      setFixedStackVar(cssVar, "0px");
    });
  });
}

export function useAppShellSideOpen(
  placement: AppShellPlacement,
  statesRef: MutableRef<Partial<Record<AppShellPlacement, AppShellSideState>>>,
) {
  const { regionRevision } = useAppShell();
  return () => {
    regionRevision();
    return statesRef.current[placement]?.open() ?? false;
  };
}

export function useRegisteredSideState({
  placement,
  defaultOpen,
  getControlledOpen,
  statesRef,
  onOpenChange,
}: {
  getControlledOpen?: () => boolean | undefined;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  placement: AppShellPlacement;
  statesRef: MutableRef<Partial<Record<AppShellPlacement, AppShellSideState>>>;
}) {
  const { notifyRegionChange } = useAppShell();
  const side = useSideState({ defaultOpen, getControlledOpen, onOpenChange });

  const setOpen = (value: boolean | ((current: boolean) => boolean)) => {
    side.setOpen(value);
    notifyRegionChange();
  };

  const toggle = () => {
    side.toggle();
    notifyRegionChange();
  };

  const registeredSide: AppShellSideState = {
    open: side.open,
    setOpen,
    toggle,
  };

  statesRef.current[placement] = registeredSide;

  createEffect(() => {
    notifyRegionChange();
    onCleanup(() => {
      delete statesRef.current[placement];
    });
  });

  return registeredSide;
}

export function useRegisteredRailState({
  placement,
  defaultActiveRailId,
  getActiveRailId,
  statesRef,
  onActiveRailIdChange,
}: {
  getActiveRailId?: () => string | undefined;
  defaultActiveRailId?: string;
  onActiveRailIdChange?: (id: string) => void;
  placement: AppShellPlacement;
  statesRef: MutableRef<Partial<Record<AppShellPlacement, AppShellRailState>>>;
}) {
  const [uncontrolled, setUncontrolled] = createSignal(defaultActiveRailId);
  const activeRailId = createMemo(() => {
    const controlled = getActiveRailId?.();
    return controlled !== undefined ? controlled : uncontrolled();
  });

  const setActiveRailId = (id: string) => {
    if (getActiveRailId?.() === undefined) setUncontrolled(id);
    onActiveRailIdChange?.(id);
  };

  const railState: AppShellRailState = {
    activeRailId,
    placement,
    setActiveRailId,
  };

  statesRef.current[placement] = railState;

  createEffect(() => {
    onCleanup(() => {
      delete statesRef.current[placement];
    });
  });

  return railState;
}

// packages/react-ui/src/components/app-shell/region.ts
import { useUncontrolled } from "@mantine/hooks";
import type { AppShellVariants } from "@pisagor/recipes/app-shell";
import { type RefObject, useCallback, useLayoutEffect, useMemo } from "react";
import type {
  AppShellFixedStackVar,
  AppShellPlacement,
  AppShellRegionPosition,
  AppShellRegionVar,
  AppShellResizableProps,
  AppShellSideState,
} from "./app-shell.context";
import { type AppShellRailState, useAppShell, useSideState } from "./app-shell.context";

export function useRegionWidth(name: AppShellRegionVar, width: string) {
  const { setRegionVar } = useAppShell();

  useLayoutEffect(() => {
    setRegionVar(name, width);
    return () => {
      setRegionVar(name, "0px");
    };
  }, [name, setRegionVar, width]);
}

export function regionVarFor(placement: AppShellPlacement, region: "inspector" | "panel" | "rail") {
  return `--app-shell-${placement}-${region}-width` as AppShellRegionVar;
}

export function gridAreaFor(placement: AppShellPlacement, region: "inspector" | "panel" | "rail") {
  return `${placement}-${region}` as const;
}

export function mergeResizableProps(
  defaults: Required<Pick<AppShellResizableProps, "enabled" | "handlePosition">>,
  override?: AppShellResizableProps,
): Required<Pick<AppShellResizableProps, "enabled" | "handlePosition">> {
  return {
    enabled: override?.enabled ?? defaults.enabled,
    handlePosition: override?.handlePosition ?? defaults.handlePosition,
  };
}

export function useShellRegionResizeCallbacks(regionVar: AppShellRegionVar) {
  const { setRegionResizing, setRegionVar } = useAppShell();

  return useMemo(
    () => ({
      onResizeChange: (nextWidth: number) => {
        setRegionVar(regionVar, `${nextWidth}px`);
      },
      onResizeEnd: () => setRegionResizing(false),
      onResizeStart: () => setRegionResizing(true),
    }),
    [regionVar, setRegionResizing, setRegionVar],
  );
}

export function regionPositionClasses(
  slots: AppShellVariants,
  position: AppShellRegionPosition = "fixed",
  orientation: "column" | "row" = "column",
  rowLayer?: "banner" | "header" | "navigation",
  columnLayer?: "inspector",
) {
  if (position === "relative") {
    return orientation === "column" ? slots.regionRelativeColumn() : slots.regionRelativeRow();
  }

  if (orientation === "column") {
    if (columnLayer === "inspector") {
      return slots.regionStickyInspector();
    }

    return slots.regionStickyColumn();
  }

  if (rowLayer === "banner") {
    return slots.regionStickyBanner();
  }

  if (rowLayer === "navigation") {
    return slots.regionStickyNavigation();
  }

  return slots.regionStickyHeader();
}

export function useSyncFixedRegionHeight(
  ref: RefObject<HTMLElement | null>,
  position: AppShellRegionPosition,
  cssVar: AppShellFixedStackVar,
) {
  const { setFixedStackVar } = useAppShell();

  useLayoutEffect(() => {
    const element = ref.current;

    if (position !== "fixed" || !element) {
      setFixedStackVar(cssVar, "0px");
      return;
    }

    const syncHeight = () => {
      setFixedStackVar(cssVar, `${element.offsetHeight}px`);
    };

    syncHeight();
    const observer = new ResizeObserver(syncHeight);
    observer.observe(element);

    return () => {
      observer.disconnect();
      setFixedStackVar(cssVar, "0px");
    };
  }, [cssVar, position, ref, setFixedStackVar]);
}

export function useAppShellSideOpen(
  placement: AppShellPlacement,
  statesRef: RefObject<Partial<Record<AppShellPlacement, AppShellSideState>>>,
) {
  const { regionRevision } = useAppShell();
  void regionRevision;

  return statesRef.current[placement]?.open ?? false;
}

export function useRegisteredSideState({
  placement,
  defaultOpen,
  controlledOpen,
  statesRef,
  onOpenChange,
}: {
  controlledOpen?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  placement: AppShellPlacement;
  statesRef: RefObject<Partial<Record<AppShellPlacement, AppShellSideState>>>;
}) {
  const { notifyRegionChange } = useAppShell();
  const side = useSideState({ controlledOpen, defaultOpen, onOpenChange });

  const setOpen = useCallback(
    (value: boolean | ((current: boolean) => boolean)) => {
      side.setOpen(value);
      notifyRegionChange();
    },
    [notifyRegionChange, side.setOpen],
  );

  const toggle = useCallback(() => {
    side.toggle();
    notifyRegionChange();
  }, [notifyRegionChange, side.toggle]);

  const registeredSide = useMemo(
    () => ({
      open: side.open,
      setOpen,
      toggle,
    }),
    [setOpen, side.open, toggle],
  );

  statesRef.current[placement] = registeredSide;

  useLayoutEffect(() => {
    notifyRegionChange();
  }, [notifyRegionChange]);

  useLayoutEffect(() => {
    return () => {
      delete statesRef.current[placement];
    };
  }, [placement, statesRef]);

  return registeredSide;
}

export function useRegisteredRailState({
  placement,
  defaultActiveRailId,
  activeRailId: activeRailIdProp,
  statesRef,
  onActiveRailIdChange,
}: {
  activeRailId?: string;
  defaultActiveRailId?: string;
  onActiveRailIdChange?: (id: string) => void;
  placement: AppShellPlacement;
  statesRef: RefObject<Partial<Record<AppShellPlacement, AppShellRailState>>>;
}) {
  const [activeRailId, setActiveRailId] = useUncontrolled({
    defaultValue: defaultActiveRailId,
    onChange: onActiveRailIdChange,
    value: activeRailIdProp,
  });

  const railState = useMemo(
    () => ({ activeRailId, placement, setActiveRailId }),
    [activeRailId, placement, setActiveRailId],
  );

  statesRef.current[placement] = railState;

  useLayoutEffect(() => {
    return () => {
      delete statesRef.current[placement];
    };
  }, [placement, statesRef]);

  return railState;
}
