// packages/solid/src/components/file-upload/file-upload.tsx
import { ark } from "@ark-ui/solid/factory";
import type {
  FileUploadClearTriggerProps,
  FileUploadItemGroupProps,
  FileUploadItemNameProps,
  FileUploadItemPreviewProps,
  FileUploadItemProps,
  FileUploadItemSizeTextProps,
  FileUploadDropzoneProps as FileUploadPrimitiveDropzoneProps,
  FileUploadRootProps as FileUploadPrimitiveRootProps,
  FileUploadTriggerProps,
} from "@ark-ui/solid/file-upload";
import {
  FileUpload as FileUploadPrimitive,
  useFileUploadContext,
} from "@ark-ui/solid/file-upload";
import {
  fileUploadItemRecipe,
  fileUploadRecipe,
} from "@pisagor/recipes/file-upload";
import { formControlZoneRecipe } from "@pisagor/recipes/form-control";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { For, Show, splitProps } from "solid-js";
import { UploadIcon, XIcon } from "../../internal/icons";
import { Button } from "../button";
import { useFormControlSurface } from "../surface/use-form-control-surface";
import {
  FileUploadContext,
  FileUploadItemContext,
  useFileUpload,
  useFileUploadItem,
} from "./file-upload.context";

type FormControlVariant = "primary" | "secondary";

export interface FileUploadItemRootProps extends FileUploadItemProps {
  itemRecipe?: typeof fileUploadItemRecipe;
}

export type FileUploadListProps = Omit<FileUploadItemRootProps, "file">;

export interface FileUploadRootProps extends FileUploadPrimitiveRootProps {
  onValueChange?: (value: File[]) => void;
  recipe?: typeof fileUploadRecipe;
}

export interface FileUploadDropzoneProps
  extends FileUploadPrimitiveDropzoneProps {
  variant?: FormControlVariant;
}

export type FileUploadItemPreviewImageProps = ComponentProps<
  typeof FileUploadPrimitive.ItemPreviewImage
>;
export type FileUploadItemSizeProps = FileUploadItemSizeTextProps;
export type FileUploadItemDeleteTriggerProps = ComponentProps<
  typeof FileUploadPrimitive.ItemDeleteTrigger
>;
export type FileUploadDropzoneIconProps = ComponentProps<typeof ark.div>;
export type FileUploadTitleProps = ComponentProps<typeof ark.div>;
export type FileUploadDescriptionProps = ComponentProps<typeof ark.div>;
export type FileUploadHelperProps = ComponentProps<typeof ark.div>;

export function FileUploadRoot(props: FileUploadRootProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "children",
    "onFileChange",
    "onValueChange",
    "recipe",
    "class",
  ]);
  const slots = () => (local.recipe ?? fileUploadRecipe)();

  return (
    <FileUploadContext value={{ slots: slots() }}>
      <FileUploadPrimitive.Root
        {...rest}
        class={slots().base({ class: cn(local.class) })}
        onFileChange={(details) => {
          local.onFileChange?.(details);
          local.onValueChange?.(details.acceptedFiles);
        }}
      >
        {local.children}
        <FileUploadPrimitive.HiddenInput />
      </FileUploadPrimitive.Root>
    </FileUploadContext>
  );
}

export function FileUploadTrigger(props: FileUploadTriggerProps): JSX.Element {
  return <FileUploadPrimitive.Trigger {...props} />;
}

export function FileUploadDropzone(
  props: FileUploadDropzoneProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["variant", "class"]);
  const surfaceVariant = useFormControlSurface();
  const variant = () => local.variant ?? ("primary" as FormControlVariant);
  const { slots } = useFileUpload();

  return (
    <FileUploadPrimitive.Dropzone
      {...rest}
      class={cn(
        formControlZoneRecipe({ surfaceVariant, variant: variant() }),
        slots.dropzone(),
        local.class,
      )}
      data-variant={variant()}
    />
  );
}

export function FileUploadDropzoneIcon(
  props: FileUploadDropzoneIconProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useFileUpload();

  return (
    <ark.div
      {...rest}
      class={slots.dropzoneIcon({ class: cn(local.class) })}
      data-part="dropzone-icon"
      data-scope="file-upload"
    >
      {local.children ?? <UploadIcon />}
    </ark.div>
  );
}

export function FileUploadTitle(props: FileUploadTitleProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileUpload();
  return (
    <ark.div
      {...rest}
      class={slots.title({ class: cn(local.class) })}
      data-part="title"
      data-scope="file-upload"
    />
  );
}

export function FileUploadDescription(
  props: FileUploadDescriptionProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileUpload();
  return (
    <ark.div
      {...rest}
      class={slots.description({ class: cn(local.class) })}
      data-part="title"
      data-scope="file-upload"
    />
  );
}

export function FileUploadHelper(props: FileUploadHelperProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileUpload();
  return (
    <ark.div
      {...rest}
      class={slots.helper({ class: cn(local.class) })}
      data-part="dropzone-helper"
      data-scope="file-upload"
    />
  );
}

export function FileUploadItemGroup(
  props: FileUploadItemGroupProps,
): JSX.Element {
  return <FileUploadPrimitive.ItemGroup {...props} />;
}

export function FileUploadList(props: FileUploadListProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class", "itemRecipe"]);
  const fileUpload = useFileUploadContext();
  const { slots } = useFileUpload();
  const itemRecipe = () => local.itemRecipe ?? fileUploadItemRecipe;
  const itemSlots = () => itemRecipe()();
  const files = () => fileUpload().acceptedFiles;

  return (
    <Show when={files().length > 0}>
      <FileUploadItemGroup class={slots.itemGroup()}>
        <For each={files()}>
          {(file) => {
            const isImage = () => file.type.startsWith("image/");
            const extension = () => file.name.split(".").pop();
            return (
              <FileUploadItem
                {...rest}
                class={itemSlots().listItem({ class: cn(local.class) })}
                file={file}
                itemRecipe={itemRecipe()}
              >
                <FileUploadItemPreview
                  class={itemSlots().listPreview()}
                  type={isImage() ? "image/*" : ".*"}
                >
                  <Show
                    fallback={
                      <span class={itemSlots().extension()}>{extension()}</span>
                    }
                    when={isImage()}
                  >
                    <FileUploadItemPreviewImage />
                  </Show>
                </FileUploadItemPreview>
                <div class={itemSlots().content()}>
                  <FileUploadItemName />
                  <FileUploadItemSize />
                </div>
                <FileUploadItemDeleteTrigger
                  asChild={(triggerProps) => (
                    <Button
                      {...triggerProps({ class: itemSlots().deleteButton() })}
                      aria-label="Remove file"
                      size="icon-xs"
                      variant="ghost"
                    >
                      <XIcon aria-hidden />
                    </Button>
                  )}
                />
              </FileUploadItem>
            );
          }}
        </For>
      </FileUploadItemGroup>
    </Show>
  );
}

export function FileUploadItem(props: FileUploadItemRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "itemRecipe", "class"]);
  const slots = () => (local.itemRecipe ?? fileUploadItemRecipe)();

  return (
    <FileUploadItemContext value={{ slots: slots() }}>
      <FileUploadPrimitive.Item
        {...rest}
        class={slots().base({ class: cn(local.class) })}
      >
        {local.children}
      </FileUploadPrimitive.Item>
    </FileUploadItemContext>
  );
}

export function FileUploadItemPreview(
  props: FileUploadItemPreviewProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileUploadItem();
  return (
    <FileUploadPrimitive.ItemPreview
      {...rest}
      class={slots.preview({ class: cn(local.class) })}
    />
  );
}

export function FileUploadItemPreviewImage(
  props: FileUploadItemPreviewImageProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileUploadItem();
  return (
    <FileUploadPrimitive.ItemPreviewImage
      {...rest}
      class={slots.previewImage({ class: cn(local.class) })}
    />
  );
}

export function FileUploadItemName(
  props: FileUploadItemNameProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileUploadItem();
  return (
    <FileUploadPrimitive.ItemName
      {...rest}
      class={slots.name({ class: cn(local.class) })}
    />
  );
}

export function FileUploadItemSize(
  props: FileUploadItemSizeProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileUploadItem();
  return (
    <FileUploadPrimitive.ItemSizeText
      {...rest}
      class={slots.size({ class: cn(local.class) })}
    />
  );
}

export function FileUploadItemDeleteTrigger(
  props: FileUploadItemDeleteTriggerProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useFileUploadItem();
  return (
    <FileUploadPrimitive.ItemDeleteTrigger
      {...rest}
      class={slots.deleteTrigger({ class: cn(local.class) })}
    />
  );
}

export function FileUploadClearTrigger(
  props: FileUploadClearTriggerProps,
): JSX.Element {
  return <FileUploadPrimitive.ClearTrigger {...props} />;
}

// packages/react/src/components/file-upload/file-upload.tsx
import { ark } from "@ark-ui/react/factory";
import type {
  FileUploadClearTriggerProps,
  FileUploadItemGroupProps,
  FileUploadItemNameProps,
  FileUploadItemPreviewProps,
  FileUploadItemProps,
  FileUploadItemSizeTextProps,
  FileUploadDropzoneProps as FileUploadPrimitiveDropzoneProps,
  FileUploadRootProps as FileUploadPrimitiveRootProps,
  FileUploadTriggerProps,
} from "@ark-ui/react/file-upload";
import {
  FileUpload as FileUploadPrimitive,
  useFileUploadContext,
} from "@ark-ui/react/file-upload";
import { UploadIcon, XIcon } from "@phosphor-icons/react";
import {
  fileUploadItemRecipe,
  fileUploadRecipe,
} from "@pisagor/recipes/file-upload";
import { formControlZoneRecipe } from "@pisagor/recipes/form-control";
import { cn } from "@pisagor/utils";
import type { ComponentProps } from "react";
import { Button } from "../button";
import { useFormControlSurface } from "../surface/use-form-control-surface";
import {
  FileUploadContext,
  FileUploadItemContext,
  useFileUpload,
  useFileUploadItem,
} from "./file-upload.context";

// #region Types
type FormControlVariant = "primary" | "secondary";

export interface FileUploadItemRootProps extends FileUploadItemProps {
  /**
   * Style recipe. Defaults to `fileUploadItemRecipe` from `@pisagor/recipes/file-upload`.
   *
   * @defaultValue fileUploadItemRecipe
   */
  itemRecipe?: typeof fileUploadItemRecipe;
}

export type FileUploadListProps = Omit<FileUploadItemRootProps, "file">;

export interface FileUploadRootProps extends FileUploadPrimitiveRootProps {
  onValueChange?: (value: File[]) => void;
  /**
   * Style recipe. Defaults to `fileUploadRecipe` from `@pisagor/recipes/file-upload`.
   *
   * @defaultValue fileUploadRecipe
   */
  recipe?: typeof fileUploadRecipe;
}

export interface FileUploadDropzoneProps
  extends FileUploadPrimitiveDropzoneProps {
  /** Visual shell variant. Defaults to `primary`. */
  variant?: FormControlVariant;
}

export type FileUploadItemPreviewImageProps = ComponentProps<
  typeof FileUploadPrimitive.ItemPreviewImage
>;

export type FileUploadItemSizeProps = FileUploadItemSizeTextProps;

export type FileUploadItemDeleteTriggerProps = ComponentProps<
  typeof FileUploadPrimitive.ItemDeleteTrigger
>;

export type FileUploadDropzoneIconProps = ComponentProps<typeof ark.div>;

export type FileUploadTitleProps = ComponentProps<typeof ark.div>;

export type FileUploadDescriptionProps = ComponentProps<typeof ark.div>;

export type FileUploadHelperProps = ComponentProps<typeof ark.div>;
// #endregion

// #region Parts
export function FileUploadRoot({
  children,
  onFileChange,
  onValueChange,
  recipe = fileUploadRecipe,
  className,
  ...rest
}: FileUploadRootProps) {
  const slots = recipe();

  return (
    <FileUploadContext value={{ slots }}>
      <FileUploadPrimitive.Root
        {...rest}
        className={slots.base({ className })}
        onFileChange={(details) => {
          onFileChange?.(details);
          onValueChange?.(details.acceptedFiles);
        }}
      >
        {children}

        <FileUploadPrimitive.HiddenInput />
      </FileUploadPrimitive.Root>
    </FileUploadContext>
  );
}

export function FileUploadTrigger(props: FileUploadTriggerProps) {
  return <FileUploadPrimitive.Trigger {...props} />;
}

export function FileUploadDropzone({
  variant: variantProp,
  className,
  ...rest
}: FileUploadDropzoneProps) {
  const resolved = {
    surfaceVariant: useFormControlSurface(),
    variant: variantProp ?? ("primary" as FormControlVariant),
  };
  const shellArgs = {
    surfaceVariant: resolved.surfaceVariant,
    variant: resolved.variant,
  };
  const controlProps = { "data-variant": resolved.variant };
  const { slots } = useFileUpload();

  return (
    <FileUploadPrimitive.Dropzone
      {...rest}
      {...controlProps}
      className={cn(
        formControlZoneRecipe({ ...shellArgs }),
        slots.dropzone(),
        className,
      )}
    />
  );
}

export function FileUploadDropzoneIcon({
  children,
  className,
  ...rest
}: FileUploadDropzoneIconProps) {
  const { slots } = useFileUpload();

  return (
    <ark.div
      {...rest}
      className={slots.dropzoneIcon({ className })}
      data-part="dropzone-icon"
      data-scope="file-upload"
    >
      {children || <UploadIcon />}
    </ark.div>
  );
}

export function FileUploadTitle({ className, ...rest }: FileUploadTitleProps) {
  const { slots } = useFileUpload();

  return (
    <ark.div
      {...rest}
      className={slots.title({ className })}
      data-part="title"
      data-scope="file-upload"
    />
  );
}

export function FileUploadDescription({
  className,
  ...rest
}: FileUploadDescriptionProps) {
  const { slots } = useFileUpload();

  return (
    <ark.div
      {...rest}
      className={slots.description({ className })}
      data-part="title"
      data-scope="file-upload"
    />
  );
}

export function FileUploadHelper({
  className,
  ...rest
}: FileUploadHelperProps) {
  const { slots } = useFileUpload();

  return (
    <ark.div
      {...rest}
      className={slots.helper({ className })}
      data-part="dropzone-helper"
      data-scope="file-upload"
    />
  );
}

export function FileUploadItemGroup(props: FileUploadItemGroupProps) {
  return <FileUploadPrimitive.ItemGroup {...props} />;
}

export function FileUploadList({
  className,
  itemRecipe = fileUploadItemRecipe,
  ...rest
}: FileUploadListProps) {
  const fileUpload = useFileUploadContext();
  const { slots } = useFileUpload();
  const itemSlots = itemRecipe();

  const files = fileUpload.acceptedFiles;

  if (files.length === 0) {
    return null;
  }

  return (
    <FileUploadItemGroup className={slots.itemGroup()}>
      {files.map((file, index) => {
        const isImage = file.type.startsWith("image/");

        const key = `${file.name}-${index}`;

        const extension = file.name.split(".").pop();

        return (
          <FileUploadItem
            {...rest}
            className={itemSlots.listItem({ className })}
            file={file}
            itemRecipe={itemRecipe}
            key={key}
          >
            <FileUploadItemPreview
              {...(isImage ? { type: "image/*" } : { type: ".*" })}
              className={itemSlots.listPreview()}
            >
              {isImage ? (
                <FileUploadItemPreviewImage />
              ) : (
                <span className={itemSlots.extension()}>{extension}</span>
              )}
            </FileUploadItemPreview>

            <div className={itemSlots.content()}>
              <FileUploadItemName />
              <FileUploadItemSize />
            </div>

            <FileUploadItemDeleteTrigger asChild>
              <Button
                aria-label="Remove file"
                className={itemSlots.deleteButton()}
                size="icon-xs"
                variant="ghost"
              >
                <XIcon aria-hidden />
              </Button>
            </FileUploadItemDeleteTrigger>
          </FileUploadItem>
        );
      })}
    </FileUploadItemGroup>
  );
}

export function FileUploadItem({
  children,
  itemRecipe = fileUploadItemRecipe,
  className,
  ...rest
}: FileUploadItemRootProps) {
  const slots = itemRecipe();

  return (
    <FileUploadItemContext value={{ slots }}>
      <FileUploadPrimitive.Item {...rest} className={slots.base({ className })}>
        {children}
      </FileUploadPrimitive.Item>
    </FileUploadItemContext>
  );
}

export function FileUploadItemPreview({
  className,
  ...rest
}: FileUploadItemPreviewProps) {
  const { slots } = useFileUploadItem();

  return (
    <FileUploadPrimitive.ItemPreview
      {...rest}
      className={slots.preview({ className })}
    />
  );
}

export function FileUploadItemPreviewImage({
  className,
  ...rest
}: FileUploadItemPreviewImageProps) {
  const { slots } = useFileUploadItem();

  return (
    <FileUploadPrimitive.ItemPreviewImage
      {...rest}
      className={slots.previewImage({ className })}
    />
  );
}

export function FileUploadItemName({
  className,
  ...rest
}: FileUploadItemNameProps) {
  const { slots } = useFileUploadItem();

  return (
    <FileUploadPrimitive.ItemName
      {...rest}
      className={slots.name({ className })}
    />
  );
}

export function FileUploadItemSize({
  className,
  ...rest
}: FileUploadItemSizeProps) {
  const { slots } = useFileUploadItem();

  return (
    <FileUploadPrimitive.ItemSizeText
      {...rest}
      className={slots.size({ className })}
    />
  );
}

export function FileUploadItemDeleteTrigger({
  className,
  ...rest
}: FileUploadItemDeleteTriggerProps) {
  const { slots } = useFileUploadItem();

  return (
    <FileUploadPrimitive.ItemDeleteTrigger
      {...rest}
      className={slots.deleteTrigger({ className })}
    />
  );
}

export function FileUploadClearTrigger(props: FileUploadClearTriggerProps) {
  return <FileUploadPrimitive.ClearTrigger {...props} />;
}
// #endregion

// #region Display Names
FileUploadRoot.displayName = "FileUpload";
FileUploadTrigger.displayName = "FileUpload.Trigger";
FileUploadDropzone.displayName = "FileUpload.Dropzone";
FileUploadDropzoneIcon.displayName = "FileUpload.DropzoneIcon";
FileUploadTitle.displayName = "FileUpload.Title";
FileUploadDescription.displayName = "FileUpload.Description";
FileUploadHelper.displayName = "FileUpload.Helper";
FileUploadItemGroup.displayName = "FileUpload.ItemGroup";
FileUploadList.displayName = "FileUpload.List";
FileUploadItem.displayName = "FileUpload.Item";
FileUploadItemPreview.displayName = "FileUpload.ItemPreview";
FileUploadItemPreviewImage.displayName = "FileUpload.ItemPreviewImage";
FileUploadItemName.displayName = "FileUpload.ItemName";
FileUploadItemSize.displayName = "FileUpload.ItemSize";
FileUploadItemDeleteTrigger.displayName = "FileUpload.ItemDeleteTrigger";
FileUploadClearTrigger.displayName = "FileUpload.ClearTrigger";
// #endregion
