// packages/react-ui/src/components/steps/steps.tsx
import { ark } from "@ark-ui/react/factory";
import { Steps as StepsPrimitive } from "@ark-ui/react/steps";
import { CheckIcon } from "@phosphor-icons/react";
import { stepsItemVariants, stepsVariants } from "@pisagor/recipes/steps";
import type { ComponentProps } from "react";
import { useMemo } from "react";
import { StepsContext, StepsItemContext, useSteps, useStepsItem } from "./steps.context";

// #region Types
export type StepsTriggerProps = ComponentProps<typeof StepsPrimitive.Trigger>;

export type StepsRootProps = ComponentProps<typeof StepsPrimitive.Root>;

export type StepsListProps = ComponentProps<typeof StepsPrimitive.List>;

export type StepsItemProps = ComponentProps<typeof StepsPrimitive.Item>;

export type StepsIndicatorProps = ComponentProps<typeof StepsPrimitive.Indicator>;

export type StepsSeparatorProps = ComponentProps<typeof StepsPrimitive.Separator>;

export type StepsContentProps = ComponentProps<typeof StepsPrimitive.Content>;

export type StepsCompletedContentProps = ComponentProps<typeof StepsPrimitive.CompletedContent>;

export type StepsPrevTriggerProps = ComponentProps<typeof StepsPrimitive.PrevTrigger>;

export type StepsNextTriggerProps = ComponentProps<typeof StepsPrimitive.NextTrigger>;

export interface StepsTitleProps extends ComponentProps<typeof ark.span> {}

export interface StepsDescriptionProps extends ComponentProps<typeof ark.span> {}
// #endregion

// #region Parts
export function StepsRoot({ children, className, ...rest }: StepsRootProps) {
  const slots = useMemo(() => stepsVariants(), []);

  return (
    <StepsContext value={{ slots }}>
      <StepsPrimitive.Root {...rest} className={slots.base({ className })}>
        {children}
      </StepsPrimitive.Root>
    </StepsContext>
  );
}

export function StepsList({ className, ...rest }: StepsListProps) {
  const { slots } = useSteps();

  return <StepsPrimitive.List {...rest} className={slots.list({ className })} />;
}

export function StepsItem({ children, className, ...rest }: StepsItemProps) {
  const slots = useMemo(() => stepsItemVariants(), []);

  return (
    <StepsItemContext value={{ slots }}>
      <StepsPrimitive.Item {...rest} className={slots.base({ className })}>
        {children}
      </StepsPrimitive.Item>
    </StepsItemContext>
  );
}

export function StepsTrigger({ className, ...rest }: StepsTriggerProps) {
  const { slots } = useStepsItem();

  return <StepsPrimitive.Trigger {...rest} className={slots.trigger({ className })} />;
}

export function StepsIndicator({ children, className, ...rest }: StepsIndicatorProps) {
  const { slots } = useStepsItem();

  return (
    <StepsPrimitive.Indicator {...rest} className={slots.indicator({ className })}>
      <span className={slots.label()}>{children}</span>
      <CheckIcon className={slots.check()} />
    </StepsPrimitive.Indicator>
  );
}

export function StepsSeparator({ className, ...rest }: StepsSeparatorProps) {
  const { slots } = useStepsItem();

  return <StepsPrimitive.Separator {...rest} className={slots.separator({ className })} />;
}

export function StepsTitle({ className, ...rest }: StepsTitleProps) {
  const { slots } = useStepsItem();

  return (
    <ark.span
      {...rest}
      className={slots.title({ className })}
      data-part="title"
      data-scope="steps"
    />
  );
}

export function StepsDescription({ className, ...rest }: StepsDescriptionProps) {
  const { slots } = useStepsItem();

  return (
    <ark.span
      {...rest}
      className={slots.description({ className })}
      data-part="description"
      data-scope="steps"
    />
  );
}

export function StepsContent({ className, ...rest }: StepsContentProps) {
  const { slots } = useSteps();

  return <StepsPrimitive.Content {...rest} className={slots.content({ className })} />;
}

export function StepsCompletedContent({ className, ...rest }: StepsCompletedContentProps) {
  const { slots } = useSteps();

  return (
    <StepsPrimitive.CompletedContent {...rest} className={slots.completedContent({ className })} />
  );
}

export function StepsPrevTrigger(props: StepsPrevTriggerProps) {
  return <StepsPrimitive.PrevTrigger {...props} />;
}

export function StepsNextTrigger(props: StepsNextTriggerProps) {
  return <StepsPrimitive.NextTrigger {...props} />;
}
// #endregion

// #region Display Names
StepsRoot.displayName = "Steps";
StepsList.displayName = "Steps.List";
StepsItem.displayName = "Steps.Item";
StepsTrigger.displayName = "Steps.Trigger";
StepsIndicator.displayName = "Steps.Indicator";
StepsSeparator.displayName = "Steps.Separator";
StepsTitle.displayName = "Steps.Title";
StepsDescription.displayName = "Steps.Description";
StepsContent.displayName = "Steps.Content";
StepsCompletedContent.displayName = "Steps.CompletedContent";
StepsPrevTrigger.displayName = "Steps.PrevTrigger";
StepsNextTrigger.displayName = "Steps.NextTrigger";
// #endregion

// packages/solid/src/components/steps/steps.tsx
import { ark } from "@ark-ui/solid/factory";
import type {
  StepsCompletedContentProps,
  StepsContentProps,
  StepsIndicatorProps,
  StepsListProps,
  StepsNextTriggerProps,
  StepsPrevTriggerProps,
  StepsItemProps as StepsPrimitiveItemProps,
  StepsRootProps as StepsPrimitiveRootProps,
  StepsSeparatorProps,
  StepsTriggerProps,
} from "@ark-ui/solid/steps";
import { Steps as StepsPrimitive } from "@ark-ui/solid/steps";
import { stepsItemRecipe, stepsRecipe } from "@pisagor/recipes/steps";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { splitProps } from "solid-js";
import { CheckIcon } from "../../internal/icons";
import {
  StepsContext,
  StepsItemContext,
  useSteps,
  useStepsItem,
} from "./steps.context";

export interface StepsRootProps extends StepsPrimitiveRootProps {
  recipe?: typeof stepsRecipe;
}

export interface StepsItemProps extends StepsPrimitiveItemProps {
  itemRecipe?: typeof stepsItemRecipe;
}

export type StepsTitleProps = ComponentProps<typeof ark.span>;
export type StepsDescriptionProps = ComponentProps<typeof ark.span>;

export function StepsRoot(props: StepsRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? stepsRecipe)();

  return (
    <StepsContext value={{ slots: slots() }}>
      <StepsPrimitive.Root
        {...rest}
        class={slots().base({ class: cn(local.class) })}
      >
        {local.children}
      </StepsPrimitive.Root>
    </StepsContext>
  );
}

export function StepsList(props: StepsListProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useSteps();
  return (
    <StepsPrimitive.List
      {...rest}
      class={slots.list({ class: cn(local.class) })}
    />
  );
}

export function StepsItem(props: StepsItemProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "itemRecipe", "class"]);
  const slots = () => (local.itemRecipe ?? stepsItemRecipe)();

  return (
    <StepsItemContext value={{ slots: slots() }}>
      <StepsPrimitive.Item
        {...rest}
        class={slots().base({ class: cn(local.class) })}
      >
        {local.children}
      </StepsPrimitive.Item>
    </StepsItemContext>
  );
}

export function StepsTrigger(props: StepsTriggerProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useStepsItem();
  return (
    <StepsPrimitive.Trigger
      {...rest}
      class={slots.trigger({ class: cn(local.class) })}
    />
  );
}

export function StepsIndicator(props: StepsIndicatorProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useStepsItem();
  return (
    <StepsPrimitive.Indicator
      {...rest}
      class={slots.indicator({ class: cn(local.class) })}
    >
      <span class={slots.label()}>{local.children}</span>
      <CheckIcon class={slots.check()} />
    </StepsPrimitive.Indicator>
  );
}

export function StepsSeparator(props: StepsSeparatorProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useStepsItem();
  return (
    <StepsPrimitive.Separator
      {...rest}
      class={slots.separator({ class: cn(local.class) })}
    />
  );
}

export function StepsTitle(props: StepsTitleProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useStepsItem();
  return (
    <ark.span
      {...rest}
      class={slots.title({ class: cn(local.class) })}
      data-part="title"
      data-scope="steps"
    />
  );
}

export function StepsDescription(props: StepsDescriptionProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useStepsItem();
  return (
    <ark.span
      {...rest}
      class={slots.description({ class: cn(local.class) })}
      data-part="description"
      data-scope="steps"
    />
  );
}

export function StepsContent(props: StepsContentProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useSteps();
  return (
    <StepsPrimitive.Content
      {...rest}
      class={slots.content({ class: cn(local.class) })}
    />
  );
}

export function StepsCompletedContent(
  props: StepsCompletedContentProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useSteps();
  return (
    <StepsPrimitive.CompletedContent
      {...rest}
      class={slots.completedContent({ class: cn(local.class) })}
    />
  );
}

export function StepsPrevTrigger(props: StepsPrevTriggerProps): JSX.Element {
  return <StepsPrimitive.PrevTrigger {...props} />;
}

export function StepsNextTrigger(props: StepsNextTriggerProps): JSX.Element {
  return <StepsPrimitive.NextTrigger {...props} />;
}
