// packages/react/src/components/input/input.tsx
import {
  type FieldInputProps,
  FieldInput as InputPrimitive,
} from "@ark-ui/react/field";
import type { InputProps as BaseInputProps } from "@pisagor/props";
import {
  type InputRecipeSlot,
  inputRecipe,
  inputRootRecipe,
} from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { ChangeEventHandler, RefAttributes } from "react";
import { useClearableInput } from "../../hooks";
import type { VariantClassNames } from "../../internal/types";
import { InputGroupRoot } from "../input-group/input-group-core";
import { useFormControlSurface } from "../surface/use-form-control-surface";
import { InputClearAddon } from "./input-clear-button";

// #region Types
type FormControlVariant = "primary" | "secondary";

type InputClassNames = VariantClassNames<InputRecipeSlot>;

export interface InputProps
  extends Omit<FieldInputProps, "size">,
    RefAttributes<HTMLInputElement>,
    BaseInputProps {
  /**
   * Whether to show a clear button when the input has a value.
   *
   * @defaultValue false
   *
   * @remarks
   * In controlled mode, pass `value` and update it via `onChange` or `onValueChange` when clearing.
   */
  clearable?: boolean;
  /** Called with the string value when the input changes. */
  onValueChange?: (value: string) => void;
  /**
   * Root style recipe. Defaults to `inputRootRecipe` from `@pisagor/recipes/input`.
   *
   * @defaultValue inputRootRecipe
   */
  rootRecipe?: typeof inputRootRecipe;
  /** Slot class names */
  classNames?: InputClassNames;
}
// #endregion

// #region Component
export function Input({
  size = "md",
  variant: variantProp,
  clearable = false,
  defaultValue,
  disabled,
  readOnly,
  type = "text",
  value,
  ref,
  onChange,
  onValueChange,
  recipe = inputRecipe,
  rootRecipe = inputRootRecipe,
  className,
  classNames,
  ...rest
}: InputProps) {
  const resolved = {
    surfaceVariant: useFormControlSurface(),
    variant: variantProp ?? ("primary" as FormControlVariant),
  };

  const { canClear, handleChange, handleClear, mergedRef } = useClearableInput({
    clearable: clearable && type !== "file" && type !== "password",
    defaultValue,
    disabled,
    onChange,
    onValueChange,
    readOnly,
    ref,
    type,
    value,
  });

  const skipClearable = !clearable || type === "file" || type === "password";
  const shellArgs = {
    surfaceVariant: resolved.surfaceVariant,
    variant: resolved.variant,
  };
  const controlProps = { "data-variant": resolved.variant };
  const slots = recipe();

  const changeHandler: ChangeEventHandler<HTMLInputElement> | undefined =
    skipClearable
      ? onChange || onValueChange
        ? (event) => {
            onChange?.(event);
            onValueChange?.(event.target.value);
          }
        : undefined
      : handleChange;

  if (skipClearable) {
    return (
      <InputPrimitive
        {...rest}
        {...controlProps}
        className={rootRecipe({ className, size, ...shellArgs })}
        data-size={size}
        defaultValue={defaultValue}
        disabled={disabled}
        onChange={changeHandler}
        readOnly={readOnly}
        ref={ref}
        type={type}
        value={value}
      />
    );
  }

  return (
    <InputGroupRoot size={size} variant={variantProp}>
      <InputPrimitive
        {...rest}
        className={slots.clearableRoot({
          className: cn(className, classNames?.clearableRoot),
        })}
        data-size={size}
        defaultValue={defaultValue}
        disabled={disabled}
        onChange={handleChange}
        readOnly={readOnly}
        ref={mergedRef}
        type={type}
        value={value}
      />
      {canClear ? <InputClearAddon onClear={handleClear} /> : null}
    </InputGroupRoot>
  );
}
// #endregion

// packages/svelte/src/components/input/input.svelte
<script lang="ts">
import { Field, type FieldInputProps } from "@ark-ui/svelte/field";
import type { InputProps as BaseInputProps } from "@pisagor/props";
import {
  type InputRecipeSlot,
  type InputRootVariantProps,
  inputRecipe,
  inputRootRecipe,
} from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { VariantClassNames } from "../../internal/types";
import InputGroupRoot from "../input-group/input-group-root.svelte";
import { useFormControlSurface } from "../surface/use-form-control-surface";
import InputClearAddon from "./input-clear-addon.svelte";

type FormControlVariant = "primary" | "secondary";

type Props = Omit<FieldInputProps, "size"> &
  InputRootVariantProps & {
    /**
     * Whether to show a clear button when the input has a value.
     * @defaultValue false
     */
    clearable?: boolean;
    classNames?: VariantClassNames<InputRecipeSlot>;
    /** Called with the string value when the input changes. */
    onValueChange?: (value: string) => void;
    rootRecipe?: typeof inputRootRecipe;
  } & BaseInputProps;

let {
  size = "md",
  variant: variantProp,
  clearable = false,
  disabled,
  readonly,
  type = "text",
  value = $bindable<string | number | undefined>(undefined),
  oninput,
  onValueChange,
  recipe = inputRecipe,
  rootRecipe = inputRootRecipe,
  class: className,
  classNames,
  ...rest
}: Props = $props();

const surfaceVariant = useFormControlSurface();
const variant = $derived(variantProp ?? ("primary" as FormControlVariant));
const slots = $derived(recipe());

const skipClearable = $derived(
  !clearable || type === "file" || type === "password",
);
const canClear = $derived(
  !skipClearable && !disabled && !readonly && String(value ?? "").length > 0,
);

function handleInput(event: Event & { currentTarget: HTMLInputElement }) {
  const next = event.currentTarget.value;
  value = next;
  onValueChange?.(next);
  oninput?.(event as never);
}

function handleClear() {
  value = "";
  onValueChange?.("");
}
</script>

{#if skipClearable}
  <Field.Input
    {...rest}
    class={rootRecipe({ class: cn(className), size, surfaceVariant, variant })}
    data-size={size}
    data-variant={variant}
    {disabled}
    oninput={handleInput}
    {readonly}
    {type}
    bind:value
  />
{:else}
  <InputGroupRoot {size} {variant}>
    <Field.Input
      {...rest}
      class={slots.clearableRoot({
        class: cn(className, classNames?.clearableRoot),
      })}
      data-size={size}
      {disabled}
      oninput={handleInput}
      {readonly}
      {type}
      bind:value
    />
    {#if canClear}
      <InputClearAddon onClear={handleClear} />
    {/if}
  </InputGroupRoot>
{/if}
