// packages/react/src/components/status/status.tsx
import { ark } from "@ark-ui/react/factory";
import type { StatusProps as StatusSharedProps } from "@pisagor/props";
import { statusRecipe } from "@pisagor/recipes";
import type { ComponentProps } from "react";

// #region Types
export interface StatusProps
  extends ComponentProps<typeof ark.span>,
    StatusSharedProps {}
// #endregion

// #region Component
export function Status({
  size,
  variant,
  recipe = statusRecipe,
  className,
  ...rest
}: StatusProps) {
  return (
    <ark.span
      {...rest}
      className={recipe({ className, size, variant })}
      data-part="indicator"
      data-scope="status"
      data-size={size}
    />
  );
}
// #endregion

// packages/solid/src/components/status/status.tsx
import { ark } from "@ark-ui/solid/factory";
import type { StatusProps as StatusSharedProps } from "@pisagor/props";
import { statusRecipe } from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { splitProps } from "solid-js";

export interface StatusProps
  extends ComponentProps<typeof ark.span>,
    StatusSharedProps {
  size?: import("@pisagor/recipes/status").StatusVariantProps["size"];
  variant?: import("@pisagor/recipes/status").StatusVariantProps["variant"];
}

export function Status(props: StatusProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "class",
    "recipe",
    "size",
    "variant",
  ]);
  const recipeFn = () => local.recipe ?? statusRecipe;

  return (
    <ark.span
      {...rest}
      class={recipeFn()({
        class: cn(local.class),
        size: local.size,
        variant: local.variant,
      })}
      data-part="indicator"
      data-scope="status"
      data-size={local.size}
    />
  );
}
