// packages/solid/src/components/resizable/resizable.tsx
import type {
  SplitterContextProps,
  SplitterPanelProps,
  SplitterResizeTriggerIndicatorProps,
  SplitterResizeTriggerProps,
  SplitterRootProps,
  SplitterRootProviderProps,
} from "@ark-ui/solid/splitter";
import { Splitter as SplitterPrimitive } from "@ark-ui/solid/splitter";
import { resizableEdgeHandleRecipe, resizableRecipe } from "@pisagor/recipes/resizable";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { Show, splitProps } from "solid-js";
import { DotsSixVerticalIcon } from "../../internal/icons";
import { ResizableSlotsContext, useResizable } from "./resizable.context";

export type {
  SplitterExpandCollapseDetails as ExpandCollapseDetails,
  SplitterPanelData as PanelData,
  SplitterResizeDetails as ResizeDetails,
  SplitterResizeEndDetails as ResizeEndDetails,
  UseSplitterProps,
  UseSplitterReturn,
} from "@ark-ui/solid/splitter";
export {
  createSplitterRegistry as createRegistry,
  useSplitter,
  useSplitterContext,
} from "@ark-ui/solid/splitter";

export type ResizableHandlePosition = "bottom" | "center" | "top";
export type ResizableEdgePlacement = "end" | "start";

export interface ResizableEdgeHandleProps extends ComponentProps<"button"> {
  placement: ResizableEdgePlacement;
  handlePosition?: ResizableHandlePosition;
  minWidth?: number;
  width: number;
  label: string;
  onResizeChange?: (width: number) => void;
  onResizeEnd?: () => void;
  onResizeStart?: () => void;
  onWidthChange: (width: number) => void;
  recipe?: typeof resizableEdgeHandleRecipe;
}

export interface ResizableResizeTriggerProps extends SplitterResizeTriggerProps {
  withHandle?: boolean;
}

export interface ResizableRootProps extends SplitterRootProps {
  recipe?: typeof resizableRecipe;
}

export type ResizablePanelProps = SplitterPanelProps;
export type ResizableResizeTriggerIndicatorProps = SplitterResizeTriggerIndicatorProps;
export type ResizableContextProps = SplitterContextProps;

export interface ResizableRootProviderProps extends SplitterRootProviderProps {
  recipe?: typeof resizableRecipe;
}

export function ResizableEdgeHandle(props: ResizableEdgeHandleProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "placement",
    "handlePosition",
    "label",
    "minWidth",
    "width",
    "onResizeChange",
    "onResizeEnd",
    "onResizeStart",
    "onWidthChange",
    "recipe",
    "class",
  ]);

  const handlePosition = () => local.handlePosition ?? "center";
  const minWidth = () => local.minWidth ?? 1;
  const isStart = () => local.placement === "start";
  const edgeHandle = () =>
    (local.recipe ?? resizableEdgeHandleRecipe)({
      handlePosition: handlePosition(),
      placement: local.placement,
    });

  const initialWidth = { current: local.width };
  const startX = { current: 0 };
  const startWidth = { current: local.width };
  const liveWidth = { current: local.width };

  const applyWidth = (nextWidth: number) => {
    liveWidth.current = nextWidth;
    startWidth.current = nextWidth;
    local.onResizeChange?.(nextWidth);
    local.onWidthChange(nextWidth);
  };

  return (
    <button
      {...rest}
      aria-label={local.label}
      class={edgeHandle().base({ class: cn(local.class) })}
      data-handle-position={handlePosition()}
      data-part="edge-handle"
      data-scope="resizable"
      onDblClick={(event) => {
        event.preventDefault();
        local.onResizeEnd?.();
        applyWidth(initialWidth.current);
      }}
      onLostPointerCapture={() => {
        local.onResizeEnd?.();
        local.onWidthChange(liveWidth.current);
      }}
      onPointerDown={(event) => {
        event.currentTarget.setPointerCapture(event.pointerId);
        startX.current = event.clientX;
        startWidth.current = local.width;
        liveWidth.current = local.width;
        local.onResizeStart?.();
      }}
      onPointerMove={(event) => {
        if (!event.currentTarget.hasPointerCapture(event.pointerId)) {
          return;
        }
        const delta = event.clientX - startX.current;
        const next = Math.max(
          minWidth(),
          isStart() ? startWidth.current + delta : startWidth.current - delta,
        );
        liveWidth.current = next;
        local.onResizeChange?.(next);
      }}
      onPointerUp={(event) => {
        event.currentTarget.releasePointerCapture(event.pointerId);
        local.onResizeEnd?.();
        local.onWidthChange(liveWidth.current);
      }}
      type="button"
    >
      <span class={edgeHandle().grip()}>
        <DotsSixVerticalIcon class={edgeHandle().icon()} />
      </span>
    </button>
  );
}

export function ResizableRoot(props: ResizableRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? resizableRecipe)();

  return (
    <ResizableSlotsContext value={{ slots: slots() }}>
      <SplitterPrimitive.Root {...rest} class={slots().base({ class: cn(local.class) })}>
        {local.children}
      </SplitterPrimitive.Root>
    </ResizableSlotsContext>
  );
}

export function ResizablePanel(props: ResizablePanelProps): JSX.Element {
  return <SplitterPrimitive.Panel {...props} />;
}

export function ResizableResizeTriggerIndicator(
  props: ResizableResizeTriggerIndicatorProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useResizable();
  return (
    <SplitterPrimitive.ResizeTriggerIndicator
      {...rest}
      class={slots.resizeTriggerIndicator({ class: cn(local.class) })}
    />
  );
}

export function ResizableResizeTrigger(props: ResizableResizeTriggerProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "withHandle", "class"]);
  const { slots } = useResizable();
  const withHandle = () => local.withHandle ?? false;

  return (
    <SplitterPrimitive.ResizeTrigger
      {...rest}
      aria-label="Resize"
      class={slots.resizeTrigger({ class: cn(local.class) })}
    >
      <Show fallback={local.children ?? <ResizableResizeTriggerIndicator />} when={withHandle()}>
        <div class={slots.resizeTriggerHandle()}>
          <DotsSixVerticalIcon class={slots.resizeTriggerIcon()} />
        </div>
      </Show>
    </SplitterPrimitive.ResizeTrigger>
  );
}

export function ResizableContext(props: ResizableContextProps): JSX.Element {
  return <SplitterPrimitive.Context {...props} />;
}

export function ResizableRootProvider(props: ResizableRootProviderProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? resizableRecipe)();

  return (
    <ResizableSlotsContext value={{ slots: slots() }}>
      <SplitterPrimitive.RootProvider {...rest} class={slots().base({ class: cn(local.class) })}>
        {local.children}
      </SplitterPrimitive.RootProvider>
    </ResizableSlotsContext>
  );
}

// packages/react-ui/src/components/resizable/resizable.tsx
import { Splitter as SplitterPrimitive } from "@ark-ui/react/splitter";
import { DotsSixVerticalIcon } from "@phosphor-icons/react";
import { resizableEdgeHandleVariants, resizableVariants } from "@pisagor/recipes/resizable";
import { type ComponentProps, useCallback, useRef } from "react";
import { ResizableSlotsContext, useResizable } from "./resizable.context";

export type {
  SplitterExpandCollapseDetails as ExpandCollapseDetails,
  SplitterPanelData as PanelData,
  SplitterResizeDetails as ResizeDetails,
  SplitterResizeEndDetails as ResizeEndDetails,
  UseSplitterProps,
  UseSplitterReturn,
} from "@ark-ui/react/splitter";
export {
  createSplitterRegistry as createRegistry,
  useSplitter,
  useSplitterContext,
} from "@ark-ui/react/splitter";

// #region Types
export type ResizableHandlePosition = "bottom" | "center" | "top";
export type ResizableEdgePlacement = "end" | "start";

export interface ResizableEdgeHandleProps extends ComponentProps<"button"> {
  /** Which edge of the resizable region the handle sits on. */
  placement: ResizableEdgePlacement;
  /** Vertical placement of the visible grip. @defaultValue `"center"` */
  handlePosition?: ResizableHandlePosition;
  /** Minimum width in pixels. @defaultValue 1 */
  minWidth?: number;
  /** Current width in pixels. */
  width: number;
  /** Accessible label for the resize control. */
  label: string;
  /** Called during drag for live width updates. */
  onResizeChange?: (width: number) => void;
  /** Called when a resize interaction ends. */
  onResizeEnd?: () => void;
  /** Called when a resize interaction starts. */
  onResizeStart?: () => void;
  /** Called when the width settles after drag or double-click reset. */
  onWidthChange: (width: number) => void;
}

export interface ResizableResizeTriggerProps
  extends ComponentProps<typeof SplitterPrimitive.ResizeTrigger> {
  /**
   * Whether to show the handle.
   *
   * @defaultValue false
   */
  withHandle?: boolean;
}

export type ResizableRootProps = ComponentProps<typeof SplitterPrimitive.Root>;

export type ResizablePanelProps = ComponentProps<typeof SplitterPrimitive.Panel>;

export type ResizableResizeTriggerIndicatorProps = ComponentProps<
  typeof SplitterPrimitive.ResizeTriggerIndicator
>;

export type ResizableContextProps = ComponentProps<typeof SplitterPrimitive.Context>;

export type ResizableRootProviderProps = ComponentProps<typeof SplitterPrimitive.RootProvider>;
// #endregion

// #region Parts
export function ResizableEdgeHandle({
  placement,
  handlePosition = "center",
  label,
  minWidth = 1,
  width,
  onResizeChange,
  onResizeEnd,
  onResizeStart,
  onWidthChange,
  className,
  ...rest
}: ResizableEdgeHandleProps) {
  const initialWidthRef = useRef(width);
  const startXRef = useRef(0);
  const startWidthRef = useRef(width);
  const liveWidthRef = useRef(width);
  const isStart = placement === "start";
  const edgeHandle = resizableEdgeHandleVariants({ handlePosition, placement });

  const applyWidth = useCallback(
    (nextWidth: number) => {
      liveWidthRef.current = nextWidth;
      startWidthRef.current = nextWidth;
      onResizeChange?.(nextWidth);
      onWidthChange(nextWidth);
    },
    [onResizeChange, onWidthChange],
  );

  return (
    <button
      {...rest}
      aria-label={label}
      className={edgeHandle.base({ className })}
      data-handle-position={handlePosition}
      data-part="edge-handle"
      data-scope="resizable"
      onDoubleClick={(event) => {
        event.preventDefault();
        onResizeEnd?.();
        applyWidth(initialWidthRef.current);
      }}
      onLostPointerCapture={() => {
        onResizeEnd?.();
        onWidthChange(liveWidthRef.current);
      }}
      onPointerDown={(event) => {
        event.currentTarget.setPointerCapture(event.pointerId);
        startXRef.current = event.clientX;
        startWidthRef.current = width;
        liveWidthRef.current = width;
        onResizeStart?.();
      }}
      onPointerMove={(event) => {
        if (!event.currentTarget.hasPointerCapture(event.pointerId)) {
          return;
        }

        const delta = event.clientX - startXRef.current;
        const next = Math.max(
          minWidth,
          isStart ? startWidthRef.current + delta : startWidthRef.current - delta,
        );

        liveWidthRef.current = next;
        onResizeChange?.(next);
      }}
      onPointerUp={(event) => {
        event.currentTarget.releasePointerCapture(event.pointerId);
        onResizeEnd?.();
        onWidthChange(liveWidthRef.current);
      }}
      type="button"
    >
      <span className={edgeHandle.grip()}>
        <DotsSixVerticalIcon className={edgeHandle.icon()} />
      </span>
    </button>
  );
}

export function ResizableRoot({ children, className, ...rest }: ResizableRootProps) {
  const slots = resizableVariants();

  return (
    <ResizableSlotsContext value={{ slots }}>
      <SplitterPrimitive.Root {...rest} className={slots.base({ className })}>
        {children}
      </SplitterPrimitive.Root>
    </ResizableSlotsContext>
  );
}

export function ResizablePanel(props: ResizablePanelProps) {
  return <SplitterPrimitive.Panel {...props} />;
}

export function ResizableResizeTriggerIndicator({
  className,
  ...rest
}: ResizableResizeTriggerIndicatorProps) {
  const { slots } = useResizable();

  return (
    <SplitterPrimitive.ResizeTriggerIndicator
      {...rest}
      className={slots.resizeTriggerIndicator({ className })}
    />
  );
}

export function ResizableResizeTrigger({
  children,
  withHandle = false,
  className,
  ...rest
}: ResizableResizeTriggerProps) {
  const { slots } = useResizable();

  return (
    <SplitterPrimitive.ResizeTrigger
      {...rest}
      aria-label="Resize"
      className={slots.resizeTrigger({ className })}
    >
      {withHandle ? (
        <div className={slots.resizeTriggerHandle()}>
          <DotsSixVerticalIcon className={slots.resizeTriggerIcon()} />
        </div>
      ) : (
        (children ?? <ResizableResizeTriggerIndicator />)
      )}
    </SplitterPrimitive.ResizeTrigger>
  );
}

export function ResizableContext(props: ResizableContextProps) {
  return <SplitterPrimitive.Context {...props} />;
}

export function ResizableRootProvider({
  children,
  className,
  ...rest
}: ResizableRootProviderProps) {
  const slots = resizableVariants();

  return (
    <ResizableSlotsContext value={{ slots }}>
      <SplitterPrimitive.RootProvider {...rest} className={slots.base({ className })}>
        {children}
      </SplitterPrimitive.RootProvider>
    </ResizableSlotsContext>
  );
}
// #endregion

// #region Display Names
ResizableEdgeHandle.displayName = "Resizable.EdgeHandle";
ResizableRoot.displayName = "Resizable";
ResizablePanel.displayName = "Resizable.Panel";
ResizableResizeTriggerIndicator.displayName = "Resizable.ResizeTriggerIndicator";
ResizableResizeTrigger.displayName = "Resizable.ResizeTrigger";
ResizableContext.displayName = "Resizable.Context";
ResizableRootProvider.displayName = "Resizable.RootProvider";
// #endregion
