// packages/react-form/src/tanstack/components/submit-button.tsx
import { Button, type ButtonProps } from "@pisagor/react";
import type { ReactNode } from "react";
import { useFormContext } from "../contexts";

interface SubmitButtonProps extends Omit<ButtonProps, "type"> {
  children: ReactNode;
}

export function SubmitButton({
  loading,
  children,
  ...buttonProps
}: SubmitButtonProps) {
  const form = useFormContext();

  return (
    <form.Subscribe selector={(state) => state.isSubmitting}>
      {(isSubmitting) => (
        <Button
          {...buttonProps}
          loading={loading ?? isSubmitting}
          type="submit"
        >
          {children}
        </Button>
      )}
    </form.Subscribe>
  );
}

// packages/svelte-form/src/tanstack/components/submit-button.svelte
<script lang="ts">
import { Button } from "@pisagor/svelte";
import type { ComponentProps, Snippet } from "svelte";
import { useFormContext } from "../contexts";

type ButtonProps = ComponentProps<typeof Button>;

type Props = Omit<ButtonProps, "type" | "children"> & {
  children?: Snippet;
};

let { loading, children, ...buttonProps }: Props = $props();
const form = useFormContext();
</script>

<form.Subscribe selector={(state) => state.isSubmitting}>
  {#snippet children(
  isSubmitting,
)}
    <Button {...buttonProps} loading={loading ?? isSubmitting} type="submit">
      {@render children?.()}
    </Button>
  {/snippet}
</form.Subscribe>
