// packages/react/src/components/button-group/examples/with-separator.tsx
import { MinusIcon, PlusIcon } from "@phosphor-icons/react";
import { Button } from "@pisagor/react";
import { ButtonGroup } from "..";
export function WithSeparator() {
  return (
    <ButtonGroup>
      <Button aria-label="Remove" size="icon-md" variant="secondary">
        <MinusIcon />
      </Button>
      <ButtonGroup.Separator />
      <Button aria-label="Add" size="icon-md" variant="secondary">
        <PlusIcon />
      </Button>
    </ButtonGroup>
  );
}

// packages/svelte/examples/button-group/with-separator.svelte
<script lang="ts">
import { Button, ButtonGroup } from "@pisagor/svelte";
import MinusIcon from "phosphor-svelte/lib/MinusIcon";
import PlusIcon from "phosphor-svelte/lib/PlusIcon";
</script>

<ButtonGroup>
  <Button aria-label="Remove" size="icon-md" variant="secondary">
    <MinusIcon />
  </Button>
  <ButtonGroup.Separator />
  <Button aria-label="Add" size="icon-md" variant="secondary">
    <PlusIcon />
  </Button>
</ButtonGroup>
