// packages/react/src/components/item/item-group.tsx
import { ark } from "@ark-ui/react/factory";
import type {
  ItemProps as BaseItemGroupProps,
  ItemProps as BaseItemSeparatorProps,
} from "@pisagor/props";
import { itemRecipe } from "@pisagor/recipes";
import type { ComponentProps } from "react";
import { Separator, type SeparatorProps } from "../separator";
import { ItemGroupContext } from "./item-group.context";

// #region Types
export interface ItemGroupProps
  extends ComponentProps<typeof ark.div>,
    BaseItemGroupProps {}

export interface ItemSeparatorProps
  extends Omit<SeparatorProps, "recipe">,
    BaseItemSeparatorProps {}
// #endregion

// #region Parts
export function ItemGroup({
  variant = "default",
  children,
  recipe = itemRecipe,
  className,
  ...rest
}: ItemGroupProps) {
  const slots = recipe();

  return (
    <ItemGroupContext value={{ variant }}>
      <ark.div
        {...rest}
        className={slots.group({ className })}
        data-part="group"
        data-scope="item"
        data-variant={variant}
        role="list"
      >
        {children}
      </ark.div>
    </ItemGroupContext>
  );
}

export function ItemSeparator({
  recipe = itemRecipe,
  className,
  ...rest
}: ItemSeparatorProps) {
  const slots = recipe();

  return (
    <Separator
      {...rest}
      className={slots.separator({ className })}
      data-part="separator"
      data-scope="item"
      orientation="horizontal"
    />
  );
}
// #endregion

// #region Display Names
ItemGroup.displayName = "Item.Group";
ItemSeparator.displayName = "Item.Separator";
// #endregion

// packages/solid/src/components/item/item-group.tsx
import { ark } from "@ark-ui/solid/factory";
import type {
  ItemProps as BaseItemGroupProps,
  ItemProps as BaseItemSeparatorProps,
} from "@pisagor/props";
import { itemRecipe } from "@pisagor/recipes";
import type { ComponentProps, JSX } from "solid-js";
import { splitProps } from "solid-js";
import { Separator, type SeparatorProps } from "../separator";
import { ItemGroupContext } from "./item-group.context";

export interface ItemGroupProps
  extends ComponentProps<typeof ark.div>,
    BaseItemGroupProps {}

export interface ItemSeparatorProps
  extends Omit<SeparatorProps, "recipe">,
    BaseItemSeparatorProps {}

export function ItemGroup(props: ItemGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "variant",
    "children",
    "recipe",
    "class",
  ]);
  const variant = () => local.variant ?? "default";
  const slots = () => (local.recipe ?? itemRecipe)();

  return (
    <ItemGroupContext value={{ variant: variant() }}>
      <ark.div
        {...rest}
        class={slots().group({ class: local.class })}
        data-part="group"
        data-scope="item"
        data-variant={variant()}
        role="list"
      >
        {local.children}
      </ark.div>
    </ItemGroupContext>
  );
}

export function ItemSeparator(props: ItemSeparatorProps): JSX.Element {
  const [local, rest] = splitProps(props, ["recipe", "class"]);
  const slots = () => (local.recipe ?? itemRecipe)();

  return (
    <Separator
      {...rest}
      class={slots().separator({ class: local.class })}
      data-part="separator"
      data-scope="item"
      orientation="horizontal"
    />
  );
}
