// packages/svelte/src/components/item/item-group.svelte
<script lang="ts">
import { Ark } from "@ark-ui/svelte/factory";
import { type ItemVariantProps, itemRecipe } from "@pisagor/recipes/item";
import { cn } from "@pisagor/utils";
import type { HTMLAttributes } from "svelte/elements";
import { setItemGroupContext } from "./item-group.context";

type Props = Omit<HTMLAttributes<HTMLDivElement>, "class"> &
  ItemVariantProps & {
    children?: import("svelte").Snippet;
    class?: string | undefined;
    recipe?: typeof itemRecipe;
  };

let {
  variant = "default",
  children,
  recipe = itemRecipe,
  class: className,
  ...rest
}: Props = $props();

const slots = $derived(recipe());

setItemGroupContext({
  get variant() {
    return variant;
  },
});
</script>

<Ark
  as="div"
  {...rest}
  class={slots.group({ class: cn(className) })}
  data-part="group"
  data-scope="item"
  data-variant={variant}
  role="list"
>
  {@render children?.()}
</Ark>

// packages/solid/src/components/item/item-group.tsx
import { ark } from "@ark-ui/solid/factory";
import { type ItemVariantProps, itemRecipe } from "@pisagor/recipes/item";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { splitProps } from "solid-js";
import { Separator, type SeparatorProps } from "../separator";
import { ItemGroupContext } from "./item-group.context";

export interface ItemGroupProps
  extends ComponentProps<typeof ark.div>,
    ItemVariantProps {
  recipe?: typeof itemRecipe;
}

export interface ItemSeparatorProps extends Omit<SeparatorProps, "recipe"> {
  recipe?: typeof itemRecipe;
}

export function ItemGroup(props: ItemGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "variant",
    "children",
    "recipe",
    "class",
  ]);
  const variant = () => local.variant ?? "default";
  const slots = () => (local.recipe ?? itemRecipe)();

  return (
    <ItemGroupContext value={{ variant: variant() }}>
      <ark.div
        {...rest}
        class={slots().group({ class: cn(local.class) })}
        data-part="group"
        data-scope="item"
        data-variant={variant()}
        role="list"
      >
        {local.children}
      </ark.div>
    </ItemGroupContext>
  );
}

export function ItemSeparator(props: ItemSeparatorProps): JSX.Element {
  const [local, rest] = splitProps(props, ["recipe", "class"]);
  const slots = () => (local.recipe ?? itemRecipe)();

  return (
    <Separator
      {...rest}
      class={slots().separator({ class: cn(local.class) })}
      data-part="separator"
      data-scope="item"
      orientation="horizontal"
    />
  );
}
