// packages/svelte/examples/autocomplete/variants.svelte
<script lang="ts">
import { Autocomplete } from "@pisagor/svelte";

const items = [
  { label: "Apple", value: "apple" },
  { label: "Banana", value: "banana" },
  { label: "Cherry", value: "cherry" },
];
</script>

<div class="flex flex-col gap-2">
  <Autocomplete {items} placeholder="Primary" variant="primary" />
  <Autocomplete {items} placeholder="Secondary" variant="secondary" />
</div>

// packages/react/examples/autocomplete/variants.tsx
import { Autocomplete } from "@pisagor/react";

const items = [
  { label: "Apple", value: "apple" },
  { label: "Banana", value: "banana" },
  { label: "Cherry", value: "cherry" },
];

export function Variants() {
  return (
    <div className="flex flex-col gap-2">
      <Autocomplete items={items} placeholder="Primary" variant="primary" />
      <Autocomplete items={items} placeholder="Secondary" variant="secondary" />
    </div>
  );
}
