// packages/svelte/examples/field/disabled-field.svelte
<script lang="ts">
import { Field, Input } from "@pisagor/svelte";
</script>

<Field disabled>
      <Field.Label>Email</Field.Label>
      <Input disabled placeholder="Enter your email" type="email" />
      <Field.Description>
        This field is currently unavailable.
      </Field.Description>
    </Field>

// packages/react/examples/field/disabled-field.tsx
import { Input } from "@pisagor/react";
import { Field } from "@pisagor/react/field";
export function DisabledField() {
  return (
    <Field disabled>
      <Field.Label>Email</Field.Label>
      <Input disabled placeholder="Enter your email" type="email" />
      <Field.Description>
        This field is currently unavailable.
      </Field.Description>
    </Field>
  );
}
