// packages/svelte/examples/field/number-input-story.svelte
<script lang="ts">
import { Field, NumberInput } from "@pisagor/svelte";
</script>

<Field>
      <NumberInput defaultValue="50" max={100} min={1}>
        <NumberInput.Scrubber>Quantity</NumberInput.Scrubber>
        <NumberInput.Control>
          <NumberInput.DecrementTrigger />
          <NumberInput.Input />
          <NumberInput.IncrementTrigger />
        </NumberInput.Control>
      </NumberInput>
    </Field>

// packages/react/examples/field/number-input-story.tsx
import { Field, NumberInput } from "@pisagor/react";
export function NumberInputStory() {
  return (
    <Field>
      <NumberInput defaultValue="50" max={100} min={1}>
        <NumberInput.Scrubber>Quantity</NumberInput.Scrubber>
        <NumberInput.Control>
          <NumberInput.DecrementTrigger />
          <NumberInput.Input />
          <NumberInput.IncrementTrigger />
        </NumberInput.Control>
      </NumberInput>
    </Field>
  );
}
