// packages/vue/src/components/prose/examples/media.vue
<script setup lang="ts">
import { Prose } from "..";
</script>

<template>
        <Prose>
          <figure>
            <img alt="Placeholder" height="200" src="/images/placeholder.svg" width="200" />
            <figcaption>A description of the image.</figcaption>
          </figure>
        </Prose>
  
</template>

// packages/react/src/components/prose/examples/media.tsx
import { Prose } from "..";

export function Media() {
  return (
    <Prose>
      <figure>
        <img
          alt="Placeholder"
          height={200}
          src="/images/placeholder.svg"
          width={200}
        />
        <figcaption>A description of the image.</figcaption>
      </figure>
    </Prose>
  );
}
