// packages/react/src/components/announcement/examples/without-badge.tsx
import { ArrowUpRightIcon } from "@phosphor-icons/react";
import { Announcement } from "..";

export function WithoutBadge() {
  return (
    <Announcement
      title={
        <>
          New features added, check the logs for more details.
          <ArrowUpRightIcon />
        </>
      }
    />
  );
}

// packages/svelte/skills/svelte/assets/examples/announcement/without-badge.svelte
<script lang="ts">
import { Announcement } from "@pisagor/svelte/announcement";
import ArrowUpRightIcon from "phosphor-svelte/lib/ArrowUpRightIcon";
</script>

<Announcement>
  {#snippet title()}
    New features added, check the logs for more details.
    <ArrowUpRightIcon />
  {/snippet}
</Announcement>
