// packages/svelte/examples/scroll-area/horizontal.svelte
<script lang="ts">
import { ScrollArea } from "@pisagor/svelte";
</script>

<ScrollArea class="h-auto rounded-lg border">
      <div class="flex w-max gap-2 p-4">
        {#each Array.from({ length: 20 }) as _}
<div
            class="flex h-20 w-32 shrink-0 items-center justify-center rounded-md bg-muted"
          >
            <span class="font-medium text-sm">Item {i + 1}</span>
          </div>
{/each}
      </div>
    </ScrollArea>

// packages/vue/src/components/scroll-area/examples/horizontal.vue
<script lang="ts" setup>
import { ScrollArea } from "..";

const items = Array.from({ length: 10 }, (_, i) => `Item ${i + 1}`);
</script>

<template>
  <ScrollArea class="h-auto rounded-lg border">
    <div class="flex w-max gap-2 p-4">
      <div
        class="flex h-20 w-32 shrink-0 items-center justify-center rounded-md bg-muted"
        v-for="item in items"
        :key="item"
      >
        <span class="font-medium text-sm">Item {{ item }}</span>
      </div>
    </div>
  </ScrollArea>
</template>
