// packages/solid/src/components/bottom-navigation/bottom-navigation.tsx
import { ark } from "@ark-ui/solid/factory";
import {
  type TabListProps,
  Tabs as TabsPrimitive,
  type TabsRootProps,
  type TabTriggerProps,
} from "@ark-ui/solid/tabs";
import type {
  BottomNavigationItemProps as BaseBottomNavigationItemProps,
  BottomNavigationProps as BaseBottomNavigationProps,
} from "@pisagor/props";
import {
  bottomNavigationItemRecipe,
  bottomNavigationRecipe,
} from "@pisagor/recipes";
import type { ComponentProps, JSX } from "solid-js";
import { splitProps } from "solid-js";
import {
  BottomNavigationContext,
  BottomNavigationItemContext,
  useBottomNavigation,
  useBottomNavigationItem,
} from "./bottom-navigation.context";

export interface BottomNavigationRootProps
  extends TabsRootProps,
    BaseBottomNavigationProps {}

export type BottomNavigationProps = BottomNavigationRootProps;
export type BottomNavigationListProps = TabListProps;

export interface BottomNavigationItemProps
  extends TabTriggerProps,
    BaseBottomNavigationItemProps {}

export type BottomNavigationItemIconProps = ComponentProps<typeof ark.span>;
export type BottomNavigationItemLabelProps = ComponentProps<typeof ark.span>;

export function BottomNavigationRoot(
  props: BottomNavigationRootProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["recipe", "class"]);
  const slots = () => (local.recipe ?? bottomNavigationRecipe)();

  return (
    <BottomNavigationContext value={{ slots: slots() }}>
      <TabsPrimitive.Root
        {...rest}
        class={slots().base({ class: local.class })}
      />
    </BottomNavigationContext>
  );
}

export function BottomNavigationList(
  props: BottomNavigationListProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useBottomNavigation();
  return (
    <TabsPrimitive.List {...rest} class={slots.list({ class: local.class })} />
  );
}

export function BottomNavigationItem(
  props: BottomNavigationItemProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "recipe", "class"]);
  const slots = () => (local.recipe ?? bottomNavigationItemRecipe)();

  return (
    <BottomNavigationItemContext value={{ slots: slots() }}>
      <TabsPrimitive.Trigger
        {...rest}
        class={slots().base({ class: local.class })}
      >
        {local.children}
      </TabsPrimitive.Trigger>
    </BottomNavigationItemContext>
  );
}

export function BottomNavigationItemIcon(
  props: BottomNavigationItemIconProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useBottomNavigationItem();
  return (
    <ark.span
      {...rest}
      aria-hidden
      class={slots.icon({ class: local.class })}
      data-part="item-icon"
      data-scope="bottom-navigation"
    />
  );
}

export function BottomNavigationItemLabel(
  props: BottomNavigationItemLabelProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useBottomNavigationItem();
  return (
    <ark.span
      {...rest}
      class={slots.label({ class: local.class })}
      data-part="item-label"
      data-scope="bottom-navigation"
    />
  );
}

// packages/react-ui/src/components/bottom-navigation/bottom-navigation.tsx
import { ark } from "@ark-ui/react/factory";
import { Tabs as TabsPrimitive } from "@ark-ui/react/tabs";
import {
  bottomNavigationItemVariants,
  bottomNavigationVariants,
} from "@pisagor/recipes/bottom-navigation";
import type { ComponentProps } from "react";
import { useMemo } from "react";
import {
  BottomNavigationContext,
  BottomNavigationItemContext,
  useBottomNavigation,
  useBottomNavigationItem,
} from "./bottom-navigation.context";

// #region Types
export type BottomNavigationRootProps = ComponentProps<typeof TabsPrimitive.Root>;

export type BottomNavigationProps = BottomNavigationRootProps;

export type BottomNavigationListProps = ComponentProps<typeof TabsPrimitive.List>;

export type BottomNavigationItemProps = ComponentProps<typeof TabsPrimitive.Trigger>;

export type BottomNavigationItemIconProps = ComponentProps<typeof ark.span>;

export type BottomNavigationItemLabelProps = ComponentProps<typeof ark.span>;
// #endregion

// #region Parts
export function BottomNavigationRoot({ className, ...rest }: BottomNavigationRootProps) {
  const slots = useMemo(() => bottomNavigationVariants(), []);

  return (
    <BottomNavigationContext value={{ slots }}>
      <TabsPrimitive.Root {...rest} className={slots.base({ className })} />
    </BottomNavigationContext>
  );
}

export function BottomNavigationList({ className, ...rest }: BottomNavigationListProps) {
  const { slots } = useBottomNavigation();

  return <TabsPrimitive.List {...rest} className={slots.list({ className })} />;
}

export function BottomNavigationItem({ children, className, ...rest }: BottomNavigationItemProps) {
  const slots = useMemo(() => bottomNavigationItemVariants(), []);

  return (
    <BottomNavigationItemContext value={{ slots }}>
      <TabsPrimitive.Trigger {...rest} className={slots.base({ className })}>
        {children}
      </TabsPrimitive.Trigger>
    </BottomNavigationItemContext>
  );
}

export function BottomNavigationItemIcon({ className, ...rest }: BottomNavigationItemIconProps) {
  const { slots } = useBottomNavigationItem();

  return (
    <ark.span
      {...rest}
      aria-hidden
      className={slots.icon({ className })}
      data-part="item-icon"
      data-scope="bottom-navigation"
    />
  );
}

export function BottomNavigationItemLabel({ className, ...rest }: BottomNavigationItemLabelProps) {
  const { slots } = useBottomNavigationItem();

  return (
    <ark.span
      {...rest}
      className={slots.label({ className })}
      data-part="item-label"
      data-scope="bottom-navigation"
    />
  );
}
// #endregion

// #region Display Names
BottomNavigationRoot.displayName = "BottomNavigation";
BottomNavigationList.displayName = "BottomNavigation.List";
BottomNavigationItem.displayName = "BottomNavigation.Item";
BottomNavigationItemIcon.displayName = "BottomNavigation.ItemIcon";
BottomNavigationItemLabel.displayName = "BottomNavigation.ItemLabel";
// #endregion
