// packages/solid/src/components/format.tsx
import {
  type FormatByteProps,
  type FormatNumberProps,
  Format as FormatPrimitive,
  type FormatRelativeTimeProps,
} from "@ark-ui/solid/format";
import type { JSX } from "solid-js";

export function FormatByte(props: FormatByteProps): JSX.Element {
  return <FormatPrimitive.Byte {...props} />;
}

export function FormatNumber(props: FormatNumberProps): JSX.Element {
  return <FormatPrimitive.Number {...props} />;
}

export function FormatRelativeTime(
  props: FormatRelativeTimeProps,
): JSX.Element {
  return <FormatPrimitive.RelativeTime {...props} />;
}

export type {
  FormatByteProps,
  FormatNumberProps,
  FormatRelativeTimeProps,
} from "@ark-ui/solid/format";

export const Format = {
  Byte: FormatByte,
  Number: FormatNumber,
  RelativeTime: FormatRelativeTime,
};

// packages/react/src/components/format.tsx
import {
  type FormatByteProps,
  type FormatNumberProps,
  Format as FormatPrimitive,
  type FormatRelativeTimeProps,
} from "@ark-ui/react/format";

// #region Parts
export function FormatByte({ ...rest }: FormatByteProps) {
  return <FormatPrimitive.Byte {...rest} />;
}

export function FormatNumber({ ...rest }: FormatNumberProps) {
  return <FormatPrimitive.Number {...rest} />;
}

export function FormatRelativeTime({ ...rest }: FormatRelativeTimeProps) {
  return <FormatPrimitive.RelativeTime {...rest} />;
}
// #endregion

// #region Display Names
FormatByte.displayName = "Format.Byte";
FormatNumber.displayName = "Format.Number";
FormatRelativeTime.displayName = "Format.RelativeTime";

// #endregion

export type {
  FormatByteProps,
  FormatNumberProps,
  FormatRelativeTimeProps,
} from "@ark-ui/react/format";

export const Format = {
  Byte: FormatByte,
  Number: FormatNumber,
  RelativeTime: FormatRelativeTime,
};
