// packages/solid/examples/tags-input/with-combobox.tsx
/** @jsxImportSource solid-js */
import { useListCollection } from "@ark-ui/solid/collection";
import { useFilter } from "@ark-ui/solid/locale";
import { useTagsInput } from "@ark-ui/solid/tags-input";
import { Combobox, Field, TagsInput } from "@pisagor/solid";
import { createMemo, createUniqueId, For } from "solid-js";

export function WithCombobox() {
  const frameworkItems = [
    "React",
    "Solid",
    "Vue",
    "Svelte",
    "Angular",
    "Preact",
    "Next.js",
    "Astro",
  ];
  const uid = createUniqueId();

  const { contains } = useFilter({ sensitivity: "base" });
  const { collection, filter } = useListCollection({
    filter: contains,
    initialItems: frameworkItems,
  });

  const tagsInput = useTagsInput({
    ids: { control: `tags-control-${uid}`, input: `tags-input-${uid}` },
  });

  const availableItems = createMemo(() =>
    collection().items.filter((item) => !tagsInput().value.includes(item)),
  );

  return (
    <Field>
      <Field.Label for={`tags-input-${uid}`}>Frameworks</Field.Label>
      <Combobox.Root
        allowCustomValue
        collection={collection()}
        ids={{ control: `tags-control-${uid}`, input: `tags-input-${uid}` }}
        onInputValueChange={({ inputValue }) => filter(inputValue)}
        onValueChange={(value) => {
          const next = value[0];
          if (next && !tagsInput().value.includes(next)) {
            tagsInput().addValue(next);
          }
        }}
        selectionBehavior="clear"
        value={[]}
      >
        <TagsInput.RootProvider class="w-full" value={tagsInput}>
          <TagsInput.Context>
            {(api) => (
              <>
                <For each={api().value}>
                  {(tag, index) => (
                    <TagsInput.Item index={index()} value={tag}>
                      {tag}
                    </TagsInput.Item>
                  )}
                </For>
                <Combobox.FieldInput
                  asChild={(props) => (
                    <TagsInput.Input
                      {...props()}
                      placeholder="Search framework"
                    />
                  )}
                />
              </>
            )}
          </TagsInput.Context>
        </TagsInput.RootProvider>
        <Combobox.Content>
          <Combobox.List>
            <Combobox.Empty>
              No frameworks found. Try a different search.
            </Combobox.Empty>
            <For each={availableItems()}>
              {(item) => <Combobox.Item item={item}>{item}</Combobox.Item>}
            </For>
          </Combobox.List>
        </Combobox.Content>
      </Combobox.Root>
    </Field>
  );
}

// packages/react/examples/tags-input/with-combobox.tsx
import { useFilter, useListCollection } from "@ark-ui/react";
import { useTagsInput } from "@ark-ui/react/tags-input";
import { Combobox, Field, TagsInput } from "@pisagor/react";
import { useId } from "react";
export function WithCombobox() {
  const frameworkItems = [
    "React",
    "Solid",
    "Vue",
    "Svelte",
    "Angular",
    "Preact",
    "Next.js",
    "Astro",
  ];
  const uid = useId();

  const { contains } = useFilter({ sensitivity: "base" });
  const { collection, filter } = useListCollection({
    filter: contains,
    initialItems: frameworkItems,
  });

  const tagsInput = useTagsInput({
    ids: { control: `tags-control-${uid}`, input: `tags-input-${uid}` },
  });

  const availableItems = collection.items.filter(
    (item) => !tagsInput.value.includes(item),
  );

  return (
    <Field>
      <Field.Label htmlFor={`tags-input-${uid}`}>Frameworks</Field.Label>
      <Combobox.Root
        allowCustomValue
        collection={collection}
        ids={{ control: `tags-control-${uid}`, input: `tags-input-${uid}` }}
        onInputValueChange={({ inputValue }) => filter(inputValue)}
        onValueChange={(value) => {
          const next = value[0];
          if (next && !tagsInput.value.includes(next)) {
            tagsInput.addValue(next);
          }
        }}
        selectionBehavior="clear"
        value={[]}
      >
        <TagsInput.RootProvider className="w-full" value={tagsInput}>
          <TagsInput.Context>
            {({ value }) => (
              <>
                {value.map((tag, index) => (
                  <TagsInput.Item index={index} key={tag} value={tag}>
                    {tag}
                  </TagsInput.Item>
                ))}
                <Combobox.FieldInput asChild>
                  <TagsInput.Input placeholder="Search framework" />
                </Combobox.FieldInput>
              </>
            )}
          </TagsInput.Context>
        </TagsInput.RootProvider>
        <Combobox.Content>
          <Combobox.List>
            <Combobox.Empty>
              No frameworks found. Try a different search.
            </Combobox.Empty>
            {availableItems.map((item) => (
              <Combobox.Item item={item} key={item}>
                {item}
              </Combobox.Item>
            ))}
          </Combobox.List>
        </Combobox.Content>
      </Combobox.Root>
    </Field>
  );
}
