// packages/solid/src/components/checkbox/checkbox.tsx
import {
  type CheckboxIndicatorProps,
  Checkbox as CheckboxPrimitive,
  type CheckboxGroupProps as CheckboxPrimitiveGroupProps,
  type CheckboxRootProps,
} from "@ark-ui/solid/checkbox";
import { checkboxGroupRecipe, checkboxRecipe } from "@pisagor/recipes/checkbox";
import { formControlToggleRecipe } from "@pisagor/recipes/form-control";
import { cn } from "@pisagor/utils";
import type { JSX } from "solid-js";
import { splitProps } from "solid-js";
import { useFormControlSurface } from "../surface/use-form-control-surface";

type FormControlVariant = "primary" | "secondary";

export interface CheckboxGroupProps
  extends Omit<CheckboxPrimitiveGroupProps, "onValueChange"> {
  onValueChange?: (value: string[]) => void;
  recipe?: typeof checkboxGroupRecipe;
}

export interface CheckboxProps extends CheckboxRootProps {
  variant?: FormControlVariant;
  onValueChange?: (value: boolean) => void;
  recipe?: typeof checkboxRecipe;
}

type CheckboxIndicatorPartProps = CheckboxIndicatorProps & {
  recipe?: typeof checkboxRecipe;
};

function CheckIcon() {
  return (
    <svg
      aria-hidden="true"
      fill="none"
      height="1em"
      viewBox="0 0 256 256"
      width="1em"
    >
      <path
        d="M229.66,77.66l-128,128a8,8,0,0,1-11.32,0l-56-56a8,8,0,0,1,11.32-11.32L96,188.69,218.34,66.34a8,8,0,0,1,11.32,11.32Z"
        fill="currentColor"
      />
    </svg>
  );
}

function MinusIcon() {
  return (
    <svg
      aria-hidden="true"
      fill="none"
      height="1em"
      viewBox="0 0 256 256"
      width="1em"
    >
      <path
        d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128Z"
        fill="currentColor"
      />
    </svg>
  );
}

export function CheckboxGroup(props: CheckboxGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, ["onValueChange", "recipe", "class"]);

  return (
    <CheckboxPrimitive.Group
      {...rest}
      class={(local.recipe ?? checkboxGroupRecipe)({ class: cn(local.class) })}
      onValueChange={local.onValueChange}
    />
  );
}

export function CheckboxRoot(props: CheckboxProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "variant",
    "tabIndex",
    "onCheckedChange",
    "onValueChange",
    "recipe",
    "class",
  ]);
  const surfaceVariant = useFormControlSurface();
  const variant = () => local.variant ?? ("primary" as FormControlVariant);
  const recipeFn = () => local.recipe ?? checkboxRecipe;
  const slots = () => recipeFn()();

  return (
    <CheckboxPrimitive.Root
      {...rest}
      class={cn(
        formControlToggleRecipe({
          size: "md",
          surfaceVariant,
          variant: variant(),
        }),
        slots().base({ class: cn(local.class) }),
      )}
      data-variant={variant()}
      onCheckedChange={
        local.onCheckedChange || local.onValueChange
          ? (details) => {
              local.onCheckedChange?.(details);
              local.onValueChange?.(details.checked === true);
            }
          : undefined
      }
      role="checkbox"
    >
      <CheckboxPrimitive.Control>
        <CheckboxIndicator recipe={recipeFn()}>
          <CheckIcon />
        </CheckboxIndicator>
        <CheckboxIndicator indeterminate recipe={recipeFn()}>
          <MinusIcon />
        </CheckboxIndicator>
      </CheckboxPrimitive.Control>
      <CheckboxPrimitive.HiddenInput tabIndex={local.tabIndex} />
    </CheckboxPrimitive.Root>
  );
}

function CheckboxIndicator(props: CheckboxIndicatorPartProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class", "recipe"]);
  const slots = () => (local.recipe ?? checkboxRecipe)();

  return (
    <CheckboxPrimitive.Indicator
      {...rest}
      class={slots().indicator({ class: cn(local.class) })}
    />
  );
}

// packages/react/src/components/checkbox/checkbox.tsx
import {
  type CheckboxIndicatorProps,
  Checkbox as CheckboxPrimitive,
  type CheckboxGroupProps as CheckboxPrimitiveGroupProps,
  type CheckboxRootProps,
} from "@ark-ui/react/checkbox";
import { CheckIcon, MinusIcon } from "@phosphor-icons/react";
import { checkboxGroupRecipe, checkboxRecipe } from "@pisagor/recipes/checkbox";
import { formControlToggleRecipe } from "@pisagor/recipes/form-control";

import { cn } from "@pisagor/utils";
import { useFormControlSurface } from "../surface/use-form-control-surface";

// #region Types
type FormControlVariant = "primary" | "secondary";

export interface CheckboxGroupProps extends Omit<CheckboxPrimitiveGroupProps, "onValueChange"> {
  onValueChange?: (value: string[]) => void;
  /**
   * Style recipe. Defaults to `checkboxGroupRecipe` from `@pisagor/recipes/checkbox`.
   *
   * @defaultValue checkboxGroupRecipe
   */
  recipe?: typeof checkboxGroupRecipe;
}

export interface CheckboxProps extends CheckboxRootProps {
  /** Visual shell variant. Defaults to `primary`. */
  variant?: FormControlVariant;
  onValueChange?: (value: boolean) => void;
  /**
   * Style recipe. Defaults to `checkboxRecipe` from `@pisagor/recipes/checkbox`.
   *
   * @defaultValue checkboxRecipe
   */
  recipe?: typeof checkboxRecipe;
}

type CheckboxIndicatorPartProps = CheckboxIndicatorProps & {
  recipe?: typeof checkboxRecipe;
};

// #endregion

// #region Parts
export function CheckboxGroup({
  onValueChange,
  recipe = checkboxGroupRecipe,
  className,
  ...rest
}: CheckboxGroupProps) {
  return (
    <CheckboxPrimitive.Group
      {...rest}
      className={recipe({ className })}
      onValueChange={onValueChange}
    />
  );
}

export function CheckboxRoot({
  variant: variantProp,
  tabIndex,
  onCheckedChange,
  onValueChange,
  recipe = checkboxRecipe,
  className,
  ...rest
}: CheckboxProps) {
  const resolved = {
    surfaceVariant: useFormControlSurface(),
    variant: variantProp ?? ("primary" as FormControlVariant),
  };
  const shellArgs = {
    surfaceVariant: resolved.surfaceVariant,
    variant: resolved.variant,
  };
  const controlProps = { "data-variant": resolved.variant };
  const slots = recipe();

  const handleCheckedChange =
    onCheckedChange || onValueChange
      ? (details: Parameters<NonNullable<CheckboxProps["onCheckedChange"]>>[0]) => {
          onCheckedChange?.(details);
          onValueChange?.(details.checked === true);
        }
      : undefined;

  return (
    <CheckboxPrimitive.Root
      {...rest}
      {...controlProps}
      className={cn(
        formControlToggleRecipe({ size: "md", ...shellArgs }),
        slots.base({ className }),
      )}
      onCheckedChange={handleCheckedChange}
      role="checkbox"
    >
      <CheckboxPrimitive.Control>
        <CheckboxIndicator recipe={recipe}>
          <CheckIcon />
        </CheckboxIndicator>

        <CheckboxIndicator indeterminate recipe={recipe}>
          <MinusIcon />
        </CheckboxIndicator>
      </CheckboxPrimitive.Control>

      <CheckboxPrimitive.HiddenInput tabIndex={tabIndex} />
    </CheckboxPrimitive.Root>
  );
}

function CheckboxIndicator({
  className,
  recipe = checkboxRecipe,
  ...rest
}: CheckboxIndicatorPartProps) {
  const slots = recipe();

  return <CheckboxPrimitive.Indicator {...rest} className={slots.indicator({ className })} />;
}
// #endregion

// #region Display Names
CheckboxGroup.displayName = "Checkbox.Group";
CheckboxRoot.displayName = "Checkbox";
CheckboxIndicator.displayName = "Checkbox.Indicator";
// #endregion
