// packages/react/src/components/announcement/examples/with-link.tsx
import { ArrowUpRightIcon } from "@phosphor-icons/react";
import { Badge } from "@pisagor/react";
import { Announcement } from "..";
export function WithLink() {
  return (
    <Announcement.Root asChild>
      <a href="/">
        <Badge>Latest update</Badge>
        <Announcement.Title>
          New feature added
          <ArrowUpRightIcon aria-hidden />
        </Announcement.Title>
      </a>
    </Announcement.Root>
  );
}

// packages/svelte/examples/announcement/with-link.svelte
<script lang="ts">
import { Announcement, Badge } from "@pisagor/svelte";
import ArrowUpRightIcon from "phosphor-svelte/lib/ArrowUpRightIcon";
</script>

<Announcement.Root>
  {#snippet asChild(props)}
    <a {...props()} href="/">
      <Badge>Latest update</Badge>
      <Announcement.Title>
        New feature added
        <ArrowUpRightIcon aria-hidden />
      </Announcement.Title>
    </a>
  {/snippet}
</Announcement.Root>
