// packages/react/examples/file-upload/directory-upload.tsx
import { FolderIcon } from "@phosphor-icons/react";
import { Button, FileUpload } from "@pisagor/react";
export function DirectoryUpload() {
  return (
    <FileUpload directory>
      <div className="flex justify-center">
        <FileUpload.Trigger asChild>
          <Button size="sm" variant="outline">
            <FolderIcon />
            Select folder
          </Button>
        </FileUpload.Trigger>
        <FileUpload.List />
      </div>
    </FileUpload>
  );
}

// packages/vue/src/components/file-upload/examples/directory-upload.vue
<script lang="ts" setup >
import { PhFolder } from "@phosphor-icons/vue";
import { Button } from "@pisagor/vue";
import { FileUpload } from "..";
</script>

<template>
        <FileUpload directory>
          <div class="flex justify-center">
            <FileUpload.Trigger as-child>
              <Button size="sm" variant="outline">
                <PhFolder />
                Select folder
              </Button>
            </FileUpload.Trigger>
            <FileUpload.List />
          </div>
        </FileUpload>
  
</template>
