// packages/vue/examples/carousel/controlled.vue
<script lang="ts" setup>
import { Carousel } from "@pisagor/vue";
import { ref } from "vue";
import { numberedSlides } from "./helpers";

const slides = numberedSlides(8);
const page = ref(0);
</script>

<template>
  <div class="flex flex-col gap-2">
    <Carousel v-model:page="page" :slides="slides" />
    <p class="text-center text-muted-foreground text-sm">
      Current page: {{ page + 1 }} of 5
    </p>
  </div>
</template>

// packages/svelte/examples/carousel/controlled.svelte
<script lang="ts">
import { Carousel } from "@pisagor/svelte/carousel";
import { numberedSlides } from "./helpers";

let page = $state(0);

const slides = numberedSlides(8);
</script>

<div class="flex flex-col gap-2">
  <Carousel
    onPageChange={(d) => {
      page = d.page;
    }}
    {page}
    {slides}
  />
  <p class="text-center text-muted-foreground text-sm">
    Current page: {page + 1} of 5
  </p>
</div>
