// packages/react/src/components/file-upload/examples/media-capture.tsx
import { CameraIcon } from "@phosphor-icons/react";
import { Button } from "@pisagor/react";
import { FileUpload } from "..";
export function MediaCapture() {
  return (
    <FileUpload capture="environment">
      <div className="flex justify-center">
        <FileUpload.Trigger asChild>
          <Button variant="outline">
            <CameraIcon />
            Take a picture
          </Button>
        </FileUpload.Trigger>
      </div>
      <FileUpload.List />
    </FileUpload>
  );
}

// packages/svelte/examples/file-upload/media-capture.svelte
<script lang="ts">
import { Button, FileUpload } from "@pisagor/svelte";
import CameraIcon from "phosphor-svelte/lib/CameraIcon";
</script>

<FileUpload capture="environment">
  <div class="flex justify-center">
    <FileUpload.Trigger>
      {#snippet asChild(props)}
        <Button {...props()} variant="outline">
          <CameraIcon />
          Take a picture
        </Button>
      {/snippet}
    </FileUpload.Trigger>
  </div>
  <FileUpload.List />
</FileUpload>
