// packages/vue/src/components/toggle-group/examples/vertical.vue
<script setup lang="ts">
import { PhTextB, PhTextItalic, PhTextUnderline } from "@phosphor-icons/vue";
import { ToggleGroup } from "..";
</script>

<template>
        <ToggleGroup.Root :default-value="['bold']" orientation="vertical" variant="outline">
          <ToggleGroup.Item aria-label="Toggle bold" value="bold">
            <PhTextB />
          </ToggleGroup.Item>
          <ToggleGroup.Item aria-label="Toggle italic" value="italic">
            <PhTextItalic />
          </ToggleGroup.Item>
          <ToggleGroup.Item aria-label="Toggle underline" value="underline">
            <PhTextUnderline />
          </ToggleGroup.Item>
        </ToggleGroup.Root>
  
</template>

// packages/react/src/components/toggle-group/examples/vertical.tsx
import {
  TextBIcon,
  TextItalicIcon,
  TextUnderlineIcon,
} from "@phosphor-icons/react";
import { ToggleGroup } from "..";

export function Vertical() {
  return (
    <ToggleGroup.Root
      defaultValue={["bold"]}
      orientation="vertical"
      variant="outline"
    >
      <ToggleGroup.Item aria-label="Toggle bold" value="bold">
        <TextBIcon />
      </ToggleGroup.Item>
      <ToggleGroup.Item aria-label="Toggle italic" value="italic">
        <TextItalicIcon />
      </ToggleGroup.Item>
      <ToggleGroup.Item aria-label="Toggle underline" value="underline">
        <TextUnderlineIcon />
      </ToggleGroup.Item>
    </ToggleGroup.Root>
  );
}
