// packages/vue/examples/kbd/with-button.vue
<script lang="ts" setup>
import { PhFloppyDisk } from "@phosphor-icons/vue";
import { Button, Kbd } from "@pisagor/vue";
</script>

<template>
  <Button variant="outline">
    <PhFloppyDisk />
    Save
    <Kbd.Group class="translate-x-0.5">
      <Kbd variant="outline">Ctrl+S</Kbd>
    </Kbd.Group>
  </Button>
</template>

// packages/react/examples/kbd/with-button.tsx
import { FloppyDiskIcon } from "@phosphor-icons/react";
import { Button } from "@pisagor/react";
import { Kbd } from "@pisagor/react/kbd";
export function WithButton() {
  return (
    <Button variant="outline">
      <FloppyDiskIcon />
      Save
      <Kbd.Group className="translate-x-0.5">
        <Kbd variant="outline">Ctrl+S</Kbd>
      </Kbd.Group>
    </Button>
  );
}
