// packages/svelte/examples/kbd/with-button.svelte
<script lang="ts">
import { Button, Kbd } from "@pisagor/svelte";
import FloppyDiskIcon from "phosphor-svelte/lib/FloppyDiskIcon";
</script>

<Button variant="outline">
  <FloppyDiskIcon />
  Save
  <Kbd.Group class="translate-x-0.5">
    <Kbd variant="outline">Ctrl+S</Kbd>
  </Kbd.Group>
</Button>

// packages/react/src/components/kbd/examples/with-button.tsx
import { FloppyDiskIcon } from "@phosphor-icons/react";
import { Button } from "@pisagor/react";
import { Kbd } from "..";
export function WithButton() {
  return (
    <Button variant="outline">
      <FloppyDiskIcon />
      Save
      <Kbd.Group className="translate-x-0.5">
        <Kbd variant="outline">Ctrl+S</Kbd>
      </Kbd.Group>
    </Button>
  );
}
