// packages/react/src/components/announcement/announcement.tsx
import { ark } from "@ark-ui/react/factory";
import type { AnnouncementProps as AnnouncementRootSharedProps } from "@pisagor/props";
import { announcementRecipe } from "@pisagor/recipes";
import type { ComponentProps, ReactNode } from "react";
import { AnnouncementContext, useAnnouncement } from "./announcement.context";

// #region Types
type AnnouncementTitleProps = ComponentProps<typeof ark.span>;

type AnnouncementRootProps = Omit<ComponentProps<typeof ark.div>, "title"> & {
  /**
   * The ARIA role of the announcement.
   *
   * @defaultValue "status"
   */
  role?: "status" | "alert";
} & AnnouncementRootSharedProps;

export interface AnnouncementProps
  extends Omit<AnnouncementRootProps, "children"> {
  /** Optional badge or label rendered before the title. */
  badge?: ReactNode;
  /** Title content rendered inside `Announcement.Title`. */
  title?: ReactNode;
  /** Extra props forwarded to the announcement title element */
  titleProps?: Omit<AnnouncementTitleProps, "children" | "className">;
}
// #endregion

// #region Parts
export function AnnouncementRoot({
  role = "status",
  children,
  recipe = announcementRecipe,
  className,
  ...rest
}: AnnouncementRootProps) {
  const slots = recipe();

  return (
    <AnnouncementContext value={{ slots }}>
      <ark.div
        {...rest}
        className={slots.base({ className })}
        data-part="root"
        data-scope="announcement"
        role={role}
      >
        {" "}
        {children}
      </ark.div>
    </AnnouncementContext>
  );
}

export function AnnouncementTitle({
  className,
  ...rest
}: AnnouncementTitleProps) {
  const { slots } = useAnnouncement();

  return (
    <ark.span
      {...rest}
      className={slots.title({ className })}
      data-part="title"
      data-scope="announcement"
    />
  );
}
// #endregion

// #region Shorthand
export function AnnouncementShorthand({
  badge,
  title,
  titleProps,
  ...rest
}: AnnouncementProps) {
  return (
    <AnnouncementRoot {...rest}>
      {" "}
      {badge}
      {title !== undefined && (
        <AnnouncementTitle {...titleProps}>{title}</AnnouncementTitle>
      )}
    </AnnouncementRoot>
  );
}
// #endregion

// #region Display Names
AnnouncementRoot.displayName = "Announcement.Root";
AnnouncementTitle.displayName = "Announcement.Title";
AnnouncementShorthand.displayName = "Announcement";
// #endregion

// packages/solid/src/components/announcement.tsx
import { ark } from "@ark-ui/solid/factory";
import type { AnnouncementProps as BaseAnnouncementRootProps } from "@pisagor/props";
import { announcementRecipe } from "@pisagor/recipes";
import type { Component, ComponentProps, JSX } from "solid-js";
import { Show, splitProps } from "solid-js";
import { createSlotRecipeContext } from "../internal/create-slot-recipe-context";

// #region Context
const { withContext, withProvider } = createSlotRecipeContext({
  name: "Announcement",
  recipe: announcementRecipe,
});
// #endregion

// #region Types
export type AnnouncementRootProps = Omit<
  ComponentProps<typeof ark.div>,
  "title"
> &
  BaseAnnouncementRootProps & {
    role?: "status" | "alert";
  };

export type AnnouncementTitleProps = ComponentProps<typeof ark.span>;

export interface AnnouncementProps
  extends Omit<AnnouncementRootProps, "children"> {
  /** Optional badge or label rendered before the title. */
  badge?: JSX.Element;
  /** Title content rendered inside `Announcement.Title`. */
  title?: JSX.Element;
  /** Extra props forwarded to the announcement title element */
  titleProps?: Omit<AnnouncementTitleProps, "children" | "class">;
}
// #endregion

// #region Parts
export const AnnouncementRoot: Component<AnnouncementRootProps> = withProvider(
  ark.div,
  {
    defaultProps: { role: "status" },
    name: "Root",
    slot: "base",
  },
);

export const AnnouncementTitle = withContext(ark.span, { name: "Title" });
// #endregion

// #region Shorthand
export function AnnouncementShorthand(props: AnnouncementProps): JSX.Element {
  const [local, rest] = splitProps(props, ["badge", "title", "titleProps"]);

  return (
    <AnnouncementRoot {...rest}>
      {local.badge}
      <Show when={local.title !== undefined}>
        <AnnouncementTitle {...local.titleProps}>
          {local.title}
        </AnnouncementTitle>
      </Show>
    </AnnouncementRoot>
  );
}
// #endregion

export const Announcement = Object.assign(AnnouncementShorthand, {
  Root: AnnouncementRoot,
  Title: AnnouncementTitle,
});
