// packages/react/src/components/combobox.tsx
import {
  type CollectionItem,
  createListCollection,
} from "@ark-ui/react/collection";
import type {
  ComboboxClearTriggerProps,
  ComboboxControlProps,
  ComboboxEmptyProps,
  ComboboxItemGroupLabelProps,
  ComboboxListProps,
  ComboboxPositionerProps,
  ComboboxContentProps as ComboboxPrimitiveContentProps,
  ComboboxInputProps as ComboboxPrimitiveInputProps,
  ComboboxItemGroupProps as ComboboxPrimitiveItemGroupProps,
  ComboboxItemProps as ComboboxPrimitiveItemProps,
  ComboboxRootProps as ComboboxPrimitiveRootProps,
  ComboboxTriggerProps,
} from "@ark-ui/react/combobox";
import {
  Combobox as ComboboxPrimitive,
  useComboboxContext,
} from "@ark-ui/react/combobox";
import { Portal } from "@ark-ui/react/portal";
import { CaretUpDownIcon, CheckIcon, XIcon } from "@phosphor-icons/react";
import type { ComboboxProps as BaseComboboxRootProps } from "@pisagor/props";
import {
  type ComboboxVariantProps,
  comboboxRecipe,
  type InputRootVariantProps,
} from "@pisagor/recipes";

import type { ReactNode } from "react";
import { createContext, use } from "react";
import { createSlotRecipeContext } from "../internal/create-slot-recipe-context";
import { Button } from "./button";
import { InputGroup } from "./input-group";

// #region Context
const { Context: ComboboxStylesContext } = createSlotRecipeContext({
  name: "Combobox",
  recipe: comboboxRecipe,
});

function useComboboxSlots() {
  const styles = use(ComboboxStylesContext);
  return styles?.slots ?? comboboxRecipe();
}

/** Root-level control props (`variant`, `size`) read by `Combobox.Input`. */
const ComboboxControlContext = createContext<InputRootVariantProps>({});
ComboboxControlContext.displayName = "ComboboxControlContext";

/** @deprecated Prefer composing within Combobox.Root; kept for public API. */
export function useComboboxRoot() {
  const styles = use(ComboboxStylesContext);
  return styles ? { slots: styles.slots } : undefined;
}
// #endregion

// #region Types
type FormControlVariant = "primary" | "secondary";

interface ComboboxPresetItem {
  label: string;
  value: string;
}

export type ComboboxRootProps<T extends CollectionItem = CollectionItem> = Omit<
  ComboboxPrimitiveRootProps<T>,
  "onValueChange"
> & {
  /** Visual shell variant applied to the input. Defaults to `primary`. */
  variant?: FormControlVariant;
  /** Input size. Defaults to `md`. */
  size?: InputRootVariantProps["size"];
  onValueChange?: (value: string[]) => void;
} & BaseComboboxRootProps;

export interface ComboboxProps
  extends Omit<ComboboxRootProps, "children" | "collection"> {
  /**
   * Whether to show a clear button when the input has a value.
   *
   * @defaultValue false
   */
  clearable?: boolean;
  items?: Array<ComboboxPresetItem | string>;
}

export interface ComboboxInputProps
  extends Omit<ComboboxPrimitiveInputProps, "size">,
    InputRootVariantProps {
  /**
   * Whether to show a clear button when the input has a value.
   *
   * @defaultValue false
   */
  clearable?: boolean;
  /**
   * Whether the control is disabled.
   *
   * @defaultValue false
   */
  disabled?: boolean;
  /**
   * Whether to show the trigger button.
   *
   * @defaultValue true
   */
  showTrigger?: boolean;
}

export interface ComboboxItemGroupProps
  extends ComboboxPrimitiveItemGroupProps {
  /** The heading of the group */
  heading?: string | ReactNode;
}

export interface ComboboxItemProps
  extends ComboboxPrimitiveItemProps,
    ComboboxVariantProps {}

export type ComboboxFieldInputProps = ComboboxPrimitiveInputProps;

export interface ComboboxContentProps extends ComboboxPrimitiveContentProps {
  /**
   * Whether to render the content in a portal with a positioner.
   *
   * @defaultValue true
   */
  portalled?: boolean;
}

// #endregion

// #region Parts
export function ComboboxRoot<T extends CollectionItem = CollectionItem>({
  openOnClick = true,
  children,
  onValueChange,
  variant,
  size,
  recipe = comboboxRecipe,
  ...rest
}: ComboboxRootProps<T>) {
  const slots = recipe();

  return (
    <ComboboxStylesContext value={{ slots, variants: {} as never }}>
      <ComboboxControlContext value={{ size, variant }}>
        <ComboboxPrimitive.Root
          {...rest}
          onValueChange={
            onValueChange
              ? (details) => onValueChange(details.value)
              : undefined
          }
          openOnClick={openOnClick}
        >
          {children}
        </ComboboxPrimitive.Root>
      </ComboboxControlContext>
    </ComboboxStylesContext>
  );
}

export const ComboboxContext = ComboboxPrimitive.Context;

export function ComboboxControl({ className, ...rest }: ComboboxControlProps) {
  const slots = useComboboxSlots();

  return (
    <ComboboxPrimitive.Control
      {...rest}
      className={slots.control({ className })}
    />
  );
}

export function ComboboxInput({
  size: sizeProp,
  variant: variantProp,
  clearable = false,
  showTrigger = true,
  children,
  className,
  ...rest
}: ComboboxInputProps) {
  const { inputValue } = useComboboxContext();
  const slots = useComboboxSlots();
  const control = use(ComboboxControlContext);
  const size = sizeProp ?? control.size ?? "md";
  const variant = variantProp ?? control.variant;

  return (
    <ComboboxControl data-size={size}>
      <InputGroup className={className} size={size} variant={variant}>
        {children}
        <ComboboxPrimitive.Input asChild>
          <InputGroup.Input {...rest} />
        </ComboboxPrimitive.Input>
        <InputGroup.Addon align="inline-end">
          {showTrigger && (
            <InputGroup.Button
              asChild
              className={slots.triggerHidden()}
              size="icon-xs"
              variant="ghost"
            >
              <ComboboxTrigger />
            </InputGroup.Button>
          )}
          {clearable && inputValue && (
            <ComboboxClearTrigger asChild>
              <InputGroup.Button
                aria-label="Clear"
                size="icon-xs"
                variant="ghost"
              >
                <XIcon aria-hidden />
              </InputGroup.Button>
            </ComboboxClearTrigger>
          )}
        </InputGroup.Addon>
      </InputGroup>
    </ComboboxControl>
  );
}

export function ComboboxTrigger({
  children,
  className,
  ...rest
}: ComboboxTriggerProps) {
  const slots = useComboboxSlots();

  return (
    <ComboboxPrimitive.Trigger
      {...rest}
      asChild
      className={slots.trigger({ className })}
    >
      {children ?? (
        <Button
          aria-label="Toggle"
          className={slots.triggerButton()}
          variant="ghost"
        >
          <CaretUpDownIcon aria-hidden />
        </Button>
      )}
    </ComboboxPrimitive.Trigger>
  );
}

export function ComboboxClearTrigger({
  "aria-label": ariaLabel = "Clear selected value(s)",
  ...rest
}: ComboboxClearTriggerProps) {
  return <ComboboxPrimitive.ClearTrigger {...rest} aria-label={ariaLabel} />;
}

/** Composable combobox input for custom controls (e.g. Tags Input). */
export function ComboboxFieldInput(props: ComboboxFieldInputProps) {
  return <ComboboxPrimitive.Input {...props} />;
}

export function ComboboxPositioner(props: ComboboxPositionerProps) {
  return <ComboboxPrimitive.Positioner {...props} />;
}

export function ComboboxContent({
  portalled = true,
  children,
  className,
  ...rest
}: ComboboxContentProps) {
  const slots = useComboboxSlots();

  const content = (
    <ComboboxPrimitive.Content
      {...rest}
      className={slots.content({ className })}
    >
      {children}
    </ComboboxPrimitive.Content>
  );

  if (!portalled) {
    return content;
  }

  return (
    <Portal>
      <ComboboxPositioner>{content}</ComboboxPositioner>
    </Portal>
  );
}

export function ComboboxItemGroup({
  children,
  heading,
  ...rest
}: ComboboxItemGroupProps) {
  return (
    <ComboboxPrimitive.ItemGroup {...rest}>
      {!!heading && <ComboboxItemGroupLabel>{heading}</ComboboxItemGroupLabel>}

      {children}
    </ComboboxPrimitive.ItemGroup>
  );
}

export function ComboboxItemGroupLabel({
  className,
  ...rest
}: ComboboxItemGroupLabelProps) {
  const slots = useComboboxSlots();

  return (
    <ComboboxPrimitive.ItemGroupLabel
      {...rest}
      className={slots.itemGroupLabel({ className })}
    />
  );
}

export function ComboboxItem({
  showIndicator = true,
  children,
  className,
  ...rest
}: ComboboxItemProps) {
  const slots = useComboboxSlots();

  return (
    <ComboboxPrimitive.Item
      {...rest}
      className={slots.item({ className, showIndicator })}
      persistFocus
    >
      {children}

      {showIndicator ? (
        <span className={slots.itemIndicator()}>
          <ComboboxPrimitive.ItemIndicator>
            <CheckIcon />
          </ComboboxPrimitive.ItemIndicator>
        </span>
      ) : null}
    </ComboboxPrimitive.Item>
  );
}

export function ComboboxEmpty({
  children,
  className,
  ...rest
}: ComboboxEmptyProps) {
  const slots = useComboboxSlots();

  return (
    <ComboboxPrimitive.Empty {...rest} className={slots.empty({ className })}>
      {children || "No results found. Try a different search."}
    </ComboboxPrimitive.Empty>
  );
}

export function ComboboxList({ className, ...rest }: ComboboxListProps) {
  const slots = useComboboxSlots();

  return (
    <ComboboxPrimitive.List {...rest} className={slots.list({ className })} />
  );
}
// #endregion

// #region Shorthand
export function ComboboxShorthand({
  clearable = false,
  items = [],
  id,
  ...rest
}: ComboboxProps) {
  const normalized = items.map((item) =>
    typeof item === "string" ? { label: item, value: item } : item,
  );
  const collection = createListCollection({ items: normalized });

  return (
    <ComboboxRoot {...rest} collection={collection}>
      <ComboboxInput clearable={clearable} id={id} />
      <ComboboxContent>
        <ComboboxList>
          {normalized.map((item) => (
            <ComboboxItem item={item} key={item.value}>
              {item.label}
            </ComboboxItem>
          ))}
        </ComboboxList>
      </ComboboxContent>
    </ComboboxRoot>
  );
}
// #endregion

// #region Display Names
ComboboxRoot.displayName = "Combobox.Root";
ComboboxControl.displayName = "Combobox.Control";
ComboboxInput.displayName = "Combobox.Input";
ComboboxTrigger.displayName = "Combobox.Trigger";
ComboboxClearTrigger.displayName = "Combobox.ClearTrigger";
ComboboxFieldInput.displayName = "Combobox.FieldInput";
ComboboxPositioner.displayName = "Combobox.Positioner";
ComboboxContent.displayName = "Combobox.Content";
ComboboxItemGroup.displayName = "Combobox.ItemGroup";
ComboboxItemGroupLabel.displayName = "Combobox.ItemGroupLabel";
ComboboxItem.displayName = "Combobox.Item";
ComboboxEmpty.displayName = "Combobox.Empty";
ComboboxList.displayName = "Combobox.List";
ComboboxShorthand.displayName = "Combobox";

// #endregion

export type {
  ComboboxClearTriggerProps,
  ComboboxControlProps,
  ComboboxEmptyProps,
  ComboboxItemGroupLabelProps,
  ComboboxListProps,
  ComboboxPositionerProps,
  ComboboxTriggerProps,
} from "@ark-ui/react/combobox";

export const Combobox = Object.assign(ComboboxShorthand, {
  ClearTrigger: ComboboxClearTrigger,
  Content: ComboboxContent,
  Context: ComboboxContext,
  Control: ComboboxControl,
  Empty: ComboboxEmpty,
  FieldInput: ComboboxFieldInput,
  Input: ComboboxInput,
  Item: ComboboxItem,
  ItemGroup: ComboboxItemGroup,
  ItemGroupLabel: ComboboxItemGroupLabel,
  List: ComboboxList,
  Positioner: ComboboxPositioner,
  Root: ComboboxRoot,
  Trigger: ComboboxTrigger,
});

// packages/solid/src/components/combobox.tsx
import {
  type CollectionItem,
  createListCollection,
} from "@ark-ui/solid/collection";
import type {
  ComboboxClearTriggerProps,
  ComboboxControlProps,
  ComboboxEmptyProps,
  ComboboxItemGroupLabelProps,
  ComboboxListProps,
  ComboboxPositionerProps,
  ComboboxContentProps as ComboboxPrimitiveContentProps,
  ComboboxInputProps as ComboboxPrimitiveInputProps,
  ComboboxItemGroupProps as ComboboxPrimitiveItemGroupProps,
  ComboboxItemProps as ComboboxPrimitiveItemProps,
  ComboboxRootProps as ComboboxPrimitiveRootProps,
  ComboboxTriggerProps,
} from "@ark-ui/solid/combobox";
import {
  Combobox as ComboboxPrimitive,
  useComboboxContext,
} from "@ark-ui/solid/combobox";
import type { ComboboxProps as BaseComboboxRootProps } from "@pisagor/props";
import {
  type ComboboxVariantProps,
  comboboxRecipe,
  type InputRootVariantProps,
} from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { JSX } from "solid-js";
import {
  createContext,
  createMemo,
  For,
  Show,
  splitProps,
  useContext,
} from "solid-js";
import { Portal } from "solid-js/web";
import { createSlotRecipeContext } from "../internal/create-slot-recipe-context";
import { CaretUpDownIcon, CheckIcon, XIcon } from "../internal/icons";
import { Button } from "./button";
import { InputGroup } from "./input-group";

// #region Context
const { Context: ComboboxStylesContext } = createSlotRecipeContext({
  name: "Combobox",
  recipe: comboboxRecipe,
});

/** Parts may render under a bare Ark root, so fall back to the default recipe. */
function useComboboxSlots() {
  const styles = useContext(ComboboxStylesContext);
  return () => styles?.slots ?? comboboxRecipe();
}

/** Root-level control props (`variant`, `size`) read by `Combobox.Input`. */
const ComboboxControlContext = createContext<InputRootVariantProps>({});

/** @deprecated Prefer composing within Combobox.Root; kept for public API. */
export function useComboboxRoot() {
  const styles = useContext(ComboboxStylesContext);
  if (!styles) return undefined;
  return {
    get slots() {
      return styles.slots;
    },
  };
}
// #endregion

type FormControlVariant = "primary" | "secondary";

interface ComboboxPresetItem {
  label: string;
  value: string;
}

export type ComboboxRootProps<T extends CollectionItem = CollectionItem> = Omit<
  ComboboxPrimitiveRootProps<T>,
  "onValueChange"
> & {
  /** Visual shell variant applied to the input. Defaults to `primary`. */
  variant?: FormControlVariant;
  /** Input size. Defaults to `md`. */
  size?: InputRootVariantProps["size"];
  onValueChange?: (value: string[]) => void;
} & BaseComboboxRootProps;

export interface ComboboxProps
  extends Omit<ComboboxRootProps, "children" | "collection"> {
  clearable?: boolean;
  items?: Array<ComboboxPresetItem | string>;
}

export interface ComboboxInputProps
  extends Omit<ComboboxPrimitiveInputProps, "size">,
    InputRootVariantProps {
  clearable?: boolean;
  disabled?: boolean;
  showTrigger?: boolean;
}

export interface ComboboxItemGroupProps
  extends ComboboxPrimitiveItemGroupProps {
  heading?: string | JSX.Element;
}

export interface ComboboxItemProps
  extends ComboboxPrimitiveItemProps,
    ComboboxVariantProps {}

export type ComboboxFieldInputProps = ComboboxPrimitiveInputProps;

export interface ComboboxContentProps extends ComboboxPrimitiveContentProps {
  portalled?: boolean;
}

export function ComboboxRoot<T extends CollectionItem = CollectionItem>(
  props: ComboboxRootProps<T>,
): JSX.Element {
  const [local, rest] = splitProps(props as ComboboxRootProps, [
    "openOnClick",
    "children",
    "onValueChange",
    "variant",
    "size",
    "recipe",
  ]);

  const slots = createMemo(() => (local.recipe ?? comboboxRecipe)());
  const control: InputRootVariantProps = {
    get size() {
      return local.size;
    },
    get variant() {
      return local.variant;
    },
  };

  return (
    <ComboboxStylesContext
      value={{
        get slots() {
          return slots();
        },
        variants: {},
      }}
    >
      <ComboboxControlContext.Provider value={control}>
        <ComboboxPrimitive.Root
          {...rest}
          onValueChange={
            local.onValueChange
              ? (details) => local.onValueChange?.(details.value)
              : undefined
          }
          openOnClick={local.openOnClick ?? true}
        >
          {local.children}
        </ComboboxPrimitive.Root>
      </ComboboxControlContext.Provider>
    </ComboboxStylesContext>
  );
}

export const ComboboxContext = ComboboxPrimitive.Context;

export function ComboboxControl(props: ComboboxControlProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const slots = useComboboxSlots();
  return (
    <ComboboxPrimitive.Control
      {...rest}
      class={slots().control({ class: local.class })}
    />
  );
}

export function ComboboxInput(props: ComboboxInputProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "variant",
    "clearable",
    "showTrigger",
    "children",
    "class",
  ]);
  const combobox = useComboboxContext();
  const slots = useComboboxSlots();
  const control = useContext(ComboboxControlContext);
  const size = () => local.size ?? control.size ?? "md";
  const variant = () => local.variant ?? control.variant;
  const clearable = () => local.clearable ?? false;
  const showTrigger = () => local.showTrigger ?? true;

  return (
    <ComboboxControl data-size={size()}>
      <InputGroup class={local.class} size={size()} variant={variant()}>
        {local.children}
        <ComboboxPrimitive.Input
          asChild={(inputProps) => (
            <InputGroup.Input {...inputProps()} {...rest} />
          )}
        />
        <InputGroup.Addon align="inline-end">
          <Show when={showTrigger()}>
            <ComboboxPrimitive.Trigger
              asChild={(triggerProps) => (
                <InputGroup.Button
                  {...triggerProps({ class: slots().triggerHidden() })}
                  size="icon-xs"
                  variant="ghost"
                >
                  <CaretUpDownIcon aria-hidden />
                </InputGroup.Button>
              )}
            />
          </Show>
          <Show when={clearable() && !!combobox().inputValue}>
            <ComboboxClearTrigger
              asChild={(triggerProps) => (
                <InputGroup.Button
                  {...triggerProps()}
                  aria-label="Clear"
                  size="icon-xs"
                  variant="ghost"
                >
                  <XIcon aria-hidden />
                </InputGroup.Button>
              )}
            />
          </Show>
        </InputGroup.Addon>
      </InputGroup>
    </ComboboxControl>
  );
}

export function ComboboxTrigger(props: ComboboxTriggerProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class", "asChild"]);
  const slots = useComboboxSlots();

  if (local.asChild) {
    return (
      <ComboboxPrimitive.Trigger
        {...rest}
        asChild={local.asChild}
        class={slots().trigger({ class: local.class })}
      />
    );
  }

  return (
    <ComboboxPrimitive.Trigger
      {...rest}
      asChild={(triggerProps) => (
        <Button
          {...triggerProps({ class: cn(slots().trigger(), local.class) })}
          aria-label="Toggle"
          class={slots().triggerButton()}
          variant="ghost"
        >
          {local.children ?? <CaretUpDownIcon aria-hidden />}
        </Button>
      )}
    />
  );
}

export function ComboboxClearTrigger(
  props: ComboboxClearTriggerProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["aria-label"]);
  return (
    <ComboboxPrimitive.ClearTrigger
      {...rest}
      aria-label={local["aria-label"] ?? "Clear selected value(s)"}
    />
  );
}

export function ComboboxFieldInput(
  props: ComboboxFieldInputProps,
): JSX.Element {
  return <ComboboxPrimitive.Input {...props} />;
}

export function ComboboxPositioner(
  props: ComboboxPositionerProps,
): JSX.Element {
  return <ComboboxPrimitive.Positioner {...props} />;
}

export function ComboboxContent(props: ComboboxContentProps): JSX.Element {
  const [local, rest] = splitProps(props, ["portalled", "children", "class"]);
  const slots = useComboboxSlots();
  const portalled = () => local.portalled ?? true;

  const content = (
    <ComboboxPrimitive.Content
      {...rest}
      class={slots().content({ class: local.class })}
    >
      {local.children}
    </ComboboxPrimitive.Content>
  );

  return (
    <Show fallback={content} when={portalled()}>
      <Portal>
        <ComboboxPositioner>{content}</ComboboxPositioner>
      </Portal>
    </Show>
  );
}

export function ComboboxItemGroup(props: ComboboxItemGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "heading"]);
  return (
    <ComboboxPrimitive.ItemGroup {...rest}>
      <Show when={!!local.heading}>
        <ComboboxItemGroupLabel>{local.heading}</ComboboxItemGroupLabel>
      </Show>
      {local.children}
    </ComboboxPrimitive.ItemGroup>
  );
}

export function ComboboxItemGroupLabel(
  props: ComboboxItemGroupLabelProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const slots = useComboboxSlots();
  return (
    <ComboboxPrimitive.ItemGroupLabel
      {...rest}
      class={slots().itemGroupLabel({ class: local.class })}
    />
  );
}

export function ComboboxItem(props: ComboboxItemProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "showIndicator",
    "children",
    "class",
  ]);
  const slots = useComboboxSlots();
  const showIndicator = () => local.showIndicator ?? true;

  return (
    <ComboboxPrimitive.Item
      {...rest}
      class={slots().item({
        class: local.class,
        showIndicator: showIndicator(),
      })}
      persistFocus
    >
      {local.children}
      <Show when={showIndicator()}>
        <span class={slots().itemIndicator()}>
          <ComboboxPrimitive.ItemIndicator>
            <CheckIcon />
          </ComboboxPrimitive.ItemIndicator>
        </span>
      </Show>
    </ComboboxPrimitive.Item>
  );
}

export function ComboboxEmpty(props: ComboboxEmptyProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const slots = useComboboxSlots();
  return (
    <ComboboxPrimitive.Empty
      {...rest}
      class={slots().empty({ class: local.class })}
    >
      {local.children || "No results found. Try a different search."}
    </ComboboxPrimitive.Empty>
  );
}

export function ComboboxList(props: ComboboxListProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const slots = useComboboxSlots();
  return (
    <ComboboxPrimitive.List
      {...rest}
      class={slots().list({ class: local.class })}
    />
  );
}

export function ComboboxShorthand(props: ComboboxProps): JSX.Element {
  const [local, rest] = splitProps(props, ["clearable", "items", "id"]);
  const normalized = createMemo(() =>
    (local.items ?? []).map((item) =>
      typeof item === "string" ? { label: item, value: item } : item,
    ),
  );
  const collection = createMemo(() =>
    createListCollection({ items: normalized() }),
  );

  return (
    <ComboboxRoot {...rest} collection={collection()}>
      <ComboboxInput clearable={local.clearable ?? false} id={local.id} />
      <ComboboxContent>
        <ComboboxList>
          <For each={normalized()}>
            {(item) => <ComboboxItem item={item}>{item.label}</ComboboxItem>}
          </For>
        </ComboboxList>
      </ComboboxContent>
    </ComboboxRoot>
  );
}

export type {
  ComboboxClearTriggerProps,
  ComboboxControlProps,
  ComboboxEmptyProps,
  ComboboxItemGroupLabelProps,
  ComboboxListProps,
  ComboboxPositionerProps,
  ComboboxTriggerProps,
} from "@ark-ui/solid/combobox";

export const Combobox = Object.assign(ComboboxShorthand, {
  ClearTrigger: ComboboxClearTrigger,
  Content: ComboboxContent,
  Context: ComboboxContext,
  Control: ComboboxControl,
  Empty: ComboboxEmpty,
  FieldInput: ComboboxFieldInput,
  Input: ComboboxInput,
  Item: ComboboxItem,
  ItemGroup: ComboboxItemGroup,
  ItemGroupLabel: ComboboxItemGroupLabel,
  List: ComboboxList,
  Positioner: ComboboxPositioner,
  Root: ComboboxRoot,
  Trigger: ComboboxTrigger,
});
