// packages/react/src/components/number-input.tsx
import {
  NumberInput as NumberInputPrimitive,
  type NumberInputControlProps as NumberInputPrimitiveControlProps,
  type NumberInputRootProps as NumberInputPrimitiveRootProps,
  type NumberInputScrubberProps,
} from "@ark-ui/react/number-input";
import { MinusIcon, PlusIcon } from "@phosphor-icons/react";
import type { NumberInputProps as BaseNumberInputProps } from "@pisagor/props";
import {
  formControlGroupShellRecipe,
  numberInputRecipe,
} from "@pisagor/recipes";

import { cn } from "@pisagor/utils";
import type { ComponentProps } from "react";
import { createSlotRecipeContext } from "../internal/create-slot-recipe-context";
import { Button } from "./button";
import { Field } from "./field";
import { Input, type InputProps } from "./input";
import { useFormControlSurface } from "./surface/use-form-control-surface";

// #region Context
const { Context: NumberInputStylesContext, useStyles: useNumberInput } =
  createSlotRecipeContext({
    name: "NumberInput",
    recipe: numberInputRecipe,
  });
// #endregion

// #region Types
type FormControlVariant = "primary" | "secondary";

export type NumberInputRootProps = Omit<
  NumberInputPrimitiveRootProps,
  "onValueChange"
> &
  Pick<InputProps, "size" | "variant">;

export interface NumberInputProps
  extends NumberInputRootProps,
    BaseNumberInputProps {
  /**
   * Whether to show a clear button when the input has a value.
   *
   * @defaultValue false
   */
  clearable?: boolean;
  /** Placeholder text for the auto-rendered input */
  placeholder?: string;
  /** Called with the numeric value when the input changes. */
  onValueChange?: (value: number) => void;
}

export interface NumberInputControlProps
  extends NumberInputPrimitiveControlProps {
  variant?: FormControlVariant;
  clearable?: boolean;
}

export type NumberInputDecrementTriggerProps = ComponentProps<
  typeof NumberInputPrimitive.DecrementTrigger
>;

export type NumberInputIncrementTriggerProps = ComponentProps<
  typeof NumberInputPrimitive.IncrementTrigger
>;

// #endregion

// #region Parts
export function NumberInputRoot({
  size = "md",
  variant,
  clearable = false,
  children,
  placeholder,
  onValueChange,
  recipe = numberInputRecipe,
  className,
  ...rest
}: NumberInputProps) {
  const slots = recipe();

  return (
    <NumberInputStylesContext value={{ slots, variants: {} as never }}>
      <NumberInputPrimitive.Root
        {...rest}
        className={slots.base({ className })}
        data-size={size}
        onValueChange={
          onValueChange
            ? (details) => onValueChange(Number(details.value))
            : undefined
        }
      >
        {children ?? (
          <NumberInputControl clearable={clearable} variant={variant}>
            <NumberInputDecrementTrigger />
            <NumberInputInput placeholder={placeholder} variant={variant} />
            <NumberInputClearTrigger />
            <NumberInputIncrementTrigger />
          </NumberInputControl>
        )}
      </NumberInputPrimitive.Root>
    </NumberInputStylesContext>
  );
}

export function NumberInputControl({
  variant: variantProp,
  clearable = false,
  className,
  ...rest
}: NumberInputControlProps) {
  const { slots } = useNumberInput();
  const resolved = {
    surfaceVariant: useFormControlSurface(),
    variant: variantProp ?? ("primary" as FormControlVariant),
  };
  const shellArgs = {
    surfaceVariant: resolved.surfaceVariant,
    variant: resolved.variant,
  };
  const controlProps = { "data-variant": resolved.variant };

  return (
    <NumberInputPrimitive.Control
      {...rest}
      {...controlProps}
      className={cn(
        slots.control(),
        formControlGroupShellRecipe({ size: "md", ...shellArgs }),
        className,
      )}
      data-clearable={clearable || undefined}
    />
  );
}

export function NumberInputClearTrigger() {
  const { slots } = useNumberInput();

  return (
    <NumberInputPrimitive.Context>
      {(api) => {
        const hasValue =
          api.value !== undefined &&
          api.value !== null &&
          String(api.value).length > 0;

        if (!hasValue) {
          return null;
        }

        return (
          <Input.ClearButton
            className={slots.clearTrigger()}
            onClear={() => api.setValue(Number.NaN)}
          />
        );
      }}
    </NumberInputPrimitive.Context>
  );
}

export function NumberInputDecrementTrigger({
  className,
  ...rest
}: NumberInputDecrementTriggerProps) {
  const { slots } = useNumberInput();

  return (
    <NumberInputPrimitive.DecrementTrigger
      {...rest}
      asChild
      className={slots.decrementTrigger({ className })}
    >
      <Button aria-label="Decrement" variant="ghost">
        <MinusIcon aria-hidden />
      </Button>
    </NumberInputPrimitive.DecrementTrigger>
  );
}

export function NumberInputIncrementTrigger({
  className,
  ...rest
}: NumberInputIncrementTriggerProps) {
  const { slots } = useNumberInput();

  return (
    <NumberInputPrimitive.IncrementTrigger
      {...rest}
      asChild
      className={slots.incrementTrigger({ className })}
    >
      <Button aria-label="Increment" variant="ghost">
        <PlusIcon aria-hidden />
      </Button>
    </NumberInputPrimitive.IncrementTrigger>
  );
}

export function NumberInputInput({
  size,
  variant,
  className,
  classNames,
  ...rest
}: InputProps) {
  const { slots } = useNumberInput();

  return (
    <NumberInputPrimitive.Input {...rest} asChild>
      <Input
        className={slots.input({ className })}
        classNames={classNames}
        size={size}
        variant={variant}
      />
    </NumberInputPrimitive.Input>
  );
}

export function NumberInputScrubber({
  children,
  className,
  ...rest
}: NumberInputScrubberProps) {
  const { slots } = useNumberInput();

  return (
    <NumberInputPrimitive.Scrubber
      {...rest}
      asChild
      className={slots.scrubber({ className })}
    >
      <NumberInputPrimitive.Label asChild>
        <Field.Label>{children}</Field.Label>
      </NumberInputPrimitive.Label>
    </NumberInputPrimitive.Scrubber>
  );
}
// #endregion

// #region Display Names
NumberInputRoot.displayName = "NumberInput";
NumberInputControl.displayName = "NumberInput.Control";
NumberInputClearTrigger.displayName = "NumberInput.ClearTrigger";
NumberInputDecrementTrigger.displayName = "NumberInput.DecrementTrigger";
NumberInputIncrementTrigger.displayName = "NumberInput.IncrementTrigger";
NumberInputInput.displayName = "NumberInput.Input";
NumberInputScrubber.displayName = "NumberInput.Scrubber";

// #endregion

export type { NumberInputScrubberProps } from "@ark-ui/react/number-input";

export const NumberInput = Object.assign(NumberInputRoot, {
  ClearTrigger: NumberInputClearTrigger,
  Control: NumberInputControl,
  DecrementTrigger: NumberInputDecrementTrigger,
  IncrementTrigger: NumberInputIncrementTrigger,
  Input: NumberInputInput,
  Scrubber: NumberInputScrubber,
});

// packages/solid/src/components/number-input.tsx
import {
  NumberInput as NumberInputPrimitive,
  type NumberInputControlProps as NumberInputPrimitiveControlProps,
  type NumberInputRootProps as NumberInputPrimitiveRootProps,
  type NumberInputScrubberProps,
} from "@ark-ui/solid/number-input";
import type { NumberInputProps as BaseNumberInputProps } from "@pisagor/props";
import {
  formControlGroupShellRecipe,
  numberInputRecipe,
} from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { createMemo, Show, splitProps } from "solid-js";
import { createSlotRecipeContext } from "../internal/create-slot-recipe-context";
import { MinusIcon, PlusIcon } from "../internal/icons";
import { Button } from "./button";
import { Input, type InputProps } from "./input";
import { useFormControlSurface } from "./surface/use-form-control-surface";

// #region Context
const { Context: NumberInputStylesContext, useStyles: useNumberInput } =
  createSlotRecipeContext({
    name: "NumberInput",
    recipe: numberInputRecipe,
  });
// #endregion

type FormControlVariant = "primary" | "secondary";

export type NumberInputRootProps = Omit<
  NumberInputPrimitiveRootProps,
  "onValueChange"
> &
  Pick<InputProps, "size" | "variant">;

export interface NumberInputProps
  extends NumberInputRootProps,
    BaseNumberInputProps {
  clearable?: boolean;
  placeholder?: string;
  onValueChange?: (value: number) => void;
}

export interface NumberInputControlProps
  extends NumberInputPrimitiveControlProps {
  variant?: FormControlVariant;
  clearable?: boolean;
}

export type NumberInputDecrementTriggerProps = ComponentProps<
  typeof NumberInputPrimitive.DecrementTrigger
>;

export type NumberInputIncrementTriggerProps = ComponentProps<
  typeof NumberInputPrimitive.IncrementTrigger
>;

export function NumberInputRoot(props: NumberInputProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "variant",
    "clearable",
    "children",
    "placeholder",
    "onValueChange",
    "recipe",
    "class",
  ]);
  const size = () => local.size ?? "md";
  const clearable = () => local.clearable ?? false;

  const slots = createMemo(() => (local.recipe ?? numberInputRecipe)());

  return (
    <NumberInputStylesContext
      value={{
        get slots() {
          return slots();
        },
        variants: {},
      }}
    >
      <NumberInputPrimitive.Root
        {...rest}
        class={slots().base({ class: local.class })}
        data-size={size()}
        onValueChange={
          local.onValueChange
            ? (details) => local.onValueChange?.(Number(details.value))
            : undefined
        }
      >
        <Show
          fallback={
            <NumberInputControl clearable={clearable()} variant={local.variant}>
              <NumberInputDecrementTrigger />
              <NumberInputInput
                placeholder={local.placeholder}
                variant={local.variant}
              />
              <NumberInputClearTrigger />
              <NumberInputIncrementTrigger />
            </NumberInputControl>
          }
          when={local.children}
        >
          {local.children}
        </Show>
      </NumberInputPrimitive.Root>
    </NumberInputStylesContext>
  );
}

export function NumberInputControl(
  props: NumberInputControlProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["variant", "clearable", "class"]);
  const styles = useNumberInput();
  const surfaceVariant = useFormControlSurface();
  const variant = () => local.variant ?? ("primary" as FormControlVariant);

  return (
    <NumberInputPrimitive.Control
      {...rest}
      class={cn(
        styles.slots.control(),
        formControlGroupShellRecipe({
          size: "md",
          surfaceVariant,
          variant: variant(),
        }),
        local.class,
      )}
      data-clearable={local.clearable || undefined}
      data-variant={variant()}
    />
  );
}

export function NumberInputClearTrigger(): JSX.Element {
  const styles = useNumberInput();

  return (
    <NumberInputPrimitive.Context>
      {(api) => {
        const hasValue = () => {
          const value = api().value;
          return (
            value !== undefined && value !== null && String(value).length > 0
          );
        };

        return (
          <Show when={hasValue()}>
            <Input.ClearButton
              class={styles.slots.clearTrigger()}
              onClear={() => api().setValue(Number.NaN)}
            />
          </Show>
        );
      }}
    </NumberInputPrimitive.Context>
  );
}

export function NumberInputDecrementTrigger(
  props: NumberInputDecrementTriggerProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const styles = useNumberInput();

  return (
    <NumberInputPrimitive.DecrementTrigger
      {...rest}
      asChild={(triggerProps) => (
        <Button
          {...triggerProps({
            class: styles.slots.decrementTrigger({ class: local.class }),
          })}
          aria-label="Decrement"
          variant="ghost"
        >
          <MinusIcon />
        </Button>
      )}
    />
  );
}

export function NumberInputIncrementTrigger(
  props: NumberInputIncrementTriggerProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const styles = useNumberInput();

  return (
    <NumberInputPrimitive.IncrementTrigger
      {...rest}
      asChild={(triggerProps) => (
        <Button
          {...triggerProps({
            class: styles.slots.incrementTrigger({ class: local.class }),
          })}
          aria-label="Increment"
          variant="ghost"
        >
          <PlusIcon />
        </Button>
      )}
    />
  );
}

export function NumberInputInput(props: InputProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "variant",
    "class",
    "classNames",
  ]);
  const styles = useNumberInput();

  return (
    <NumberInputPrimitive.Input
      asChild={(inputProps) => (
        <Input
          {...inputProps({ class: styles.slots.input({ class: local.class }) })}
          {...rest}
          classNames={local.classNames}
          size={local.size}
          variant={local.variant}
        />
      )}
    />
  );
}

export function NumberInputScrubber(
  props: NumberInputScrubberProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const styles = useNumberInput();

  return (
    <NumberInputPrimitive.Scrubber
      {...rest}
      class={styles.slots.scrubber({ class: local.class })}
    >
      <NumberInputPrimitive.Label>{local.children}</NumberInputPrimitive.Label>
    </NumberInputPrimitive.Scrubber>
  );
}

export type { NumberInputScrubberProps } from "@ark-ui/solid/number-input";

export const NumberInput = Object.assign(NumberInputRoot, {
  ClearTrigger: NumberInputClearTrigger,
  Control: NumberInputControl,
  DecrementTrigger: NumberInputDecrementTrigger,
  IncrementTrigger: NumberInputIncrementTrigger,
  Input: NumberInputInput,
  Scrubber: NumberInputScrubber,
});
