// packages/react/src/components/select.tsx
import { Portal } from "@ark-ui/react";
import {
  type CollectionItem,
  createListCollection,
} from "@ark-ui/react/collection";
import { ark } from "@ark-ui/react/factory";
import type {
  SelectClearTriggerProps,
  SelectContentProps,
  SelectItemGroupLabelProps,
  SelectItemProps,
  SelectItemGroupProps as SelectPrimitiveItemGroupProps,
  SelectRootProps as SelectPrimitiveRootProps,
  SelectTriggerProps as SelectPrimitiveTriggerProps,
  SelectValueTextProps,
} from "@ark-ui/react/select";
import {
  Select as SelectPrimitive,
  useSelectContext,
} from "@ark-ui/react/select";
import { CaretUpDownIcon, CheckIcon, XIcon } from "@phosphor-icons/react";
import type { SelectProps as BaseSelectRootProps } from "@pisagor/props";
import {
  type FormControlShellVariantProps,
  formControlShellRecipe,
  selectRecipe,
} from "@pisagor/recipes";

import { cn } from "@pisagor/utils";
import type { ComponentProps, ReactNode } from "react";
import { createContext, use } from "react";
import { createSlotRecipeContext } from "../internal/create-slot-recipe-context";
import { Separator, type SeparatorProps } from "./separator";
import { useFormControlSurface } from "./surface/use-form-control-surface";

// #region Context
const { Context: SelectStylesContext } = createSlotRecipeContext({
  name: "Select",
  recipe: selectRecipe,
});

function useSelectSlots() {
  const styles = use(SelectStylesContext);
  return styles?.slots ?? selectRecipe();
}

/** Root-level control props (`variant`, `size`) read by `Select.Trigger`. */
const SelectControlContext = createContext<FormControlShellVariantProps>({});
SelectControlContext.displayName = "SelectControlContext";
// #endregion

// #region Types
type FormControlVariant = "primary" | "secondary";

interface SelectPresetItem {
  label: string;
  value: string;
}

export type SelectRootProps<T extends CollectionItem = CollectionItem> = Omit<
  SelectPrimitiveRootProps<T>,
  "onValueChange"
> & {
  /**
   * Visual shell variant applied to the trigger. Defaults to `primary`.
   */
  variant?: FormControlVariant;
  /**
   * Trigger size. Defaults to `md`.
   */
  size?: FormControlShellVariantProps["size"];
  onValueChange?: (value: string | string[]) => void;
} & BaseSelectRootProps;

export interface SelectProps
  extends Omit<SelectRootProps, "children" | "collection"> {
  /**
   * Whether to show a clear button when a value is selected.
   *
   * @defaultValue false
   */
  clearable?: boolean;
  items?: Array<SelectPresetItem | string>;
  placeholder?: string;
}

export interface SelectTriggerProps
  extends Omit<SelectPrimitiveTriggerProps, "size">,
    FormControlShellVariantProps {
  /**
   * Whether to show a clear button when a value is selected.
   *
   * @defaultValue false
   */
  clearable?: boolean;
}

export interface SelectItemGroupProps extends SelectPrimitiveItemGroupProps {
  /** The heading of the group */
  heading?: string | ReactNode;
}

export type SelectEmptyProps = ComponentProps<typeof ark.div>;
// #endregion

// #region Parts
export const SelectContext = SelectPrimitive.Context;

export function SelectRoot<T extends CollectionItem = CollectionItem>({
  children,
  onValueChange,
  variant,
  size,
  recipe = selectRecipe,
  ...rest
}: SelectRootProps<T>) {
  const slots = recipe();

  return (
    <SelectStylesContext value={{ slots, variants: {} as never }}>
      <SelectControlContext value={{ size, variant }}>
        <SelectPrimitive.Root
          {...rest}
          onValueChange={
            onValueChange
              ? (details) => onValueChange(details.value)
              : undefined
          }
        >
          {children}

          <SelectPrimitive.HiddenSelect />
        </SelectPrimitive.Root>
      </SelectControlContext>
    </SelectStylesContext>
  );
}

export function SelectTrigger({
  size: sizeProp,
  variant: variantProp,
  clearable = false,
  children,
  className,
  ...rest
}: SelectTriggerProps) {
  const slots = useSelectSlots();
  const control = use(SelectControlContext);
  const size = sizeProp ?? control.size ?? "md";
  const resolved = {
    surfaceVariant: useFormControlSurface(),
    variant:
      variantProp ?? control.variant ?? ("primary" as FormControlVariant),
  };
  const shellArgs = {
    surfaceVariant: resolved.surfaceVariant,
    variant: resolved.variant,
  };
  const controlProps = { "data-variant": resolved.variant };

  return (
    <SelectPrimitive.Control>
      <SelectPrimitive.Trigger
        {...rest}
        {...controlProps}
        className={cn(
          formControlShellRecipe({ size, ...shellArgs }),
          slots.trigger(),
          className,
        )}
      >
        {children}

        <div className={slots.triggerActions()}>
          {clearable && (
            <SelectClearTrigger>
              <XIcon />
            </SelectClearTrigger>
          )}
          <SelectPrimitive.Indicator>
            <CaretUpDownIcon />
          </SelectPrimitive.Indicator>
        </div>
      </SelectPrimitive.Trigger>
    </SelectPrimitive.Control>
  );
}

export function SelectSeparator({ className, ...rest }: SeparatorProps) {
  const slots = useSelectSlots();

  return (
    <Separator
      {...rest}
      className={slots.separator({ className })}
      data-part="separator"
      data-scope="select"
    />
  );
}

export function SelectValueText({ className, ...rest }: SelectValueTextProps) {
  const slots = useSelectSlots();

  return (
    <SelectPrimitive.ValueText
      {...rest}
      className={slots.valueText({ className })}
    />
  );
}

export function SelectContent({ className, ...rest }: SelectContentProps) {
  const slots = useSelectSlots();

  return (
    <Portal>
      <SelectPrimitive.Positioner>
        <SelectPrimitive.Content
          {...rest}
          className={slots.content({ className })}
        />
      </SelectPrimitive.Positioner>
    </Portal>
  );
}

export function SelectItemGroup({
  children,
  heading,
  ...rest
}: SelectItemGroupProps) {
  return (
    <SelectPrimitive.ItemGroup {...rest}>
      {!heading && <SelectItemGroupLabel>{heading}</SelectItemGroupLabel>}

      {children}
    </SelectPrimitive.ItemGroup>
  );
}

export function SelectItemGroupLabel({
  className,
  ...rest
}: SelectItemGroupLabelProps) {
  const slots = useSelectSlots();

  return (
    <SelectPrimitive.ItemGroupLabel
      {...rest}
      className={slots.itemGroupLabel({ className })}
    />
  );
}

export function SelectItem({ children, className, ...rest }: SelectItemProps) {
  const slots = useSelectSlots();

  return (
    <SelectPrimitive.Item {...rest} className={slots.item({ className })}>
      <SelectPrimitive.ItemText className={slots.itemText()}>
        {children}
      </SelectPrimitive.ItemText>

      <span className={slots.itemIndicator()}>
        <SelectPrimitive.ItemIndicator>
          <CheckIcon />
        </SelectPrimitive.ItemIndicator>
      </span>
    </SelectPrimitive.Item>
  );
}

export function SelectClearTrigger({
  className,
  ...rest
}: SelectClearTriggerProps) {
  const slots = useSelectSlots();

  return (
    <SelectPrimitive.ClearTrigger
      {...rest}
      aria-label="Clear selected value(s)"
      className={slots.clearTrigger({ className })}
    />
  );
}

export function SelectEmpty({ className, ...rest }: SelectEmptyProps) {
  const { empty } = useSelectContext();
  const slots = useSelectSlots();

  if (empty) {
    return (
      <ark.div
        {...rest}
        className={slots.empty({ className })}
        role="presentation"
      />
    );
  }

  return null;
}
// #endregion

// #region Shorthand
export function SelectShorthand({
  clearable = false,
  items = [],
  placeholder,
  ...rest
}: SelectProps) {
  const normalized = items.map((item) =>
    typeof item === "string" ? { label: item, value: item } : item,
  );
  const collection = createListCollection({ items: normalized });

  return (
    <SelectRoot {...rest} collection={collection}>
      <SelectTrigger clearable={clearable}>
        <SelectValueText placeholder={placeholder} />
      </SelectTrigger>
      <SelectContent>
        {normalized.map((item) => (
          <SelectItem item={item} key={item.value}>
            {item.label}
          </SelectItem>
        ))}
      </SelectContent>
    </SelectRoot>
  );
}
// #endregion

// #region Display Names
SelectRoot.displayName = "Select.Root";
SelectTrigger.displayName = "Select.Trigger";
SelectSeparator.displayName = "Select.Separator";
SelectValueText.displayName = "Select.ValueText";
SelectContent.displayName = "Select.Content";
SelectItemGroup.displayName = "Select.ItemGroup";
SelectItemGroupLabel.displayName = "Select.ItemGroupLabel";
SelectItem.displayName = "Select.Item";
SelectClearTrigger.displayName = "Select.ClearTrigger";
SelectEmpty.displayName = "Select.Empty";
SelectShorthand.displayName = "Select";

// #endregion

export type {
  SelectClearTriggerProps,
  SelectContentProps,
  SelectItemGroupLabelProps,
  SelectItemProps,
  SelectValueTextProps,
} from "@ark-ui/react/select";

export const Select = Object.assign(SelectShorthand, {
  ClearTrigger: SelectClearTrigger,
  Content: SelectContent,
  Context: SelectContext,
  Empty: SelectEmpty,
  Item: SelectItem,
  ItemGroup: SelectItemGroup,
  ItemGroupLabel: SelectItemGroupLabel,
  Root: SelectRoot,
  Separator: SelectSeparator,
  Trigger: SelectTrigger,
  ValueText: SelectValueText,
});

// packages/solid/src/components/select.tsx
import {
  type CollectionItem,
  createListCollection,
} from "@ark-ui/solid/collection";
import { ark } from "@ark-ui/solid/factory";
import type {
  SelectClearTriggerProps,
  SelectContentProps,
  SelectItemGroupLabelProps,
  SelectItemProps,
  SelectItemGroupProps as SelectPrimitiveItemGroupProps,
  SelectRootProps as SelectPrimitiveRootProps,
  SelectTriggerProps as SelectPrimitiveTriggerProps,
  SelectValueTextProps,
} from "@ark-ui/solid/select";
import {
  Select as SelectPrimitive,
  useSelectContext,
} from "@ark-ui/solid/select";
import type { SelectProps as BaseSelectRootProps } from "@pisagor/props";
import {
  type FormControlShellVariantProps,
  formControlShellRecipe,
  selectRecipe,
} from "@pisagor/recipes";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import {
  createContext,
  createMemo,
  For,
  Show,
  splitProps,
  useContext,
} from "solid-js";
import { Portal } from "solid-js/web";
import { createSlotRecipeContext } from "../internal/create-slot-recipe-context";
import { CaretUpDownIcon, CheckIcon, XIcon } from "../internal/icons";
import { Separator, type SeparatorProps } from "./separator";
import { useFormControlSurface } from "./surface/use-form-control-surface";

// #region Context
const { Context: SelectStylesContext } = createSlotRecipeContext({
  name: "Select",
  recipe: selectRecipe,
});

/** Parts may render under a bare Ark root, so fall back to the default recipe. */
function useSelectSlots() {
  const styles = useContext(SelectStylesContext);
  return () => styles?.slots ?? selectRecipe();
}

/** Root-level control props (`variant`, `size`) read by `Select.Trigger`. */
const SelectControlContext = createContext<FormControlShellVariantProps>({});
// #endregion

type FormControlVariant = "primary" | "secondary";

interface SelectPresetItem {
  label: string;
  value: string;
}

export type SelectRootProps<T extends CollectionItem = CollectionItem> = Omit<
  SelectPrimitiveRootProps<T>,
  "onValueChange"
> & {
  /** Visual shell variant applied to the trigger. Defaults to `primary`. */
  variant?: FormControlVariant;
  /** Trigger size. Defaults to `md`. */
  size?: FormControlShellVariantProps["size"];
  onValueChange?: (value: string | string[]) => void;
} & BaseSelectRootProps;

export interface SelectProps
  extends Omit<SelectRootProps, "children" | "collection"> {
  clearable?: boolean;
  items?: Array<SelectPresetItem | string>;
  placeholder?: string;
}

export interface SelectTriggerProps
  extends Omit<SelectPrimitiveTriggerProps, "size">,
    FormControlShellVariantProps {
  clearable?: boolean;
}

export interface SelectItemGroupProps extends SelectPrimitiveItemGroupProps {
  heading?: string | JSX.Element;
}

export type SelectEmptyProps = ComponentProps<typeof ark.div>;

export const SelectContext = SelectPrimitive.Context;

export function SelectRoot<T extends CollectionItem = CollectionItem>(
  props: SelectRootProps<T>,
): JSX.Element {
  const [local, rest] = splitProps(props as SelectRootProps, [
    "children",
    "onValueChange",
    "variant",
    "size",
    "recipe",
  ]);

  const slots = createMemo(() => (local.recipe ?? selectRecipe)());
  const control: FormControlShellVariantProps = {
    get size() {
      return local.size;
    },
    get variant() {
      return local.variant;
    },
  };

  return (
    <SelectStylesContext
      value={{
        get slots() {
          return slots();
        },
        variants: {},
      }}
    >
      <SelectControlContext.Provider value={control}>
        <SelectPrimitive.Root
          {...rest}
          onValueChange={
            local.onValueChange
              ? (details) => local.onValueChange?.(details.value)
              : undefined
          }
        >
          {local.children}
          <SelectPrimitive.HiddenSelect />
        </SelectPrimitive.Root>
      </SelectControlContext.Provider>
    </SelectStylesContext>
  );
}

export function SelectTrigger(props: SelectTriggerProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "variant",
    "clearable",
    "children",
    "class",
  ]);
  const slots = useSelectSlots();
  const control = useContext(SelectControlContext);
  const size = () => local.size ?? control.size ?? "md";
  const surfaceVariant = useFormControlSurface();
  const variant = () =>
    local.variant ?? control.variant ?? ("primary" as FormControlVariant);
  const clearable = () => local.clearable ?? false;

  return (
    <SelectPrimitive.Control>
      <SelectPrimitive.Trigger
        {...rest}
        class={cn(
          formControlShellRecipe({
            size: size(),
            surfaceVariant,
            variant: variant(),
          }),
          slots().trigger(),
          local.class,
        )}
        data-variant={variant()}
      >
        {local.children}
        <div class={slots().triggerActions()}>
          <Show when={clearable()}>
            <SelectClearTrigger>
              <XIcon />
            </SelectClearTrigger>
          </Show>
          <SelectPrimitive.Indicator>
            <CaretUpDownIcon />
          </SelectPrimitive.Indicator>
        </div>
      </SelectPrimitive.Trigger>
    </SelectPrimitive.Control>
  );
}

export function SelectSeparator(props: SeparatorProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const slots = useSelectSlots();

  return (
    <Separator
      {...rest}
      class={slots().separator({ class: local.class })}
      data-part="separator"
      data-scope="select"
    />
  );
}

export function SelectValueText(props: SelectValueTextProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const slots = useSelectSlots();
  return (
    <SelectPrimitive.ValueText
      {...rest}
      class={slots().valueText({ class: local.class })}
    />
  );
}

export function SelectContent(props: SelectContentProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const slots = useSelectSlots();

  return (
    <Portal>
      <SelectPrimitive.Positioner>
        <SelectPrimitive.Content
          {...rest}
          class={slots().content({ class: local.class })}
        />
      </SelectPrimitive.Positioner>
    </Portal>
  );
}

export function SelectItemGroup(props: SelectItemGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "heading"]);

  return (
    <SelectPrimitive.ItemGroup {...rest}>
      <Show when={local.heading !== undefined && local.heading !== false}>
        <SelectItemGroupLabel>{local.heading}</SelectItemGroupLabel>
      </Show>
      {local.children}
    </SelectPrimitive.ItemGroup>
  );
}

export function SelectItemGroupLabel(
  props: SelectItemGroupLabelProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const slots = useSelectSlots();
  return (
    <SelectPrimitive.ItemGroupLabel
      {...rest}
      class={slots().itemGroupLabel({ class: local.class })}
    />
  );
}

export function SelectItem(props: SelectItemProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const slots = useSelectSlots();

  return (
    <SelectPrimitive.Item
      {...rest}
      class={slots().item({ class: local.class })}
    >
      <SelectPrimitive.ItemText class={slots().itemText()}>
        {local.children}
      </SelectPrimitive.ItemText>
      <span class={slots().itemIndicator()}>
        <SelectPrimitive.ItemIndicator>
          <CheckIcon />
        </SelectPrimitive.ItemIndicator>
      </span>
    </SelectPrimitive.Item>
  );
}

export function SelectClearTrigger(
  props: SelectClearTriggerProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const slots = useSelectSlots();

  return (
    <SelectPrimitive.ClearTrigger
      {...rest}
      aria-label="Clear selected value(s)"
      class={slots().clearTrigger({ class: local.class })}
    />
  );
}

export function SelectEmpty(props: SelectEmptyProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const select = useSelectContext();
  const slots = useSelectSlots();

  return (
    <Show when={select().empty}>
      <ark.div
        {...rest}
        class={slots().empty({ class: local.class })}
        role="presentation"
      />
    </Show>
  );
}

export function SelectShorthand(props: SelectProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "clearable",
    "items",
    "placeholder",
  ]);
  const normalized = createMemo(() =>
    (local.items ?? []).map((item) =>
      typeof item === "string" ? { label: item, value: item } : item,
    ),
  );
  const collection = createMemo(() =>
    createListCollection({ items: normalized() }),
  );

  return (
    <SelectRoot {...rest} collection={collection()}>
      <SelectTrigger clearable={local.clearable ?? false}>
        <SelectValueText placeholder={local.placeholder} />
      </SelectTrigger>
      <SelectContent>
        <For each={normalized()}>
          {(item) => <SelectItem item={item}>{item.label}</SelectItem>}
        </For>
      </SelectContent>
    </SelectRoot>
  );
}

export type {
  SelectClearTriggerProps,
  SelectContentProps,
  SelectItemGroupLabelProps,
  SelectItemProps,
  SelectValueTextProps,
} from "@ark-ui/solid/select";

export const Select = Object.assign(SelectShorthand, {
  ClearTrigger: SelectClearTrigger,
  Content: SelectContent,
  Context: SelectContext,
  Empty: SelectEmpty,
  Item: SelectItem,
  ItemGroup: SelectItemGroup,
  ItemGroupLabel: SelectItemGroupLabel,
  Root: SelectRoot,
  Separator: SelectSeparator,
  Trigger: SelectTrigger,
  ValueText: SelectValueText,
});
