// packages/solid/src/components/alert-dialog/alert-dialog.tsx
import type { JSX } from "solid-js";
import { Show, splitProps } from "solid-js";
import { Portal } from "solid-js/web";
import { Button, type ButtonProps } from "../button";
import type {
  DialogBodyProps,
  DialogCloseTriggerProps,
  DialogContentProps,
  DialogDescriptionProps,
  DialogFooterProps,
  DialogHeaderProps,
  DialogRootProps,
  DialogTitleProps,
  DialogTriggerProps,
} from "../dialog";
import { Dialog } from "../dialog";
import { useDialog } from "../dialog/dialog.context";

export type AlertDialogRootProps = DialogRootProps;

export interface AlertDialogActionProps
  extends DialogCloseTriggerProps,
    Omit<ButtonProps, "variant"> {
  variant?: "default" | "destructive";
}

export interface AlertDialogCancelProps
  extends DialogCloseTriggerProps,
    Omit<ButtonProps, "variant"> {}

export interface AlertDialogProps
  extends Omit<AlertDialogRootProps, "children" | "title"> {
  actions?: JSX.Element;
  description?: JSX.Element;
  title?: JSX.Element;
  trigger?:
    | JSX.Element
    | ((props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) => JSX.Element);
}

export function AlertDialogRoot(props: AlertDialogRootProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <Dialog.Root {...rest} role="alertdialog">
      {local.children}
    </Dialog.Root>
  );
}

export function AlertDialogTrigger(props: DialogTriggerProps): JSX.Element {
  return <Dialog.Trigger {...props} />;
}

export function AlertDialogContent(props: DialogContentProps): JSX.Element {
  const [local, rest] = splitProps(props, ["bottomStickOnMobile", "children"]);
  const bottomStickOnMobile = () => local.bottomStickOnMobile ?? true;

  return (
    <Portal>
      <Dialog.Backdrop />
      <Dialog.Positioner bottomStickOnMobile={bottomStickOnMobile()}>
        <Dialog.Content
          {...rest}
          bottomStickOnMobile={bottomStickOnMobile()}
          showCloseButton={false}
        >
          {local.children}
        </Dialog.Content>
      </Dialog.Positioner>
    </Portal>
  );
}

export function AlertDialogBody(props: DialogBodyProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useDialog();

  return (
    <Dialog.Body
      {...rest}
      class={slots.alertBody({ class: local.class })}
      data-part="body"
      data-scope="alert-dialog"
    />
  );
}

export function AlertDialogHeader(props: DialogHeaderProps): JSX.Element {
  return (
    <Dialog.Header {...props} data-part="header" data-scope="alert-dialog" />
  );
}

export function AlertDialogTitle(props: DialogTitleProps): JSX.Element {
  return <Dialog.Title {...props} />;
}

export function AlertDialogDescription(
  props: DialogDescriptionProps,
): JSX.Element {
  return <Dialog.Description {...props} />;
}

export function AlertDialogCloseTrigger(
  props: DialogCloseTriggerProps,
): JSX.Element {
  return <Dialog.CloseTrigger {...props} />;
}

export function AlertDialogFooter(props: DialogFooterProps): JSX.Element {
  return (
    <Dialog.Footer {...props} data-part="footer" data-scope="alert-dialog" />
  );
}

export function AlertDialogAction(props: AlertDialogActionProps): JSX.Element {
  const [local, rest] = splitProps(props, ["variant"]);
  return <Button {...rest} variant={local.variant ?? "default"} />;
}

export function AlertDialogCancel(props: AlertDialogCancelProps): JSX.Element {
  const [local, rest] = splitProps(props, ["asChild", "class"]);
  return (
    <AlertDialogCloseTrigger
      asChild={(triggerProps) => (
        <Button
          {...triggerProps({ class: local.class })}
          {...rest}
          variant="outline"
        />
      )}
    />
  );
}

export function AlertDialogShorthand(props: AlertDialogProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "actions",
    "description",
    "title",
    "trigger",
  ]);

  return (
    <AlertDialogRoot {...rest}>
      <Show when={local.trigger !== undefined}>
        <AlertDialogTrigger
          asChild={(triggerProps) => {
            if (typeof local.trigger === "function") {
              return local.trigger(triggerProps());
            }
            return (
              <span {...triggerProps()} style={{ display: "contents" }}>
                {local.trigger}
              </span>
            );
          }}
        />
      </Show>

      <AlertDialogContent>
        <Show
          when={local.title !== undefined || local.description !== undefined}
        >
          <AlertDialogHeader>
            <Show when={local.title !== undefined}>
              <AlertDialogTitle>{local.title}</AlertDialogTitle>
            </Show>
            <Show when={local.description !== undefined}>
              <AlertDialogDescription>
                {local.description}
              </AlertDialogDescription>
            </Show>
          </AlertDialogHeader>
        </Show>
        <Show when={local.actions !== undefined}>
          <AlertDialogFooter>{local.actions}</AlertDialogFooter>
        </Show>
      </AlertDialogContent>
    </AlertDialogRoot>
  );
}

// packages/react-ui/src/components/alert-dialog/alert-dialog.tsx
import { Portal } from "@ark-ui/react/portal";
import type { ReactNode } from "react";
import { Button, type ButtonProps } from "../button";
import {
  Dialog,
  type DialogBodyProps,
  type DialogCloseTriggerProps,
  type DialogContentProps,
  type DialogDescriptionProps,
  type DialogFooterProps,
  type DialogHeaderProps,
  type DialogRootProps,
  type DialogTitleProps,
  type DialogTriggerProps,
} from "../dialog";
import { useDialog } from "../dialog/dialog.context";

// #region Types
export interface AlertDialogRootProps extends DialogRootProps {}

export interface AlertDialogActionProps
  extends DialogCloseTriggerProps,
    Omit<ButtonProps, "variant"> {
  /**
   * The variant of the action button
   *
   * @defaultValue "default"
   */
  variant?: "default" | "destructive";
}

export interface AlertDialogCancelProps
  extends DialogCloseTriggerProps,
    Omit<ButtonProps, "variant"> {}

export interface AlertDialogProps extends Omit<AlertDialogRootProps, "children" | "title"> {
  /** Header title content. */
  title?: ReactNode;
  /** Header description content. */
  description?: ReactNode;
  /** Footer actions (typically Cancel / Action). */
  actions?: ReactNode;
  /** Control that opens the dialog. */
  trigger?: ReactNode;
}
// #endregion

// #region Parts
export function AlertDialogRoot({ children, ...rest }: AlertDialogRootProps) {
  return (
    <Dialog.Root {...rest} role="alertdialog">
      {children}
    </Dialog.Root>
  );
}

export function AlertDialogTrigger(props: DialogTriggerProps) {
  return <Dialog.Trigger {...props} />;
}

export function AlertDialogContent({
  bottomStickOnMobile = true,
  children,
  ...rest
}: DialogContentProps) {
  return (
    <Portal>
      <Dialog.Backdrop />

      <Dialog.Positioner bottomStickOnMobile={bottomStickOnMobile}>
        <Dialog.Content {...rest} bottomStickOnMobile={bottomStickOnMobile} showCloseButton={false}>
          {children}
        </Dialog.Content>
      </Dialog.Positioner>
    </Portal>
  );
}

export function AlertDialogBody({ className, ...rest }: DialogBodyProps) {
  const { slots } = useDialog();

  return (
    <Dialog.Body
      {...rest}
      className={slots.alertBody({ className })}
      data-part="body"
      data-scope="alert-dialog"
    />
  );
}

export function AlertDialogHeader(props: DialogHeaderProps) {
  return <Dialog.Header data-part="header" data-scope="alert-dialog" {...props} />;
}

export function AlertDialogTitle(props: DialogTitleProps) {
  return <Dialog.Title {...props} />;
}

export function AlertDialogDescription(props: DialogDescriptionProps) {
  return <Dialog.Description {...props} />;
}

export function AlertDialogCloseTrigger(props: DialogCloseTriggerProps) {
  return <Dialog.CloseTrigger {...props} />;
}

export function AlertDialogFooter(props: DialogFooterProps) {
  return <Dialog.Footer data-part="footer" data-scope="alert-dialog" {...props} />;
}

export function AlertDialogAction({ variant = "default", ...rest }: AlertDialogActionProps) {
  return <Button {...rest} variant={variant} />;
}

export function AlertDialogCancel(props: AlertDialogCancelProps) {
  return (
    <AlertDialogCloseTrigger asChild>
      <Button variant="outline" {...props} />
    </AlertDialogCloseTrigger>
  );
}
// #endregion

// #region Shorthand
export function AlertDialogShorthand({
  actions,
  description,
  title,
  trigger,
  ...rest
}: AlertDialogProps) {
  return (
    <AlertDialogRoot {...rest}>
      {trigger !== undefined && <AlertDialogTrigger asChild>{trigger}</AlertDialogTrigger>}

      <AlertDialogContent>
        {(title !== undefined || description !== undefined) && (
          <AlertDialogHeader>
            {title !== undefined && <AlertDialogTitle>{title}</AlertDialogTitle>}

            {description !== undefined && (
              <AlertDialogDescription>{description}</AlertDialogDescription>
            )}
          </AlertDialogHeader>
        )}

        {actions !== undefined && <AlertDialogFooter>{actions}</AlertDialogFooter>}
      </AlertDialogContent>
    </AlertDialogRoot>
  );
}
// #endregion

// #region Display Names
AlertDialogRoot.displayName = "AlertDialog.Root";
AlertDialogTrigger.displayName = "AlertDialog.Trigger";
AlertDialogContent.displayName = "AlertDialog.Content";
AlertDialogBody.displayName = "AlertDialog.Body";
AlertDialogHeader.displayName = "AlertDialog.Header";
AlertDialogTitle.displayName = "AlertDialog.Title";
AlertDialogDescription.displayName = "AlertDialog.Description";
AlertDialogCloseTrigger.displayName = "AlertDialog.CloseTrigger";
AlertDialogFooter.displayName = "AlertDialog.Footer";
AlertDialogAction.displayName = "AlertDialog.Action";
AlertDialogCancel.displayName = "AlertDialog.Cancel";
AlertDialogShorthand.displayName = "AlertDialog";
// #endregion
