// packages/react/src/components/alert/alert.tsx
import { ark } from "@ark-ui/react/factory";
import { type AlertRecipeSlot, type AlertVariantProps, alertRecipe } from "@pisagor/recipes/alert";
import type { ComponentProps, ReactNode } from "react";
import type { VariantClassNames } from "../../internal/types";
import { AlertContext, useAlert } from "./alert.context";

// #region Types
type AlertTitleProps = ComponentProps<typeof ark.div>;

type AlertDescriptionProps = ComponentProps<typeof ark.div>;

type AlertActionProps = ComponentProps<typeof ark.div>;

type AlertClassNames = VariantClassNames<AlertRecipeSlot>;

type AlertRootProps = Omit<ComponentProps<typeof ark.div>, "title"> & AlertVariantProps;

export interface AlertProps extends Omit<AlertRootProps, "children"> {
  /** Trailing action area. */
  action?: ReactNode;
  /** Description content. */
  description?: ReactNode;
  /** Leading icon, rendered as a direct child so the grid layout aligns. */
  icon?: ReactNode;
  /** Bold title line. */
  title?: ReactNode;
  /** Slot class names */
  classNames?: AlertClassNames;
  /** Extra props forwarded to the alert action element */
  actionProps?: Omit<AlertActionProps, "children" | "className">;
  /** Extra props forwarded to the alert description element */
  descriptionProps?: Omit<AlertDescriptionProps, "children" | "className">;
  /** Extra props forwarded to the alert title element */
  titleProps?: Omit<AlertTitleProps, "children" | "className">;
}
// #endregion

// #region Parts
export function AlertRoot({ variant, children, className, ...rest }: AlertRootProps) {
  const slots = alertRecipe({ variant });

  return (
    <AlertContext value={{ slots }}>
      <ark.div {...rest} className={slots.base({ className })} data-part="root" data-scope="alert">
        {children}
      </ark.div>
    </AlertContext>
  );
}

export function AlertTitle({ children, className, ...rest }: AlertTitleProps) {
  const { slots } = useAlert();

  return (
    <ark.div {...rest} className={slots.title({ className })} data-part="title" data-scope="alert">
      {children}
    </ark.div>
  );
}

export function AlertDescription({ children, className, ...rest }: AlertDescriptionProps) {
  const { slots } = useAlert();

  return (
    <ark.div
      {...rest}
      className={slots.description({ className })}
      data-part="description"
      data-scope="alert"
    >
      {children}
    </ark.div>
  );
}

export function AlertAction({ children, className, ...rest }: AlertActionProps) {
  const { slots } = useAlert();

  return (
    <ark.div
      {...rest}
      className={slots.action({ className })}
      data-part="action"
      data-scope="alert"
    >
      {children}
    </ark.div>
  );
}
// #endregion

// #region Shorthand
export function AlertShorthand({
  variant,
  action,
  actionProps,
  description,
  descriptionProps,
  icon,
  title,
  titleProps,
  className,
  classNames,
  ...rest
}: AlertProps) {
  return (
    <AlertRoot {...rest} className={className} variant={variant}>
      {icon}

      {title !== undefined && (
        <AlertTitle {...titleProps} className={classNames?.title}>
          {title}
        </AlertTitle>
      )}

      {description !== undefined && (
        <AlertDescription {...descriptionProps} className={classNames?.description}>
          {description}
        </AlertDescription>
      )}

      {action !== undefined && (
        <AlertAction {...actionProps} className={classNames?.action}>
          {action}
        </AlertAction>
      )}
    </AlertRoot>
  );
}
// #endregion

// #region Display Names
AlertRoot.displayName = "Alert.Root";
AlertTitle.displayName = "Alert.Title";
AlertDescription.displayName = "Alert.Description";
AlertAction.displayName = "Alert.Action";
AlertShorthand.displayName = "Alert";
// #endregion

// packages/solid/src/components/alert/alert.tsx
import { ark } from "@ark-ui/solid/factory";
import {
  type AlertRecipeSlot,
  type AlertVariantProps,
  alertRecipe,
} from "@pisagor/recipes/alert";
import { cn } from "@pisagor/utils";
import type { ComponentProps, JSX } from "solid-js";
import { Show, splitProps } from "solid-js";
import type { VariantClassNames } from "../../internal/types";
import { AlertContext, useAlert } from "./alert.context";

type AlertTitleProps = ComponentProps<typeof ark.div>;
type AlertDescriptionProps = ComponentProps<typeof ark.div>;
type AlertActionProps = ComponentProps<typeof ark.div>;
type AlertClassNames = VariantClassNames<AlertRecipeSlot>;

type AlertRootProps = Omit<ComponentProps<typeof ark.div>, "title"> &
  AlertVariantProps & {
    recipe?: typeof alertRecipe;
  };

export interface AlertProps extends Omit<AlertRootProps, "children"> {
  action?: JSX.Element;
  description?: JSX.Element;
  icon?: JSX.Element;
  title?: JSX.Element;
  classNames?: AlertClassNames;
  actionProps?: Omit<AlertActionProps, "children" | "class">;
  descriptionProps?: Omit<AlertDescriptionProps, "children" | "class">;
  titleProps?: Omit<AlertTitleProps, "children" | "class">;
}

export function AlertRoot(props: AlertRootProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "variant",
    "children",
    "recipe",
    "class",
  ]);
  const slots = () => (local.recipe ?? alertRecipe)({ variant: local.variant });

  return (
    <AlertContext value={{ slots: slots() }}>
      <ark.div
        {...rest}
        class={slots().base({ class: cn(local.class) })}
        data-part="root"
        data-scope="alert"
      >
        {local.children}
      </ark.div>
    </AlertContext>
  );
}

export function AlertTitle(props: AlertTitleProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useAlert();

  return (
    <ark.div
      {...rest}
      class={slots.title({ class: cn(local.class) })}
      data-part="title"
      data-scope="alert"
    >
      {local.children}
    </ark.div>
  );
}

export function AlertDescription(props: AlertDescriptionProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useAlert();

  return (
    <ark.div
      {...rest}
      class={slots.description({ class: cn(local.class) })}
      data-part="description"
      data-scope="alert"
    >
      {local.children}
    </ark.div>
  );
}

export function AlertAction(props: AlertActionProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useAlert();

  return (
    <ark.div
      {...rest}
      class={slots.action({ class: cn(local.class) })}
      data-part="action"
      data-scope="alert"
    >
      {local.children}
    </ark.div>
  );
}

export function AlertShorthand(props: AlertProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "variant",
    "action",
    "actionProps",
    "description",
    "descriptionProps",
    "icon",
    "title",
    "titleProps",
    "class",
    "classNames",
  ]);

  return (
    <AlertRoot {...rest} class={local.class} variant={local.variant}>
      {local.icon}
      <Show when={local.title !== undefined}>
        <AlertTitle {...local.titleProps} class={local.classNames?.title}>
          {local.title}
        </AlertTitle>
      </Show>
      <Show when={local.description !== undefined}>
        <AlertDescription
          {...local.descriptionProps}
          class={local.classNames?.description}
        >
          {local.description}
        </AlertDescription>
      </Show>
      <Show when={local.action !== undefined}>
        <AlertAction {...local.actionProps} class={local.classNames?.action}>
          {local.action}
        </AlertAction>
      </Show>
    </AlertRoot>
  );
}
