// packages/solid/src/components/hover-card/hover-card.tsx
import type {
  HoverCardArrowProps,
  HoverCardContentProps,
  HoverCardRootProps as HoverCardPrimitiveRootProps,
  HoverCardTriggerProps,
} from "@ark-ui/solid/hover-card";
import { HoverCard as HoverCardPrimitive } from "@ark-ui/solid/hover-card";
import type { HoverCardProps as BaseHoverCardRootProps } from "@pisagor/props";
import { hoverCardRecipe } from "@pisagor/recipes";
import type { JSX } from "solid-js";
import { splitProps } from "solid-js";
import { Portal } from "solid-js/web";
import { HoverCardContext, useHoverCard } from "./hover-card.context";

export interface HoverCardRootProps
  extends HoverCardPrimitiveRootProps,
    BaseHoverCardRootProps {}

export type HoverCardProps = HoverCardRootProps;

export function HoverCardRoot(props: HoverCardRootProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "closeDelay",
    "openDelay",
    "positioning",
    "children",
    "recipe",
  ]);
  const slots = () => (local.recipe ?? hoverCardRecipe)();

  return (
    <HoverCardContext value={{ slots: slots() }}>
      <HoverCardPrimitive.Root
        {...rest}
        closeDelay={local.closeDelay ?? 300}
        openDelay={local.openDelay ?? 600}
        positioning={local.positioning ?? { placement: "top" }}
      >
        {local.children}
      </HoverCardPrimitive.Root>
    </HoverCardContext>
  );
}

export function HoverCardTrigger(props: HoverCardTriggerProps): JSX.Element {
  return <HoverCardPrimitive.Trigger {...props} />;
}

export function HoverCardArrow(props: HoverCardArrowProps): JSX.Element {
  const [local, rest] = splitProps(props, ["style"]);
  const { slots } = useHoverCard();

  return (
    <HoverCardPrimitive.Arrow
      {...rest}
      style={{
        "--arrow-background": "var(--popover)",
        "--arrow-size": "calc(1.5 * var(--spacing))",
        ...(typeof local.style === "object" && local.style !== null
          ? local.style
          : {}),
      }}
    >
      <HoverCardPrimitive.ArrowTip class={slots.arrowTip()} />
    </HoverCardPrimitive.Arrow>
  );
}

export function HoverCardContent(props: HoverCardContentProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useHoverCard();

  return (
    <Portal>
      <HoverCardPrimitive.Positioner>
        <HoverCardPrimitive.Content
          {...rest}
          class={slots.content({ class: local.class })}
        >
          {local.children}
          <HoverCardArrow />
        </HoverCardPrimitive.Content>
      </HoverCardPrimitive.Positioner>
    </Portal>
  );
}

// packages/react/src/components/hover-card/hover-card.tsx
import { Portal } from "@ark-ui/react";
import type {
  HoverCardArrowProps,
  HoverCardContentProps,
  HoverCardRootProps as HoverCardPrimitiveRootProps,
  HoverCardTriggerProps,
} from "@ark-ui/react/hover-card";
import { HoverCard as HoverCardPrimitive } from "@ark-ui/react/hover-card";
import type { HoverCardProps as BaseHoverCardRootProps } from "@pisagor/props";
import { hoverCardRecipe } from "@pisagor/recipes";

import { HoverCardContext, useHoverCard } from "./hover-card.context";

// #region Types
export interface HoverCardRootProps
  extends HoverCardPrimitiveRootProps,
    BaseHoverCardRootProps {}

export type HoverCardProps = HoverCardRootProps;

// #endregion

// #region Parts
export function HoverCardRoot({
  closeDelay = 300,
  openDelay = 600,
  positioning = { placement: "top" },
  children,
  recipe = hoverCardRecipe,
  ...rest
}: HoverCardRootProps) {
  const slots = recipe();

  return (
    <HoverCardContext value={{ slots }}>
      <HoverCardPrimitive.Root
        {...rest}
        closeDelay={closeDelay}
        openDelay={openDelay}
        positioning={positioning}
      >
        {children}
      </HoverCardPrimitive.Root>
    </HoverCardContext>
  );
}

export function HoverCardTrigger(props: HoverCardTriggerProps) {
  return <HoverCardPrimitive.Trigger {...props} />;
}

export function HoverCardArrow({ style, ...rest }: HoverCardArrowProps) {
  const { slots } = useHoverCard();

  return (
    <HoverCardPrimitive.Arrow
      {...rest}
      style={{
        "--arrow-background": "var(--popover)",
        "--arrow-size": "calc(1.5 * var(--spacing))",
        ...style,
      }}
    >
      <HoverCardPrimitive.ArrowTip className={slots.arrowTip()} />
    </HoverCardPrimitive.Arrow>
  );
}

export function HoverCardContent({
  children,
  className,
  ...rest
}: HoverCardContentProps) {
  const { slots } = useHoverCard();

  return (
    <Portal>
      <HoverCardPrimitive.Positioner>
        <HoverCardPrimitive.Content
          {...rest}
          className={slots.content({ className })}
        >
          {children}

          <HoverCardArrow />
        </HoverCardPrimitive.Content>
      </HoverCardPrimitive.Positioner>
    </Portal>
  );
}
// #endregion

// #region Display Names
HoverCardRoot.displayName = "HoverCard";
HoverCardTrigger.displayName = "HoverCard.Trigger";
HoverCardArrow.displayName = "HoverCard.Arrow";
HoverCardContent.displayName = "HoverCard.Content";
// #endregion
