// packages/vue/examples/input-group/with-keyboard-shortcut.vue
<script lang="ts" setup>
import { Kbd } from "@pisagor/vue";
import { InputGroup } from "../../src/components/input-group";
</script>

<template>
  <InputGroup>
    <InputGroup.Input placeholder="Search..." />
    <InputGroup.Addon align="inline-end">
      <Kbd>⌘K</Kbd>
    </InputGroup.Addon>
  </InputGroup>
</template>

// packages/svelte/examples/input-group/with-keyboard-shortcut.svelte
<script lang="ts">
import { Kbd } from "@pisagor/svelte";
import { InputGroup } from "@pisagor/svelte/input-group";
</script>

<InputGroup>
      <InputGroup.Input placeholder="Search..." />
      <InputGroup.Addon align="inline-end">
        <Kbd>⌘K</Kbd>
      </InputGroup.Addon>
    </InputGroup>
