// packages/react/examples/badge/with-link.tsx
import { ArrowUpRightIcon, PlusCircleIcon } from "@phosphor-icons/react";
import { Badge } from "@pisagor/react";

export function WithLink() {
  return (
    <Badge>
      <a href="https://example.com/components">
        <PlusCircleIcon />
        New components <ArrowUpRightIcon />
      </a>
    </Badge>
  );
}

// packages/svelte/examples/badge/with-link.svelte
<script lang="ts">
import { Badge } from "@pisagor/svelte";
import ArrowUpRightIcon from "phosphor-svelte/lib/ArrowUpRightIcon";
import PlusCircleIcon from "phosphor-svelte/lib/PlusCircleIcon";
</script>

<Badge>
      <a href="https://example.com/components">
        <PlusCircleIcon />
        New components <ArrowUpRightIcon />
      </a>
    </Badge>
