// packages/svelte/examples/number-input/scrub.svelte
<script lang="ts">
import { NumberInput } from "@pisagor/svelte";
</script>

<NumberInput>
  <NumberInput.Scrubber>Quantity</NumberInput.Scrubber>
  <NumberInput.Control>
    <NumberInput.DecrementTrigger />
    <NumberInput.Input />
    <NumberInput.IncrementTrigger />
  </NumberInput.Control>
</NumberInput>

// packages/solid/examples/number-input/scrub.tsx
import { NumberInput } from "@pisagor/solid";

export function Scrub() {
  return (
    <NumberInput>
      <NumberInput.Scrubber>Quantity</NumberInput.Scrubber>
      <NumberInput.Control>
        <NumberInput.DecrementTrigger />
        <NumberInput.Input />
        <NumberInput.IncrementTrigger />
      </NumberInput.Control>
    </NumberInput>
  );
}
