// packages/svelte/examples/accordion/with-card.svelte
<script lang="ts">
import { Card } from "@pisagor/svelte";
import { Accordion } from "@pisagor/svelte/accordion";
import { faqItems } from "./helpers";
</script>

<Card>
      <Card.Header
        description="Common questions about our products, shipping, and returns."
        title="Product information"
      />
      <Card.Content>
        <Accordion items={faqItems()} />
      </Card.Content>
    </Card>

// packages/react/skills/react/assets/examples/accordion/with-card.tsx
import { Card } from "@pisagor/react";
import { Accordion } from "@pisagor/react/accordion";
import { faqItems } from "./helpers";

export function WithCard() {
  return (
    <Card>
      <Card.Header
        description="Common questions about our products, shipping, and returns."
        title="Product information"
      />
      <Card.Content>
        <Accordion items={faqItems()} />
      </Card.Content>
    </Card>
  );
}
