// packages/svelte/examples/announcement/compound.svelte
<script lang="ts">
import { Badge } from "@pisagor/svelte";
import { Announcement } from "@pisagor/svelte/announcement";
</script>

<Announcement.Root>
      <Badge>Release</Badge>

      <Announcement.Title>
        v2.1.0 — Dark mode, faster builds, and 12 new components
      </Announcement.Title>
    </Announcement.Root>

// packages/solid/examples/announcement/compound.tsx
import { Announcement, Badge } from "@pisagor/solid";
export function Compound() {
  return (
    <Announcement.Root>
      <Badge>Release</Badge>

      <Announcement.Title>
        v2.1.0 — Dark mode, faster builds, and 12 new components
      </Announcement.Title>
    </Announcement.Root>
  );
}
