// packages/svelte-form/src/fields/select-field.svelte
<script lang="ts">
import { Select } from "@pisagor/svelte";
import type { ComponentProps, Snippet } from "svelte";
import FieldShell from "../internal/field-shell.svelte";

type SelectProps = ComponentProps<typeof Select>;

interface SelectOption {
  label: string;
  value: string;
}

type Props = Omit<
  SelectProps,
  | "children"
  | "collection"
  | "invalid"
  | "name"
  | "onValueChange"
  | "value"
  | "items"
> & {
  class?: string | undefined;
  description?: string | undefined;
  error?: string | undefined;
  id?: string | undefined;
  invalid?: boolean | undefined;
  items: Array<SelectOption | string>;
  label?: string | undefined;
  labelAccessory?: Snippet | undefined;
  labelProps?: ComponentProps<typeof FieldShell>["labelProps"];
  name?: string | undefined;
  onBlur?: (() => void) | undefined;
  onValueChange?: ((value: string) => void) | undefined;
  orientation?: ComponentProps<typeof FieldShell>["orientation"];
  placeholder?: string | undefined;
  value?: string | undefined;
};

let {
  class: className,
  description,
  error,
  id,
  invalid,
  items,
  label,
  labelAccessory,
  labelProps,
  name,
  onBlur,
  onValueChange,
  orientation,
  placeholder = "Select an option",
  value,
  ...selectProps
}: Props = $props();

const selectValue = $derived(
  value !== undefined ? (value ? [value] : []) : undefined,
);

function handleValueChange(nextValue: string[] | string) {
  onValueChange?.(
    Array.isArray(nextValue) ? (nextValue.at(0) ?? "") : nextValue,
  );
}
</script>

<FieldShell
  class={className}
  {description}
  {error}
  {id}
  {invalid}
  {label}
  {labelAccessory}
  {labelProps}
  {orientation}
>
  <Select
    {...selectProps}
    {id}
    {invalid}
    {items}
    {name}
    onFocusOutside={onBlur}
    onValueChange={handleValueChange}
    {placeholder}
    value={selectValue}
  />
</FieldShell>

// packages/react-form/src/fields/select-field.tsx
import {
  createListCollection,
  Select,
  type SelectRootProps,
} from "@pisagor/react";
import {
  type FieldPresentationProps,
  FieldShell,
} from "../internal/field-shell";

// #region Types
interface SelectOption {
  label: string;
  value: string;
}

export interface SelectFieldProps
  extends FieldPresentationProps,
    Omit<
      SelectRootProps,
      "children" | "collection" | "invalid" | "name" | "onValueChange" | "value"
    > {
  name?: string;
  value?: string;
  items: Array<SelectOption | string>;
  placeholder?: string;
  onBlur?: () => void;
  onValueChange?: (value: string) => void;
}
// #endregion

// #region Component
export function SelectField({
  orientation,
  id,
  invalid,
  name,
  value,
  description,
  error,
  items,
  label,
  labelAccessory,
  placeholder = "Select an option",
  onBlur,
  onValueChange,
  className,
  labelProps,
  ...selectProps
}: SelectFieldProps) {
  const normalizedItems = items.map((item) =>
    typeof item === "string" ? { label: item, value: item } : item,
  );
  const collection = createListCollection({ items: normalizedItems });

  return (
    <FieldShell
      className={className}
      description={description}
      error={error}
      id={id}
      invalid={invalid}
      label={label}
      labelAccessory={labelAccessory}
      labelProps={labelProps}
      orientation={orientation}
    >
      <Select.Root
        {...selectProps}
        {...(value !== undefined ? { value: value ? [value] : [] } : {})}
        collection={collection}
        invalid={invalid}
        name={name}
        onFocusOutside={onBlur}
        onValueChange={(nextValue) => {
          onValueChange?.(
            Array.isArray(nextValue) ? (nextValue.at(0) ?? "") : nextValue,
          );
        }}
      >
        <Select.Trigger id={id}>
          <Select.ValueText placeholder={placeholder} />
        </Select.Trigger>
        <Select.Content>
          {normalizedItems.map((item) => (
            <Select.Item item={item} key={item.value}>
              {item.label}
            </Select.Item>
          ))}
        </Select.Content>
      </Select.Root>
    </FieldShell>
  );
}
// #endregion
