// packages/svelte/src/components/aspect-ratio/aspect-ratio.svelte
<script lang="ts">
import { Ark } from "@ark-ui/svelte/factory";
import type { AspectRatioProps as BaseAspectRatioProps } from "@pisagor/props";
import { aspectRatioRecipe } from "@pisagor/recipes";
import type { HTMLAttributes } from "svelte/elements";

type Props = Omit<HTMLAttributes<HTMLElement>, "class"> & {
  children?: import("svelte").Snippet;
  class?: string | undefined;
} & BaseAspectRatioProps;

let {
  recipe = aspectRatioRecipe,
  class: className,
  children,
  ...rest
}: Props = $props();
</script>

<Ark
  as="div"
  {...rest}
  class={recipe({ class: className })}
  data-part="root"
  data-scope="aspect-ratio"
>
  {@render children?.()}
</Ark>

// packages/react/src/components/aspect-ratio/aspect-ratio.tsx
import { ark } from "@ark-ui/react/factory";
import type { AspectRatioProps as BaseAspectRatioProps } from "@pisagor/props";
import { aspectRatioRecipe } from "@pisagor/recipes";
import type { ComponentProps } from "react";

// #region Types
export interface AspectRatioProps
  extends ComponentProps<typeof ark.div>,
    BaseAspectRatioProps {}
// #endregion

// #region Component
export function AspectRatio({
  recipe = aspectRatioRecipe,
  className,
  ...rest
}: AspectRatioProps) {
  return (
    <ark.div
      {...rest}
      className={recipe({ className })}
      data-part="root"
      data-scope="aspect-ratio"
    />
  );
}
// #endregion
