// packages/react-ui/src/components/collapsible/collapsible.tsx
import { Collapsible as CollapsiblePrimitive } from "@ark-ui/react/collapsible";
import { CaretDownIcon } from "@phosphor-icons/react";
import { collapsibleVariants } from "@pisagor/recipes/collapsible";
import type { ComponentProps } from "react";
import { useMemo } from "react";
import { CollapsibleContext, useCollapsible } from "./collapsible.context";

// #region Types
export interface CollapsibleRootProps extends ComponentProps<typeof CollapsiblePrimitive.Root> {}

export type CollapsibleTriggerProps = ComponentProps<typeof CollapsiblePrimitive.Trigger>;

export type CollapsibleContentProps = ComponentProps<typeof CollapsiblePrimitive.Content>;

export type CollapsibleIndicatorProps = ComponentProps<typeof CollapsiblePrimitive.Indicator>;
// #endregion

// #region Parts
export function CollapsibleRoot({
  collapsedHeight,
  lazyMount,
  unmountOnExit,
  className,
  children,
  ...rest
}: CollapsibleRootProps) {
  const slots = useMemo(() => collapsibleVariants(), []);

  return (
    <CollapsibleContext value={{ slots }}>
      <CollapsiblePrimitive.Root
        {...rest}
        className={slots.base({ className })}
        collapsedHeight={collapsedHeight}
        data-partial-collapse={collapsedHeight ? "" : undefined}
        lazyMount={collapsedHeight ? false : lazyMount}
        unmountOnExit={collapsedHeight ? false : unmountOnExit}
      >
        {children}
      </CollapsiblePrimitive.Root>
    </CollapsibleContext>
  );
}

export function CollapsibleTrigger({ className, ...rest }: CollapsibleTriggerProps) {
  const { slots } = useCollapsible();

  return <CollapsiblePrimitive.Trigger {...rest} className={slots.trigger({ className })} />;
}

export function CollapsibleContent({ className, children, ...rest }: CollapsibleContentProps) {
  const { slots } = useCollapsible();

  return (
    <CollapsiblePrimitive.Content {...rest} className={slots.content()}>
      <div className={className}>{children}</div>
    </CollapsiblePrimitive.Content>
  );
}

export function CollapsibleIndicator({ className, ...rest }: CollapsibleIndicatorProps) {
  const { slots } = useCollapsible();

  return (
    <CollapsiblePrimitive.Indicator {...rest} className={slots.indicator({ className })}>
      <CaretDownIcon className={slots.icon()} />
    </CollapsiblePrimitive.Indicator>
  );
}
// #endregion

// #region Display Names
CollapsibleRoot.displayName = "Collapsible";
CollapsibleTrigger.displayName = "Collapsible.Trigger";
CollapsibleContent.displayName = "Collapsible.Content";
CollapsibleIndicator.displayName = "Collapsible.Indicator";
// #endregion

// packages/solid/src/components/collapsible/collapsible.tsx
import {
  type CollapsibleContentProps,
  type CollapsibleIndicatorProps,
  Collapsible as CollapsiblePrimitive,
  type CollapsibleRootProps as CollapsiblePrimitiveRootProps,
  type CollapsibleTriggerProps,
} from "@ark-ui/solid/collapsible";
import { collapsibleRecipe } from "@pisagor/recipes/collapsible";
import { cn } from "@pisagor/utils";
import type { JSX } from "solid-js";
import { splitProps } from "solid-js";
import { CaretDownIcon } from "../../internal/icons";
import { CollapsibleContext, useCollapsible } from "./collapsible.context";

export interface CollapsibleRootProps extends CollapsiblePrimitiveRootProps {
  recipe?: typeof collapsibleRecipe;
}

export function CollapsibleRoot(props: CollapsibleRootProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "lazyMount",
    "unmountOnExit",
    "children",
    "collapsedHeight",
    "recipe",
    "class",
  ]);
  const slots = () => (local.recipe ?? collapsibleRecipe)();
  const collapsedHeight = () => local.collapsedHeight;

  return (
    <CollapsibleContext value={{ slots: slots() }}>
      <CollapsiblePrimitive.Root
        {...rest}
        class={slots().base({ class: cn(local.class) })}
        collapsedHeight={collapsedHeight()}
        data-partial-collapse={collapsedHeight() ? "" : undefined}
        lazyMount={collapsedHeight() ? false : local.lazyMount}
        unmountOnExit={collapsedHeight() ? false : local.unmountOnExit}
      >
        {local.children}
      </CollapsiblePrimitive.Root>
    </CollapsibleContext>
  );
}

export function CollapsibleTrigger(props: CollapsibleTriggerProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useCollapsible();
  return (
    <CollapsiblePrimitive.Trigger {...rest} class={slots.trigger({ class: cn(local.class) })} />
  );
}

export function CollapsibleContent(props: CollapsibleContentProps): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useCollapsible();
  return (
    <CollapsiblePrimitive.Content {...rest} class={slots.content()}>
      <div class={local.class}>{local.children}</div>
    </CollapsiblePrimitive.Content>
  );
}

export function CollapsibleIndicator(props: CollapsibleIndicatorProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useCollapsible();
  return (
    <CollapsiblePrimitive.Indicator {...rest} class={slots.indicator({ class: cn(local.class) })}>
      <CaretDownIcon class={slots.icon()} />
    </CollapsiblePrimitive.Indicator>
  );
}
