// packages/react/src/components/button-group/examples/nested.tsx
import {
  BracketsCurlyIcon,
  ImageSquareIcon,
  TextBIcon,
  TextItalicIcon,
  TextUnderlineIcon,
} from "@phosphor-icons/react";
import { Button } from "@pisagor/react";
import { ButtonGroup } from "..";
export function Nested() {
  return (
    <ButtonGroup>
      <ButtonGroup>
        <Button aria-label="Italic" size="icon-md" variant="outline">
          <TextItalicIcon />
        </Button>
        <Button aria-label="Bold" size="icon-md" variant="outline">
          <TextBIcon />
        </Button>
        <Button aria-label="Underline" size="icon-md" variant="outline">
          <TextUnderlineIcon />
        </Button>
      </ButtonGroup>
      <ButtonGroup>
        <Button aria-label="Image" size="icon-md" variant="outline">
          <ImageSquareIcon />
        </Button>
        <Button aria-label="Code" size="icon-md" variant="outline">
          <BracketsCurlyIcon />
        </Button>
      </ButtonGroup>
    </ButtonGroup>
  );
}

// packages/vue/examples/button-group/nested.vue
<script lang="ts" setup>
import {
  PhBracketsCurly,
  PhImageSquare,
  PhTextB,
  PhTextItalic,
  PhTextUnderline,
} from "@phosphor-icons/vue";
import { Button, ButtonGroup } from "@pisagor/vue";
</script>

<template>
  <ButtonGroup>
    <ButtonGroup>
      <Button size="icon-md" variant="outline">
        <PhTextItalic />
      </Button>
      <Button size="icon-md" variant="outline">
        <PhTextB />
      </Button>
      <Button size="icon-md" variant="outline">
        <PhTextUnderline />
      </Button>
    </ButtonGroup>
    <ButtonGroup>
      <Button size="icon-md" variant="outline">
        <PhImageSquare />
      </Button>
      <Button size="icon-md" variant="outline">
        <PhBracketsCurly />
      </Button>
    </ButtonGroup>
  </ButtonGroup>
</template>
