// packages/svelte/examples/file-upload/directory-upload.svelte
<script lang="ts">
import { Button, FileUpload } from "@pisagor/svelte";
import FolderIcon from "phosphor-svelte/lib/FolderIcon";
</script>

<FileUpload directory>
  <div class="flex justify-center">
    <FileUpload.Trigger>
      {#snippet asChild(
        props: any,
      )}
        <Button {...props()} size="sm" variant="outline">
          <FolderIcon />
          Select folder
        </Button>
      {/snippet}
    </FileUpload.Trigger>
    <FileUpload.List />
  </div>
</FileUpload>

// packages/react/src/components/file-upload/examples/directory-upload.tsx
import { FolderIcon } from "@phosphor-icons/react";
import { Button } from "@pisagor/react";
import { FileUpload } from "..";
export function DirectoryUpload() {
  return (
    <FileUpload directory>
      <div className="flex justify-center">
        <FileUpload.Trigger asChild>
          <Button size="sm" variant="outline">
            <FolderIcon />
            Select folder
          </Button>
        </FileUpload.Trigger>
        <FileUpload.List />
      </div>
    </FileUpload>
  );
}
