// packages/svelte/examples/highlight/search-query.svelte
<script lang="ts">
import { Highlight, Input } from "@pisagor/svelte";

const searchResults = ["Spotlight bulb", "Spot cleaner", "Spot ceiling"];
let query = $state("spot");
</script>

<div class="flex flex-col gap-2">
  <Input
    aria-label="Search"
    oninput={(e) => (query = e.currentTarget.value)}
    placeholder="Search..."
    value={query}
  />
  <div class="space-y-2">
    <p class="text-muted-foreground text-sm">
      Search result for: {query || "(empty)"}
    </p>
    <ul class="space-y-1">
      {#each searchResults as item}
        <li class="text-base text-foreground">
          {#if query}
            <Highlight ignoreCase {query} text={item} />
          {:else}
            {item}
          {/if}
        </li>
      {/each}
    </ul>
  </div>
</div>

// packages/react/examples/highlight/search-query.tsx
import { Highlight, Input } from "@pisagor/react";
import { useState } from "react";
export function SearchQuery() {
  const searchResults = ["Spotlight bulb", "Spot cleaner", "Spot ceiling"];
  const [query, setQuery] = useState("spot");

  return (
    <div className="flex flex-col gap-2">
      <Input
        aria-label="Search"
        onChange={(e) => setQuery(e.target.value)}
        placeholder="Search..."
        value={query}
      />
      <div className="space-y-2">
        <p className="text-muted-foreground text-sm">
          Search result for: {query || "(empty)"}
        </p>
        <ul className="space-y-1">
          {searchResults.map((item) => (
            <li className="text-base text-foreground" key={item}>
              {query ? (
                <Highlight ignoreCase query={query} text={item} />
              ) : (
                item
              )}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
