// packages/react/src/components/progress/progress.tsx
import type {
  ProgressRootProps as ProgressPrimitiveRootProps,
  ProgressRangeProps,
  ProgressTrackProps,
  ProgressValueTextProps,
} from "@ark-ui/react/progress";
import { Progress as ProgressPrimitive } from "@ark-ui/react/progress";
import { type ProgressSlots, progressRecipe } from "@pisagor/recipes/progress";
import type { ComponentProps, ReactNode } from "react";
import type { VariantClassNames } from "../../internal/types";
import { Field } from "../field";
import { ProgressContext, useProgress } from "./progress.context";

// #region Types
type ProgressHeaderProps = ComponentProps<"div">;

type ProgressClassNames = VariantClassNames<ProgressSlots>;

type ProgressRootProps = Omit<ProgressPrimitiveRootProps, "value">;

export interface ProgressProps extends Omit<ProgressRootProps, "children"> {
  /**
   * Whether to show indeterminate progress.
   *
   * @defaultValue false
   */
  indeterminate?: boolean;
  /** When true, renders the numeric value text beside the label. */
  isValueVisible?: boolean;
  /**
   * The value of the progress bar
   *
   * @defaultValue 0
   */
  value?: number;
  children?: ReactNode;
  /** Optional label rendered above the progress bar. */
  label?: string;
  /** Slot class names */
  classNames?: ProgressClassNames;
  /** Extra props forwarded to the progress range element */
  rangeProps?: Omit<ProgressRangeProps, "children" | "className">;
  /** Extra props forwarded to the progress track element */
  trackProps?: Omit<ProgressTrackProps, "children" | "className">;
  /** Extra props forwarded to the progress value text element */
  valueProps?: Omit<ProgressValueTextProps, "children" | "className">;
}
// #endregion

// #region Parts
function ProgressRoot({
  orientation = "horizontal",
  children,
  className,
  ...rest
}: ProgressRootProps & { value?: number | null }) {
  const slots = progressRecipe();

  return (
    <ProgressContext value={{ slots }}>
      <ProgressPrimitive.Root
        {...rest}
        className={slots.base({ className })}
        orientation={orientation}
      >
        {children}
      </ProgressPrimitive.Root>
    </ProgressContext>
  );
}

function ProgressHeader({ children, className, ...rest }: ProgressHeaderProps) {
  const { slots } = useProgress();

  return (
    <div {...rest} className={slots.header({ className })}>
      {children}
    </div>
  );
}

function ProgressValue({ className, ...rest }: ProgressValueTextProps) {
  const { slots } = useProgress();

  return <ProgressPrimitive.ValueText {...rest} className={slots.value({ className })} />;
}

function ProgressTrack({ children, className, ...rest }: ProgressTrackProps) {
  const { slots } = useProgress();

  return (
    <ProgressPrimitive.Track {...rest} className={slots.track({ className })}>
      {children}
    </ProgressPrimitive.Track>
  );
}

function ProgressRange({ className, ...rest }: ProgressRangeProps) {
  const { slots } = useProgress();

  return <ProgressPrimitive.Range {...rest} className={slots.range({ className })} />;
}
// #endregion

// #region Closed
export function Progress({
  orientation = "horizontal",
  indeterminate = false,
  isValueVisible,
  value,
  children,
  label,
  rangeProps,
  trackProps,
  valueProps,
  className,
  classNames,
  ...rest
}: ProgressProps) {
  const showHeader = label || isValueVisible;

  return (
    <ProgressRoot
      {...rest}
      className={className}
      orientation={orientation}
      value={indeterminate ? null : value}
    >
      {showHeader && (
        <ProgressHeader className={classNames?.header}>
          {label && <Field.Label>{label}</Field.Label>}
          {isValueVisible && (
            <Field.Label asChild>
              <ProgressValue {...valueProps} className={classNames?.value} />
            </Field.Label>
          )}
        </ProgressHeader>
      )}

      {children}

      <ProgressTrack {...trackProps} className={classNames?.track}>
        <ProgressRange {...rangeProps} className={classNames?.range} />
      </ProgressTrack>
    </ProgressRoot>
  );
}
// #endregion

// #region Display Names
ProgressRoot.displayName = "Progress.Root";
ProgressHeader.displayName = "Progress.Header";
ProgressValue.displayName = "Progress.Value";
ProgressTrack.displayName = "Progress.Track";
ProgressRange.displayName = "Progress.Range";
Progress.displayName = "Progress";
// #endregion

// packages/svelte/src/components/progress/progress.svelte
<script lang="ts">
import type {
  ProgressRangeProps,
  ProgressRootProps,
  ProgressTrackProps,
  ProgressValueTextProps,
} from "@ark-ui/svelte/progress";
import type { ProgressProps as BaseProgressProps } from "@pisagor/props";
import type { ProgressRecipeSlot } from "@pisagor/recipes";
import type { Snippet } from "svelte";
import type { VariantClassNames } from "../../internal/types";
import { Field } from "../field";
import ProgressHeader from "./progress-header.svelte";
import ProgressRange from "./progress-range.svelte";
import ProgressRoot from "./progress-root.svelte";
import ProgressTrack from "./progress-track.svelte";
import ProgressValue from "./progress-value.svelte";

type Props = Omit<ProgressRootProps, "children" | "value"> & {
  children?: Snippet;
  /** Slot class names */
  classNames?: VariantClassNames<ProgressRecipeSlot>;
  /**
   * Whether to show indeterminate progress.
   * @defaultValue false
   */
  indeterminate?: boolean;
  /** When true, renders the numeric value text beside the label. */
  isValueVisible?: boolean;
  /** Optional label rendered above the progress bar. */
  label?: string;
  /** Extra props forwarded to the progress range element */
  rangeProps?: Omit<ProgressRangeProps, "children" | "class">;
  /** Extra props forwarded to the progress track element */
  trackProps?: Omit<ProgressTrackProps, "children" | "class">;
  /**
   * The value of the progress bar
   * @defaultValue 0
   */
  value?: number;
  /** Extra props forwarded to the progress value text element */
  valueProps?: Omit<ProgressValueTextProps, "children" | "class">;
} & BaseProgressProps;

let {
  orientation = "horizontal",
  indeterminate = false,
  isValueVisible,
  defaultValue = 0,
  value,
  children,
  label,
  rangeProps,
  trackProps,
  valueProps,
  classNames,
  ...rest
}: Props = $props();

const showHeader = $derived(Boolean(label || isValueVisible));
</script>

<ProgressRoot
  {...rest}
  {defaultValue}
  {orientation}
  value={indeterminate ? null : value}
>
  {#if showHeader}
    <ProgressHeader class={classNames?.header}>
      {#if label}
        <Field.Label>{label}</Field.Label>
      {/if}
      {#if isValueVisible}
        <Field.Label>
          {#snippet asChild(
            props,
          )}
            <ProgressValue
              {...props({ ...valueProps, class: classNames?.value })}
            />
          {/snippet}
        </Field.Label>
      {/if}
    </ProgressHeader>
  {/if}

  {@render children?.()}

  <ProgressTrack {...trackProps} class={classNames?.track}>
    <ProgressRange {...rangeProps} class={classNames?.range} />
  </ProgressTrack>
</ProgressRoot>
