// packages/solid/examples/input/clearable.tsx
import { Input } from "@pisagor/solid";
import { createSignal } from "solid-js";
export function Clearable() {
  const [value, setValue] = createSignal("Hello world");

  return (
    <Input
      clearable
      onChange={({ target }) => setValue(target.value)}
      placeholder="Type to search..."
      value={value()}
    />
  );
}

// packages/react/skills/react/assets/examples/input/clearable.tsx
import { Input } from "@pisagor/react/input";
import { useState } from "react";

export function Clearable() {
  const [value, setValue] = useState("Hello world");

  return (
    <Input
      clearable
      onChange={({ target }) => setValue(target.value)}
      placeholder="Type to search..."
      value={value}
    />
  );
}
