// packages/react/src/components/scrollspy/examples/horizontal.tsx
import { Button, ScrollArea } from "@pisagor/react";
import { useRef } from "react";
import { Scrollspy } from "..";
import { horizontalSections } from "./helpers";
export function Horizontal() {
  const parentRef = useRef<HTMLDivElement>(null);

  return (
    <div className="w-full space-y-5">
      <div className="flex w-full gap-2">
        <Scrollspy className="flex gap-2.5" offset={50} targetRef={parentRef}>
          {horizontalSections.map((item) => (
            <Button
              className="data-[active=true]:bg-primary data-[active=true]:text-primary-foreground"
              data-scrollspy-anchor={item.id}
              key={item.id}
              variant="outline"
            >
              {item.label}
            </Button>
          ))}
        </Scrollspy>
      </div>

      <div className="w-full" ref={parentRef}>
        <ScrollArea className="h-100 grow">
          <div className="space-y-8">
            {horizontalSections.map((item) => (
              <div className="space-y-2.5" id={item.id} key={item.id}>
                <h3 className="text-base text-foreground">{item.label}</h3>
                <div className="h-87.5 rounded-2xl bg-muted" />
              </div>
            ))}
          </div>
        </ScrollArea>
      </div>
    </div>
  );
}

// packages/svelte/examples/scrollspy/horizontal.svelte
<script lang="ts">
import { Button, ScrollArea, Scrollspy } from "@pisagor/svelte";
import { horizontalSections } from "./helpers";

let parentEl = $state<HTMLDivElement | null>(null);
</script>

<div class="w-full space-y-5">
  <div class="flex w-full gap-2">
    <Scrollspy class="flex gap-2.5" offset={50} targetRef={() => parentEl}>
      {#each horizontalSections as item}
        <Button
          class="data-[active=true]:bg-primary data-[active=true]:text-primary-foreground"
          data-scrollspy-anchor={item.id}
          variant="outline"
        >
          {item.label}
        </Button>
      {/each}
    </Scrollspy>
  </div>

  <div class="w-full" bind:this={parentEl}>
    <ScrollArea class="h-100 grow">
      <div class="space-y-8">
        {#each horizontalSections as item}
          <div class="space-y-2.5" id={item.id}>
            <h3 class="text-base text-foreground">{item.label}</h3>
            <div class="h-87.5 rounded-2xl bg-muted"></div>
          </div>
        {/each}
      </div>
    </ScrollArea>
  </div>
</div>
