// packages/vue/src/components/password-input/examples/controlled-visibility.vue
<script setup lang="ts">
import { ref } from "vue";
import { PasswordInput } from "..";

const visible = ref(false);
const onVisibilityChange = (details) => setVisible(details.visible);
</script>

<template>
  <PasswordInput @visibility-change="onVisibilityChange" placeholder="Enter password" :visible="visible" />
</template>

// packages/react/src/components/password-input/examples/controlled-visibility.tsx
import { useState } from "react";
import { PasswordInput } from "..";

export function ControlledVisibility() {
  const [visible, setVisible] = useState(false);

  return (
    <PasswordInput
      onVisibilityChange={(details) => setVisible(details.visible)}
      placeholder="Enter password"
      visible={visible}
    />
  );
}
