// packages/solid/examples/password-input/controlled-visibility.tsx
/** @jsxImportSource solid-js */

import { PasswordInput } from "@pisagor/solid/password-input";
import { createSignal } from "solid-js";
export function ControlledVisibility() {
  const [visible, setVisible] = createSignal(false);

  return (
    <PasswordInput
      onVisibilityChange={(details) => setVisible(details.visible)}
      placeholder="Enter password"
      visible={visible()}
    />
  );
}

// packages/react/skills/react/assets/examples/password-input/controlled-visibility.tsx
import { PasswordInput } from "@pisagor/react/password-input";
import { useState } from "react";

export function ControlledVisibility() {
  const [visible, setVisible] = useState(false);

  return (
    <PasswordInput
      onVisibilityChange={(details) => setVisible(details.visible)}
      placeholder="Enter password"
      visible={visible}
    />
  );
}
