// packages/react/src/components/tags-input/tags-input.tsx
import type {
  TagsInputClearTriggerProps,
  TagsInputInputProps,
  TagsInputItemInputProps,
  TagsInputItemPreviewProps,
  TagsInputItemTextProps,
  TagsInputControlProps as TagsInputPrimitiveControlProps,
  TagsInputItemProps as TagsInputPrimitiveItemProps,
  TagsInputRootProps as TagsInputPrimitiveRootProps,
  TagsInputRootProviderProps as TagsInputPrimitiveRootProviderProps,
} from "@ark-ui/react/tags-input";
import {
  TagsInput as TagsInputPrimitive,
  useTagsInputContext,
} from "@ark-ui/react/tags-input";
import { XIcon } from "@phosphor-icons/react";
import type {
  TagsInputItemProps as TagsInputItemSharedProps,
  TagsInputProps as TagsInputRootProviderSharedProps,
  TagsInputProps as TagsInputSharedProps,
} from "@pisagor/props";
import { tagsInputItemRecipe, tagsInputRecipe } from "@pisagor/recipes";
import type { ComponentProps } from "react";
import { InputGroup, type InputGroupProps } from "../input-group";
import {
  TagsInputItemContext,
  TagsInputSlotsContext,
  useTagsInput,
  useTagsInputItem,
} from "./tags-input.context";

// #region Types
export type TagsInputRootProps = Omit<
  TagsInputPrimitiveRootProps,
  "onValueChange"
> &
  Pick<InputGroupProps, "size" | "variant">;

export interface TagsInputProps
  extends TagsInputRootProps,
    TagsInputSharedProps {
  /**
   * Whether to show the clear button.
   *
   * @defaultValue false
   */
  clearable?: boolean;
  /** Placeholder for the shorthand input. Defaults to empty. */
  placeholder?: string;
  onValueChange?: (value: string[]) => void;
}

export interface TagsInputControlProps
  extends TagsInputPrimitiveControlProps,
    Pick<InputGroupProps, "size" | "variant"> {
  /**
   * Whether to show the clear button.
   *
   * @defaultValue false
   */
  clearable?: boolean;
}

export interface TagsInputItemProps
  extends TagsInputPrimitiveItemProps,
    Pick<InputGroupProps, "size">,
    TagsInputItemSharedProps {
  /**
   * Whether to show the clear trigger.
   *
   * @defaultValue false
   */
  showDelete?: boolean;
}

export interface TagsInputRootProviderProps
  extends TagsInputPrimitiveRootProviderProps,
    Pick<InputGroupProps, "size">,
    TagsInputRootProviderSharedProps {
  /**
   * Whether to show the clear button.
   *
   * @defaultValue false
   */
  clearable?: boolean;
}

export type TagsInputItemDeleteTriggerProps = ComponentProps<
  typeof TagsInputPrimitive.ItemDeleteTrigger
>;

// #endregion

// #region Parts
export const TagsInputContext = TagsInputPrimitive.Context;

export function TagsInputRoot({
  size = "md",
  variant,
  clearable,
  tabIndex,
  children,
  editable = false,
  placeholder,
  onValueChange,
  recipe = tagsInputRecipe,
  className,
  ...rest
}: TagsInputProps) {
  const slots = recipe();

  return (
    <TagsInputSlotsContext value={{ slots }}>
      <TagsInputPrimitive.Root
        {...rest}
        className={slots.base({ className })}
        data-size={size}
        editable={editable}
        onValueChange={
          onValueChange ? (details) => onValueChange(details.value) : undefined
        }
      >
        <TagsInputControl clearable={clearable} variant={variant}>
          <TagsInputPrimitive.Context>
            {(api) =>
              api.value.map((value, index) => (
                <TagsInputItem index={index} key={value} value={value} />
              ))
            }
          </TagsInputPrimitive.Context>
          {children}
          <TagsInputInput placeholder={placeholder} />
        </TagsInputControl>

        <TagsInputPrimitive.HiddenInput tabIndex={tabIndex} />
      </TagsInputPrimitive.Root>
    </TagsInputSlotsContext>
  );
}

export function TagsInputControl({
  size,
  variant,
  clearable = false,
  children,
  className,
  ...rest
}: TagsInputControlProps) {
  const api = useTagsInputContext();
  const { slots } = useTagsInput();

  return (
    <TagsInputPrimitive.Control asChild>
      <InputGroup
        {...rest}
        className={slots.control({ className })}
        size={size}
        variant={variant}
      >
        {children}
        {clearable && api.value.length > 0 && (
          <TagsInputClearTrigger aria-label="Clear all tags" />
        )}
      </InputGroup>
    </TagsInputPrimitive.Control>
  );
}

export function TagsInputItem({
  showDelete = true,
  children,
  recipe = tagsInputItemRecipe,
  className,
  ...rest
}: TagsInputItemProps) {
  const slots = recipe();

  return (
    <TagsInputItemContext value={{ slots }}>
      <TagsInputPrimitive.Item {...rest} className={slots.base({ className })}>
        <TagsInputItemPreview>
          <TagsInputItemText>{children}</TagsInputItemText>
          {showDelete && <TagsInputItemDeleteTrigger />}
        </TagsInputItemPreview>
        <TagsInputItemInput />
      </TagsInputPrimitive.Item>
    </TagsInputItemContext>
  );
}

export function TagsInputItemPreview({
  className,
  ...rest
}: TagsInputItemPreviewProps) {
  const { slots } = useTagsInputItem();

  return (
    <TagsInputPrimitive.ItemPreview
      {...rest}
      className={slots.preview({ className })}
    />
  );
}

export function TagsInputItemText({
  className,
  ...rest
}: TagsInputItemTextProps) {
  const { slots } = useTagsInputItem();

  return (
    <TagsInputPrimitive.ItemText
      {...rest}
      className={slots.text({ className })}
    />
  );
}

export function TagsInputItemDeleteTrigger({
  children,
  className,
  ...rest
}: TagsInputItemDeleteTriggerProps) {
  const { slots } = useTagsInputItem();

  return (
    <TagsInputPrimitive.ItemDeleteTrigger {...rest} asChild>
      <InputGroup.Button
        aria-label="Remove tag"
        className={slots.delete({ className })}
        size="icon-xs"
        variant="ghost"
      >
        {children ?? <XIcon aria-hidden />}
      </InputGroup.Button>
    </TagsInputPrimitive.ItemDeleteTrigger>
  );
}

export function TagsInputItemInput(props: TagsInputItemInputProps) {
  const { slots } = useTagsInputItem();

  return (
    <TagsInputPrimitive.ItemInput {...props} asChild>
      <InputGroup.Input className={slots.input()} />
    </TagsInputPrimitive.ItemInput>
  );
}

export function TagsInputInput(props: TagsInputInputProps) {
  const { slots } = useTagsInput();

  return (
    <TagsInputPrimitive.Input {...props} asChild>
      <InputGroup.Input className={slots.input()} />
    </TagsInputPrimitive.Input>
  );
}

export function TagsInputClearTrigger({
  children,
  className,
  ...rest
}: TagsInputClearTriggerProps) {
  const { slots } = useTagsInput();

  return (
    <TagsInputPrimitive.ClearTrigger {...rest} asChild>
      <InputGroup.Button
        aria-label="Clear"
        className={slots.clearTrigger({ className })}
        size="icon-xs"
        variant="ghost"
      >
        {children ?? <XIcon aria-hidden />}
      </InputGroup.Button>
    </TagsInputPrimitive.ClearTrigger>
  );
}

export function TagsInputRootProvider({
  size = "md",
  clearable,
  children,
  recipe = tagsInputRecipe,
  className,
  ...rest
}: TagsInputRootProviderProps) {
  const slots = recipe();

  return (
    <TagsInputSlotsContext value={{ slots }}>
      <TagsInputPrimitive.RootProvider
        {...rest}
        className={slots.base({ className })}
        data-size={size}
      >
        <TagsInputControl clearable={clearable}>{children}</TagsInputControl>
        <TagsInputPrimitive.HiddenInput />
      </TagsInputPrimitive.RootProvider>
    </TagsInputSlotsContext>
  );
}
// #endregion

// #region Display Names
TagsInputRoot.displayName = "TagsInput";
TagsInputControl.displayName = "TagsInput.Control";
TagsInputItem.displayName = "TagsInput.Item";
TagsInputItemPreview.displayName = "TagsInput.ItemPreview";
TagsInputItemText.displayName = "TagsInput.ItemText";
TagsInputItemDeleteTrigger.displayName = "TagsInput.ItemDeleteTrigger";
TagsInputItemInput.displayName = "TagsInput.ItemInput";
TagsInputInput.displayName = "TagsInput.Input";
TagsInputClearTrigger.displayName = "TagsInput.ClearTrigger";
TagsInputRootProvider.displayName = "TagsInput.RootProvider";
// #endregion

// packages/solid/src/components/tags-input/tags-input.tsx
import type {
  TagsInputClearTriggerProps,
  TagsInputInputProps,
  TagsInputItemInputProps,
  TagsInputItemPreviewProps,
  TagsInputItemTextProps,
  TagsInputControlProps as TagsInputPrimitiveControlProps,
  TagsInputItemProps as TagsInputPrimitiveItemProps,
  TagsInputRootProps as TagsInputPrimitiveRootProps,
  TagsInputRootProviderProps as TagsInputPrimitiveRootProviderProps,
} from "@ark-ui/solid/tags-input";
import {
  TagsInput as TagsInputPrimitive,
  useTagsInputContext,
} from "@ark-ui/solid/tags-input";
import type {
  TagsInputItemProps as TagsInputItemSharedProps,
  TagsInputProps as TagsInputSharedProps,
} from "@pisagor/props";
import { tagsInputItemRecipe, tagsInputRecipe } from "@pisagor/recipes";
import type { ComponentProps, JSX } from "solid-js";
import { For, Show, splitProps } from "solid-js";
import { XIcon } from "../../internal/icons";
import { InputGroup, type InputGroupProps } from "../input-group";
import {
  TagsInputItemContext,
  TagsInputSlotsContext,
  useTagsInput,
  useTagsInputItem,
} from "./tags-input.context";

export type TagsInputRootProps = Omit<
  TagsInputPrimitiveRootProps,
  "onValueChange"
> &
  Pick<InputGroupProps, "size" | "variant">;

export interface TagsInputProps
  extends TagsInputRootProps,
    TagsInputSharedProps {
  clearable?: boolean;
  placeholder?: string;
  onValueChange?: (value: string[]) => void;
}

export interface TagsInputControlProps
  extends TagsInputPrimitiveControlProps,
    Pick<InputGroupProps, "size" | "variant"> {
  clearable?: boolean;
}

export interface TagsInputItemProps
  extends TagsInputPrimitiveItemProps,
    Pick<InputGroupProps, "size">,
    TagsInputItemSharedProps {
  showDelete?: boolean;
}

export interface TagsInputRootProviderProps
  extends TagsInputPrimitiveRootProviderProps,
    Pick<InputGroupProps, "size">,
    TagsInputSharedProps {
  clearable?: boolean;
}

export type TagsInputItemDeleteTriggerProps = ComponentProps<
  typeof TagsInputPrimitive.ItemDeleteTrigger
>;

export const TagsInputContext = TagsInputPrimitive.Context;

export function TagsInputRoot(props: TagsInputProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "variant",
    "clearable",
    "tabIndex",
    "children",
    "editable",
    "placeholder",
    "onValueChange",
    "recipe",
    "class",
  ]);
  const slots = () => (local.recipe ?? tagsInputRecipe)();
  const size = () => local.size ?? "md";

  return (
    <TagsInputSlotsContext value={{ slots: slots() }}>
      <TagsInputPrimitive.Root
        {...rest}
        class={slots().base({ class: local.class })}
        data-size={size()}
        editable={local.editable ?? false}
        onValueChange={
          local.onValueChange
            ? (details) => local.onValueChange?.(details.value)
            : undefined
        }
      >
        <TagsInputControl clearable={local.clearable} variant={local.variant}>
          <TagsInputPrimitive.Context>
            {(api) => (
              <For each={api().value}>
                {(value, index) => (
                  <TagsInputItem index={index()} value={value} />
                )}
              </For>
            )}
          </TagsInputPrimitive.Context>
          {local.children}
          <TagsInputInput placeholder={local.placeholder} />
        </TagsInputControl>
        <TagsInputPrimitive.HiddenInput tabIndex={local.tabIndex} />
      </TagsInputPrimitive.Root>
    </TagsInputSlotsContext>
  );
}

export function TagsInputControl(props: TagsInputControlProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "variant",
    "clearable",
    "children",
    "class",
  ]);
  const api = useTagsInputContext();
  const { slots } = useTagsInput();
  const clearable = () => local.clearable ?? false;

  return (
    <TagsInputPrimitive.Control
      asChild={(controlProps) => (
        <InputGroup
          {...controlProps({ class: slots.control({ class: local.class }) })}
          {...rest}
          size={local.size}
          variant={local.variant}
        >
          {local.children}
          <Show when={clearable() && api().value.length > 0}>
            <TagsInputClearTrigger aria-label="Clear all tags" />
          </Show>
        </InputGroup>
      )}
    />
  );
}

export function TagsInputItem(props: TagsInputItemProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "showDelete",
    "children",
    "recipe",
    "class",
  ]);
  const slots = () => (local.recipe ?? tagsInputItemRecipe)();
  const showDelete = () => local.showDelete ?? true;

  return (
    <TagsInputItemContext value={{ slots: slots() }}>
      <TagsInputPrimitive.Item
        {...rest}
        class={slots().base({ class: local.class })}
      >
        <TagsInputItemPreview>
          <TagsInputItemText>{local.children}</TagsInputItemText>
          <Show when={showDelete()}>
            <TagsInputItemDeleteTrigger />
          </Show>
        </TagsInputItemPreview>
        <TagsInputItemInput />
      </TagsInputPrimitive.Item>
    </TagsInputItemContext>
  );
}

export function TagsInputItemPreview(
  props: TagsInputItemPreviewProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useTagsInputItem();
  return (
    <TagsInputPrimitive.ItemPreview
      {...rest}
      class={slots.preview({ class: local.class })}
    />
  );
}

export function TagsInputItemText(props: TagsInputItemTextProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);
  const { slots } = useTagsInputItem();
  return (
    <TagsInputPrimitive.ItemText
      {...rest}
      class={slots.text({ class: local.class })}
    />
  );
}

export function TagsInputItemDeleteTrigger(
  props: TagsInputItemDeleteTriggerProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useTagsInputItem();

  return (
    <TagsInputPrimitive.ItemDeleteTrigger
      {...rest}
      asChild={(triggerProps) => (
        <InputGroup.Button
          {...triggerProps({ class: slots.delete({ class: local.class }) })}
          aria-label="Remove tag"
          size="icon-xs"
          variant="ghost"
        >
          {local.children ?? <XIcon aria-hidden />}
        </InputGroup.Button>
      )}
    />
  );
}

export function TagsInputItemInput(
  props: TagsInputItemInputProps,
): JSX.Element {
  const { slots } = useTagsInputItem();
  return (
    <TagsInputPrimitive.ItemInput
      {...props}
      asChild={(inputProps) => (
        <InputGroup.Input {...inputProps({ class: slots.input() })} />
      )}
    />
  );
}

export function TagsInputInput(props: TagsInputInputProps): JSX.Element {
  const { slots } = useTagsInput();
  return (
    <TagsInputPrimitive.Input
      {...props}
      asChild={(inputProps) => (
        <InputGroup.Input {...inputProps({ class: slots.input() })} />
      )}
    />
  );
}

export function TagsInputClearTrigger(
  props: TagsInputClearTriggerProps,
): JSX.Element {
  const [local, rest] = splitProps(props, ["children", "class"]);
  const { slots } = useTagsInput();

  return (
    <TagsInputPrimitive.ClearTrigger
      {...rest}
      asChild={(triggerProps) => (
        <InputGroup.Button
          {...triggerProps({
            class: slots.clearTrigger({ class: local.class }),
          })}
          aria-label="Clear"
          size="icon-xs"
          variant="ghost"
        >
          {local.children ?? <XIcon aria-hidden />}
        </InputGroup.Button>
      )}
    />
  );
}

export function TagsInputRootProvider(
  props: TagsInputRootProviderProps,
): JSX.Element {
  const [local, rest] = splitProps(props, [
    "size",
    "clearable",
    "children",
    "recipe",
    "class",
  ]);
  const slots = () => (local.recipe ?? tagsInputRecipe)();
  const size = () => local.size ?? "md";

  return (
    <TagsInputSlotsContext value={{ slots: slots() }}>
      <TagsInputPrimitive.RootProvider
        {...rest}
        class={slots().base({ class: local.class })}
        data-size={size()}
      >
        <TagsInputControl clearable={local.clearable}>
          {local.children}
        </TagsInputControl>
        <TagsInputPrimitive.HiddenInput />
      </TagsInputPrimitive.RootProvider>
    </TagsInputSlotsContext>
  );
}
